import { vars } from 'nativewind';
import { THEMES } from '../themes';

/**
 * Shade colors that persist across all themes
 */
const shadeColors = {
  '--color-shade-100': '#FF5841',
  '--color-shade-200': '#FF353C',
  '--color-shade-300': '#ED0C46',
  '--color-shade-400': '#CF014E',
  '--color-shade-500': '#BF004E',
  // Red colors
  '--color-red-100': '#F8E0E6',
  '--color-red-200': '#E4A3B4',
  '--color-red-300': '#ED0C46',
  '--color-red-400': '#BF0A39',
  '--color-red-500': '#9A082E',
  // Green colors
  '--color-green-100': '#E0F8E0',
  '--color-green-200': '#A3E4A3',
  '--color-green-300': '#0CED3E',
  '--color-green-400': '#0ABF35',
  '--color-green-500': '#089A2C',
  // Purple colors
  '--color-purple-100': '#E0E0F8',
  '--color-purple-200': '#A3A3E4',
  '--color-purple-300': '#8A2BE2',
  '--color-purple-400': '#6A0DAD',
  '--color-purple-500': '#4B0082',
};

/**
 * Theme variables using CSS variables for dynamic theming
 * Based on the Medium article approach
 */
export const colorThemes = {
  // Navy theme
  navy: vars({
    '--color-primary-950': THEMES['navy'][950],
    '--color-primary-900': THEMES['navy'][900],
    '--color-primary-800': THEMES['navy'][800],
    '--color-primary-700': THEMES['navy'][700],
    '--color-primary-600': THEMES['navy'][600],
    '--color-primary-500': THEMES['navy'][500],
    '--color-primary-400': THEMES['navy'][400],
    '--color-primary-300': THEMES['navy'][300],
    '--color-primary-200': THEMES['navy'][200],
    '--color-primary-100': THEMES['navy'][100],
    '--color-primary-50': THEMES['navy'][50],
    '--color-primary-0': THEMES['navy'][0],
    ...shadeColors,
  }),

  // Coral theme
  coral: vars({
    '--color-primary-950': THEMES['coral-sunrise'][950],
    '--color-primary-900': THEMES['coral-sunrise'][900],
    '--color-primary-800': THEMES['coral-sunrise'][800],
    '--color-primary-700': THEMES['coral-sunrise'][700],
    '--color-primary-600': THEMES['coral-sunrise'][600],
    '--color-primary-500': THEMES['coral-sunrise'][500],
    '--color-primary-400': THEMES['coral-sunrise'][400],
    '--color-primary-300': THEMES['coral-sunrise'][300],
    '--color-primary-200': THEMES['coral-sunrise'][200],
    '--color-primary-100': THEMES['coral-sunrise'][100],
    '--color-primary-50': THEMES['coral-sunrise'][50],
    '--color-primary-0': THEMES['coral-sunrise'][0],
    ...shadeColors,
  }),

  // Ice theme
  ice: vars({
    '--color-primary-950': THEMES['ice-queen'][950],
    '--color-primary-900': THEMES['ice-queen'][900],
    '--color-primary-800': THEMES['ice-queen'][800],
    '--color-primary-700': THEMES['ice-queen'][700],
    '--color-primary-600': THEMES['ice-queen'][600],
    '--color-primary-500': THEMES['ice-queen'][500],
    '--color-primary-400': THEMES['ice-queen'][400],
    '--color-primary-300': THEMES['ice-queen'][300],
    '--color-primary-200': THEMES['ice-queen'][200],
    '--color-primary-100': THEMES['ice-queen'][100],
    '--color-primary-50': THEMES['ice-queen'][50],
    '--color-primary-0': THEMES['ice-queen'][0],
    ...shadeColors,
  }),

  // Tropical theme
  tropical: vars({
    '--color-primary-950': THEMES['tropical-forest'][950],
    '--color-primary-900': THEMES['tropical-forest'][900],
    '--color-primary-800': THEMES['tropical-forest'][800],
    '--color-primary-700': THEMES['tropical-forest'][700],
    '--color-primary-600': THEMES['tropical-forest'][600],
    '--color-primary-500': THEMES['tropical-forest'][500],
    '--color-primary-400': THEMES['tropical-forest'][400],
    '--color-primary-300': THEMES['tropical-forest'][300],
    '--color-primary-200': THEMES['tropical-forest'][200],
    '--color-primary-100': THEMES['tropical-forest'][100],
    '--color-primary-50': THEMES['tropical-forest'][50],
    '--color-primary-0': THEMES['tropical-forest'][0],
    ...shadeColors,
  }),

  // Desert theme
  desert: vars({
    '--color-primary-950': THEMES['desert-dune'][950],
    '--color-primary-900': THEMES['desert-dune'][900],
    '--color-primary-800': THEMES['desert-dune'][800],
    '--color-primary-700': THEMES['desert-dune'][700],
    '--color-primary-600': THEMES['desert-dune'][600],
    '--color-primary-500': THEMES['desert-dune'][500],
    '--color-primary-400': THEMES['desert-dune'][400],
    '--color-primary-300': THEMES['desert-dune'][300],
    '--color-primary-200': THEMES['desert-dune'][200],
    '--color-primary-100': THEMES['desert-dune'][100],
    '--color-primary-50': THEMES['desert-dune'][50],
    '--color-primary-0': THEMES['desert-dune'][0],
    ...shadeColors,
  }),

  // Misty theme
  misty: vars({
    '--color-primary-950': THEMES['misty-morning'][950],
    '--color-primary-900': THEMES['misty-morning'][900],
    '--color-primary-800': THEMES['misty-morning'][800],
    '--color-primary-700': THEMES['misty-morning'][700],
    '--color-primary-600': THEMES['misty-morning'][600],
    '--color-primary-500': THEMES['misty-morning'][500],
    '--color-primary-400': THEMES['misty-morning'][400],
    '--color-primary-300': THEMES['misty-morning'][300],
    '--color-primary-200': THEMES['misty-morning'][200],
    '--color-primary-100': THEMES['misty-morning'][100],
    '--color-primary-50': THEMES['misty-morning'][50],
    '--color-primary-0': THEMES['misty-morning'][0],
    ...shadeColors,
  }),

  // Neon theme
  neon: vars({
    '--color-primary-950': THEMES['neon-dream'][950],
    '--color-primary-900': THEMES['neon-dream'][900],
    '--color-primary-800': THEMES['neon-dream'][800],
    '--color-primary-700': THEMES['neon-dream'][700],
    '--color-primary-600': THEMES['neon-dream'][600],
    '--color-primary-500': THEMES['neon-dream'][500],
    '--color-primary-400': THEMES['neon-dream'][400],
    '--color-primary-300': THEMES['neon-dream'][300],
    '--color-primary-200': THEMES['neon-dream'][200],
    '--color-primary-100': THEMES['neon-dream'][100],
    '--color-primary-50': THEMES['neon-dream'][50],
    '--color-primary-0': THEMES['neon-dream'][0],
    ...shadeColors,
  }),

  // Cosmic theme
  cosmic: vars({
    '--color-primary-950': THEMES['cosmic-ember'][950],
    '--color-primary-900': THEMES['cosmic-ember'][900],
    '--color-primary-800': THEMES['cosmic-ember'][800],
    '--color-primary-700': THEMES['cosmic-ember'][700],
    '--color-primary-600': THEMES['cosmic-ember'][600],
    '--color-primary-500': THEMES['cosmic-ember'][500],
    '--color-primary-400': THEMES['cosmic-ember'][400],
    '--color-primary-300': THEMES['cosmic-ember'][300],
    '--color-primary-200': THEMES['cosmic-ember'][200],
    '--color-primary-100': THEMES['cosmic-ember'][100],
    '--color-primary-50': THEMES['cosmic-ember'][50],
    '--color-primary-0': THEMES['cosmic-ember'][0],
    ...shadeColors,
  }),

  // Digital theme
  digital: vars({
    '--color-primary-950': THEMES['digital-oasis'][950],
    '--color-primary-900': THEMES['digital-oasis'][900],
    '--color-primary-800': THEMES['digital-oasis'][800],
    '--color-primary-700': THEMES['digital-oasis'][700],
    '--color-primary-600': THEMES['digital-oasis'][600],
    '--color-primary-500': THEMES['digital-oasis'][500],
    '--color-primary-400': THEMES['digital-oasis'][400],
    '--color-primary-300': THEMES['digital-oasis'][300],
    '--color-primary-200': THEMES['digital-oasis'][200],
    '--color-primary-100': THEMES['digital-oasis'][100],
    '--color-primary-50': THEMES['digital-oasis'][50],
    '--color-primary-0': THEMES['digital-oasis'][0],
    ...shadeColors,
  }),

  // Celestial theme
  celestial: vars({
    '--color-primary-950': THEMES['celestial-aura'][950],
    '--color-primary-900': THEMES['celestial-aura'][900],
    '--color-primary-800': THEMES['celestial-aura'][800],
    '--color-primary-700': THEMES['celestial-aura'][700],
    '--color-primary-600': THEMES['celestial-aura'][600],
    '--color-primary-500': THEMES['celestial-aura'][500],
    '--color-primary-400': THEMES['celestial-aura'][400],
    '--color-primary-300': THEMES['celestial-aura'][300],
    '--color-primary-200': THEMES['celestial-aura'][200],
    '--color-primary-100': THEMES['celestial-aura'][100],
    '--color-primary-50': THEMES['celestial-aura'][50],
    '--color-primary-0': THEMES['celestial-aura'][0],
    ...shadeColors,
  }),

  // Urban theme
  urban: vars({
    '--color-primary-950': THEMES['urban-concrete'][950],
    '--color-primary-900': THEMES['urban-concrete'][900],
    '--color-primary-800': THEMES['urban-concrete'][800],
    '--color-primary-700': THEMES['urban-concrete'][700],
    '--color-primary-600': THEMES['urban-concrete'][600],
    '--color-primary-500': THEMES['urban-concrete'][500],
    '--color-primary-400': THEMES['urban-concrete'][400],
    '--color-primary-300': THEMES['urban-concrete'][300],
    '--color-primary-200': THEMES['urban-concrete'][200],
    '--color-primary-100': THEMES['urban-concrete'][100],
    '--color-primary-50': THEMES['urban-concrete'][50],
    '--color-primary-0': THEMES['urban-concrete'][0],
    ...shadeColors,
  }),

  // Volcanic theme
  volcanic: vars({
    '--color-primary-950': THEMES['volcanic-crimson'][950],
    '--color-primary-900': THEMES['volcanic-crimson'][900],
    '--color-primary-800': THEMES['volcanic-crimson'][800],
    '--color-primary-700': THEMES['volcanic-crimson'][700],
    '--color-primary-600': THEMES['volcanic-crimson'][600],
    '--color-primary-500': THEMES['volcanic-crimson'][500],
    '--color-primary-400': THEMES['volcanic-crimson'][400],
    '--color-primary-300': THEMES['volcanic-crimson'][300],
    '--color-primary-200': THEMES['volcanic-crimson'][200],
    '--color-primary-100': THEMES['volcanic-crimson'][100],
    '--color-primary-50': THEMES['volcanic-crimson'][50],
    '--color-primary-0': THEMES['volcanic-crimson'][0],
    ...shadeColors,
  }),

  // Crimson theme
  crimson: vars({
    '--color-primary-950': THEMES['crimson-night'][950],
    '--color-primary-900': THEMES['crimson-night'][900],
    '--color-primary-800': THEMES['crimson-night'][800],
    '--color-primary-700': THEMES['crimson-night'][700],
    '--color-primary-600': THEMES['crimson-night'][600],
    '--color-primary-500': THEMES['crimson-night'][500],
    '--color-primary-400': THEMES['crimson-night'][400],
    '--color-primary-300': THEMES['crimson-night'][300],
    '--color-primary-200': THEMES['crimson-night'][200],
    '--color-primary-100': THEMES['crimson-night'][100],
    '--color-primary-50': THEMES['crimson-night'][50],
    '--color-primary-0': THEMES['crimson-night'][0],
    ...shadeColors,
  }),

  // Velvet theme
  velvet: vars({
    '--color-primary-950': THEMES['velvet-emerald'][950],
    '--color-primary-900': THEMES['velvet-emerald'][900],
    '--color-primary-800': THEMES['velvet-emerald'][800],
    '--color-primary-700': THEMES['velvet-emerald'][700],
    '--color-primary-600': THEMES['velvet-emerald'][600],
    '--color-primary-500': THEMES['velvet-emerald'][500],
    '--color-primary-400': THEMES['velvet-emerald'][400],
    '--color-primary-300': THEMES['velvet-emerald'][300],
    '--color-primary-200': THEMES['velvet-emerald'][200],
    '--color-primary-100': THEMES['velvet-emerald'][100],
    '--color-primary-50': THEMES['velvet-emerald'][50],
    '--color-primary-0': THEMES['velvet-emerald'][0],
    ...shadeColors,
  }),

  // Twilight theme
  twilight: vars({
    '--color-primary-950': THEMES['twilight-amber'][950],
    '--color-primary-900': THEMES['twilight-amber'][900],
    '--color-primary-800': THEMES['twilight-amber'][800],
    '--color-primary-700': THEMES['twilight-amber'][700],
    '--color-primary-600': THEMES['twilight-amber'][600],
    '--color-primary-500': THEMES['twilight-amber'][500],
    '--color-primary-400': THEMES['twilight-amber'][400],
    '--color-primary-300': THEMES['twilight-amber'][300],
    '--color-primary-200': THEMES['twilight-amber'][200],
    '--color-primary-100': THEMES['twilight-amber'][100],
    '--color-primary-50': THEMES['twilight-amber'][50],
    '--color-primary-0': THEMES['twilight-amber'][0],
    ...shadeColors,
  }),

  // Retro theme
  retro: vars({
    '--color-primary-950': THEMES['retro-outrun'][950],
    '--color-primary-900': THEMES['retro-outrun'][900],
    '--color-primary-800': THEMES['retro-outrun'][800],
    '--color-primary-700': THEMES['retro-outrun'][700],
    '--color-primary-600': THEMES['retro-outrun'][600],
    '--color-primary-500': THEMES['retro-outrun'][500],
    '--color-primary-400': THEMES['retro-outrun'][400],
    '--color-primary-300': THEMES['retro-outrun'][300],
    '--color-primary-200': THEMES['retro-outrun'][200],
    '--color-primary-100': THEMES['retro-outrun'][100],
    '--color-primary-50': THEMES['retro-outrun'][50],
    '--color-primary-0': THEMES['retro-outrun'][0],
    ...shadeColors,
  }),

  // Light beige theme
  lightbeige: vars({
    '--color-primary-950': THEMES['light-beige'][950],
    '--color-primary-900': THEMES['light-beige'][900],
    '--color-primary-800': THEMES['light-beige'][800],
    '--color-primary-700': THEMES['light-beige'][700],
    '--color-primary-600': THEMES['light-beige'][600],
    '--color-primary-500': THEMES['light-beige'][500],
    '--color-primary-400': THEMES['light-beige'][400],
    '--color-primary-300': THEMES['light-beige'][300],
    '--color-primary-200': THEMES['light-beige'][200],
    '--color-primary-100': THEMES['light-beige'][100],
    '--color-primary-50': THEMES['light-beige'][50],
    '--color-primary-0': THEMES['light-beige'][0],
    ...shadeColors,
  }),

  // Beige theme
  beige: vars({
    '--color-primary-950': THEMES['beige'][950],
    '--color-primary-900': THEMES['beige'][900],
    '--color-primary-800': THEMES['beige'][800],
    '--color-primary-700': THEMES['beige'][700],
    '--color-primary-600': THEMES['beige'][600],
    '--color-primary-500': THEMES['beige'][500],
    '--color-primary-400': THEMES['beige'][400],
    '--color-primary-300': THEMES['beige'][300],
    '--color-primary-200': THEMES['beige'][200],
    '--color-primary-100': THEMES['beige'][100],
    '--color-primary-50': THEMES['beige'][50],
    '--color-primary-0': THEMES['beige'][0],
    ...shadeColors,
  }),

  // Middle beige theme
  middlebeige: vars({
    '--color-primary-950': THEMES['middle-beige'][950],
    '--color-primary-900': THEMES['middle-beige'][900],
    '--color-primary-800': THEMES['middle-beige'][800],
    '--color-primary-700': THEMES['middle-beige'][700],
    '--color-primary-600': THEMES['middle-beige'][600],
    '--color-primary-500': THEMES['middle-beige'][500],
    '--color-primary-400': THEMES['middle-beige'][400],
    '--color-primary-300': THEMES['middle-beige'][300],
    '--color-primary-200': THEMES['middle-beige'][200],
    '--color-primary-100': THEMES['middle-beige'][100],
    '--color-primary-50': THEMES['middle-beige'][50],
    '--color-primary-0': THEMES['middle-beige'][0],
    ...shadeColors,
  }),

  // Light theme
  light: vars({
    '--color-primary-950': THEMES['light'][950],
    '--color-primary-900': THEMES['light'][900],
    '--color-primary-800': THEMES['light'][800],
    '--color-primary-700': THEMES['light'][700],
    '--color-primary-600': THEMES['light'][600],
    '--color-primary-500': THEMES['light'][500],
    '--color-primary-400': THEMES['light'][400],
    '--color-primary-300': THEMES['light'][300],
    '--color-primary-200': THEMES['light'][200],
    '--color-primary-100': THEMES['light'][100],
    '--color-primary-50': THEMES['light'][50],
    '--color-primary-0': THEMES['light'][0],
    ...shadeColors,
  }),

  // Forest theme
  forest: vars({
    '--color-primary-950': THEMES['forest'][950],
    '--color-primary-900': THEMES['forest'][900],
    '--color-primary-800': THEMES['forest'][800],
    '--color-primary-700': THEMES['forest'][700],
    '--color-primary-600': THEMES['forest'][600],
    '--color-primary-500': THEMES['forest'][500],
    '--color-primary-400': THEMES['forest'][400],
    '--color-primary-300': THEMES['forest'][300],
    '--color-primary-200': THEMES['forest'][200],
    '--color-primary-100': THEMES['forest'][100],
    '--color-primary-50': THEMES['forest'][50],
    '--color-primary-0': THEMES['forest'][0],
    ...shadeColors,
  }),

  // Sunset theme
  sunset: vars({
    '--color-primary-950': THEMES['sunset'][950],
    '--color-primary-900': THEMES['sunset'][900],
    '--color-primary-800': THEMES['sunset'][800],
    '--color-primary-700': THEMES['sunset'][700],
    '--color-primary-600': THEMES['sunset'][600],
    '--color-primary-500': THEMES['sunset'][500],
    '--color-primary-400': THEMES['sunset'][400],
    '--color-primary-300': THEMES['sunset'][300],
    '--color-primary-200': THEMES['sunset'][200],
    '--color-primary-100': THEMES['sunset'][100],
    '--color-primary-50': THEMES['sunset'][50],
    '--color-primary-0': THEMES['sunset'][0],
    ...shadeColors,
  }),

  // Ocean theme
  ocean: vars({
    '--color-primary-950': THEMES['ocean'][950],
    '--color-primary-900': THEMES['ocean'][900],
    '--color-primary-800': THEMES['ocean'][800],
    '--color-primary-700': THEMES['ocean'][700],
    '--color-primary-600': THEMES['ocean'][600],
    '--color-primary-500': THEMES['ocean'][500],
    '--color-primary-400': THEMES['ocean'][400],
    '--color-primary-300': THEMES['ocean'][300],
    '--color-primary-200': THEMES['ocean'][200],
    '--color-primary-100': THEMES['ocean'][100],
    '--color-primary-50': THEMES['ocean'][50],
    '--color-primary-0': THEMES['ocean'][0],
    ...shadeColors,
  }),

  // Dark grey theme
  darkgrey: vars({
    '--color-primary-950': THEMES['dark-grey'][950],
    '--color-primary-900': THEMES['dark-grey'][900],
    '--color-primary-800': THEMES['dark-grey'][800],
    '--color-primary-700': THEMES['dark-grey'][700],
    '--color-primary-600': THEMES['dark-grey'][600],
    '--color-primary-500': THEMES['dark-grey'][500],
    '--color-primary-400': THEMES['dark-grey'][400],
    '--color-primary-300': THEMES['dark-grey'][300],
    '--color-primary-200': THEMES['dark-grey'][200],
    '--color-primary-100': THEMES['dark-grey'][100],
    '--color-primary-50': THEMES['dark-grey'][50],
    '--color-primary-0': THEMES['dark-grey'][0],
    ...shadeColors,
  }),

  // Slate theme
  slate: vars({
    '--color-primary-950': THEMES['slate-shadow'][950],
    '--color-primary-900': THEMES['slate-shadow'][900],
    '--color-primary-800': THEMES['slate-shadow'][800],
    '--color-primary-700': THEMES['slate-shadow'][700],
    '--color-primary-600': THEMES['slate-shadow'][600],
    '--color-primary-500': THEMES['slate-shadow'][500],
    '--color-primary-400': THEMES['slate-shadow'][400],
    '--color-primary-300': THEMES['slate-shadow'][300],
    '--color-primary-200': THEMES['slate-shadow'][200],
    '--color-primary-100': THEMES['slate-shadow'][100],
    '--color-primary-50': THEMES['slate-shadow'][50],
    '--color-primary-0': THEMES['slate-shadow'][0],
    ...shadeColors,
  }),

  // Mystic theme
  mystic: vars({
    '--color-primary-950': THEMES['mystic-fog'][950],
    '--color-primary-900': THEMES['mystic-fog'][900],
    '--color-primary-800': THEMES['mystic-fog'][800],
    '--color-primary-700': THEMES['mystic-fog'][700],
    '--color-primary-600': THEMES['mystic-fog'][600],
    '--color-primary-500': THEMES['mystic-fog'][500],
    '--color-primary-400': THEMES['mystic-fog'][400],
    '--color-primary-300': THEMES['mystic-fog'][300],
    '--color-primary-200': THEMES['mystic-fog'][200],
    '--color-primary-100': THEMES['mystic-fog'][100],
    '--color-primary-50': THEMES['mystic-fog'][50],
    '--color-primary-0': THEMES['mystic-fog'][0],
    ...shadeColors,
  }),

  // Eclipse theme
  eclipse: vars({
    '--color-primary-950': THEMES['eclipse-steel'][950],
    '--color-primary-900': THEMES['eclipse-steel'][900],
    '--color-primary-800': THEMES['eclipse-steel'][800],
    '--color-primary-700': THEMES['eclipse-steel'][700],
    '--color-primary-600': THEMES['eclipse-steel'][600],
    '--color-primary-500': THEMES['eclipse-steel'][500],
    '--color-primary-400': THEMES['eclipse-steel'][400],
    '--color-primary-300': THEMES['eclipse-steel'][300],
    '--color-primary-200': THEMES['eclipse-steel'][200],
    '--color-primary-100': THEMES['eclipse-steel'][100],
    '--color-primary-50': THEMES['eclipse-steel'][50],
    '--color-primary-0': THEMES['eclipse-steel'][0],
    ...shadeColors,
  }),

  // Aurora theme
  aurora: vars({
    '--color-primary-950': THEMES['aurora-twilight'][950],
    '--color-primary-900': THEMES['aurora-twilight'][900],
    '--color-primary-800': THEMES['aurora-twilight'][800],
    '--color-primary-700': THEMES['aurora-twilight'][700],
    '--color-primary-600': THEMES['aurora-twilight'][600],
    '--color-primary-500': THEMES['aurora-twilight'][500],
    '--color-primary-400': THEMES['aurora-twilight'][400],
    '--color-primary-300': THEMES['aurora-twilight'][300],
    '--color-primary-200': THEMES['aurora-twilight'][200],
    '--color-primary-100': THEMES['aurora-twilight'][100],
    '--color-primary-50': THEMES['aurora-twilight'][50],
    '--color-primary-0': THEMES['aurora-twilight'][0],
    ...shadeColors,
  }),

  // Rose theme
  rose: vars({
    '--color-primary-950': THEMES['rose'][950],
    '--color-primary-900': THEMES['rose'][900],
    '--color-primary-800': THEMES['rose'][800],
    '--color-primary-700': THEMES['rose'][700],
    '--color-primary-600': THEMES['rose'][600],
    '--color-primary-500': THEMES['rose'][500],
    '--color-primary-400': THEMES['rose'][400],
    '--color-primary-300': THEMES['rose'][300],
    '--color-primary-200': THEMES['rose'][200],
    '--color-primary-100': THEMES['rose'][100],
    '--color-primary-50': THEMES['rose'][50],
    '--color-primary-0': THEMES['rose'][0],
    ...shadeColors,
  }),

  // Autumn theme
  autumn: vars({
    '--color-primary-950': THEMES['autumn'][950],
    '--color-primary-900': THEMES['autumn'][900],
    '--color-primary-800': THEMES['autumn'][800],
    '--color-primary-700': THEMES['autumn'][700],
    '--color-primary-600': THEMES['autumn'][600],
    '--color-primary-500': THEMES['autumn'][500],
    '--color-primary-400': THEMES['autumn'][400],
    '--color-primary-300': THEMES['autumn'][300],
    '--color-primary-200': THEMES['autumn'][200],
    '--color-primary-100': THEMES['autumn'][100],
    '--color-primary-50': THEMES['autumn'][50],
    '--color-primary-0': THEMES['autumn'][0],
    ...shadeColors,
  }),

  // Dark theme (default)
  dark: vars({
    '--color-primary-950': THEMES['dark'][950],
    '--color-primary-900': THEMES['dark'][900],
    '--color-primary-800': THEMES['dark'][800],
    '--color-primary-700': THEMES['dark'][700],
    '--color-primary-600': THEMES['dark'][600],
    '--color-primary-500': THEMES['dark'][500],
    '--color-primary-400': THEMES['dark'][400],
    '--color-primary-300': THEMES['dark'][300],
    '--color-primary-200': THEMES['dark'][200],
    '--color-primary-100': THEMES['dark'][100],
    '--color-primary-50': THEMES['dark'][50],
    '--color-primary-0': THEMES['dark'][0],
    ...shadeColors,
  }),

  // Background Image Themes
  // Deep Ocean (bg17.png)
  deepocean: vars({
    '--color-primary-950': '#030d10',
    '--color-primary-900': '#111216',
    '--color-primary-800': '#15161b',
    '--color-primary-700': '#181a20',
    '--color-primary-600': '#1c1e24',
    '--color-primary-500': '#262932',
    '--color-primary-400': '#474c5d',
    '--color-primary-300': '#696f87',
    '--color-primary-200': '#9da1b3',
    '--color-primary-100': '#c0c3ce',
    '--color-primary-50': '#e8e9ed',
    '--color-primary-0': '#FFFFFF',
    ...shadeColors,
  }),

  // Cosmic Purple (bg9.png)
  cosmicpurple: vars({
    '--color-primary-950': '#070311',
    '--color-primary-900': '#120f1a',
    '--color-primary-800': '#15121e',
    '--color-primary-700': '#191424',
    '--color-primary-600': '#1c1729',
    '--color-primary-500': '#272038',
    '--color-primary-400': '#483c68',
    '--color-primary-300': '#695898',
    '--color-primary-200': '#9d91bf',
    '--color-primary-100': '#c0b8d6',
    '--color-primary-50': '#e8e5f0',
    '--color-primary-0': '#FFFFFF',
    ...shadeColors,
  }),

  // Mystic Blue (bg8.png)
  mysticblue: vars({
    '--color-primary-950': '#05030f',
    '--color-primary-900': '#111019',
    '--color-primary-800': '#14131d',
    '--color-primary-700': '#171622',
    '--color-primary-600': '#1b1927',
    '--color-primary-500': '#242236',
    '--color-primary-400': '#444064',
    '--color-primary-300': '#645e92',
    '--color-primary-200': '#9995bb',
    '--color-primary-100': '#bdbbd3',
    '--color-primary-50': '#e7e6ef',
    '--color-primary-0': '#FFFFFF',
    ...shadeColors,
  }),

  // Royal Purple (bg6.png)
  royalpurple: vars({
    '--color-primary-950': '#030112',
    '--color-primary-900': '#100e1b',
    '--color-primary-800': '#131020',
    '--color-primary-700': '#161325',
    '--color-primary-600': '#19162a',
    '--color-primary-500': '#221e3a',
    '--color-primary-400': '#40386c',
    '--color-primary-300': '#5e529e',
    '--color-primary-200': '#958cc4',
    '--color-primary-100': '#bbb5d9',
    '--color-primary-50': '#e6e4f1',
    '--color-primary-0': '#FFFFFF',
    ...shadeColors,
  }),
};
