/* global __dirname */
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');

// eslint-plugin-react-compiler@19.1.0-rc.2 calls zod@3's `z.function().args()`,
// which the repo-wide `zod@4` override (package.json `overrides`) removes — so
// `require`-ing it throws at config-load and crashes the ENTIRE lint run. Load
// it defensively: lint must keep working (the dozens of correctness rules below
// matter far more than this single non-blocking `warn`). Re-enable
// unconditionally once the plugin supports zod 4, or migrate the rule to
// eslint-plugin-react-hooks v6 (`react-hooks/react-compiler`).
// Revisit when the plugin can load under the repo-wide zod v4 override.
let reactCompilerPlugin = null;
try {
  reactCompilerPlugin = require('eslint-plugin-react-compiler');
} catch {
  reactCompilerPlugin = null;
}

module.exports = defineConfig([
  // Global ignores — apply to every config below. Listed first because a
  // flat-config block with only `ignores` (no `files`) is treated as a
  // global ignore by ESLint v9.
  {
    ignores: [
      'dist/**',
      // Vendored build output (`@internet-privacy/marmot-ts` is a file-dep
      // pointing at vendor/marmot-ts/dist).
      'vendor/**',
      // Compiled package output. `packages/*/src` stays in scope.
      'packages/*/lib/**',
      // Per-package build-time scripts — same shape as top-level scripts/,
      // Node-only tooling.
      'packages/*/scripts/**',
      // Native module subprojects — not part of the JS lint surface.
      'modules/**',
      // Tooling scripts run under Node, not the app TS project.
      'codereview/**',
      'scripts/**',
      // Native iOS app extension targets (widget, etc) — Swift + plist
      // plus a `expo-target.config.js` that legitimately holds hex
      // colors for the native side.
      'targets/**',
      // ios/android build dirs (defensive — usually gitignored).
      'ios/**',
      'android/**',
      // Subagent skill template files — outside the TS project, parser
      // can't resolve them. Not part of the runtime surface.
      '.agents/**',
      // Generated by Uniwind; formatting it by hand is overwritten by the
      // generator and was creating editor/CI noise.
      'expo-env.d.ts',
      'uniwind-types.d.ts',
    ],
  },
  expoConfig,
  eslintPluginPrettierRecommended,
  // Type-aware linting for the TS/TSX project. `projectService: true` lets
  // typescript-eslint pick up `tsconfig.json` without us hand-maintaining a
  // `parserOptions.project` array. Required for any rule that needs type
  // info (`no-floating-promises`, `no-misused-promises`, `no-unsafe-*`, etc.).
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      // Catches every `any`-typed value at the seam — the exact shape we
      // keep paying for in audit slices ("drop type-laundering casts",
      // "drop operation:any casts", "narrow Button/Spinner any").
      '@typescript-eslint/no-explicit-any': 'error',
      // Override eslint-config-expo's `warn` + `allow` to `error` + `never`,
      // banning both `<T>x` style and `{ ... } as T` object-literal casts.
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'as', objectLiteralTypeAssertions: 'never' },
      ],
      // Catches un-awaited promises — the shape behind the "cancel async
      // writes on effect cleanup" and "thread AbortSignal through apiClient"
      // slices. Allow `void promise` as the explicit fire-and-forget escape.
      '@typescript-eslint/no-floating-promises': ['error', { ignoreVoid: true }],
      // Catches async functions passed where a sync callback is expected
      // (e.g. `onPress={async () => ...}` — fine, but `useEffect(async ...)`
      // — not fine). Allow void-returning attribute handlers, ban only the
      // ones that genuinely break (return-position promise-as-boolean,
      // spread, etc.).
      '@typescript-eslint/no-misused-promises': [
        'error',
        {
          checksVoidReturn: { attributes: false, arguments: false },
        },
      ],
    },
  },
  // React-perf rules — catch inline `{}`, `[]`, and `() => ...` passed
  // as JSX props. Every render creates a fresh reference, defeating
  // `React.memo` / `useMemo` downstream and re-firing
  // `useEffect`/`useCallback` deps. Direct payoff for the perf-slice
  // cluster (`stabilize derived collections in mintSelect`, `stabilise
  // relay-flush re-fire`, `scope useAiSend stream + balance to a hook
  // controller`, `perf(chat): stabilise chat-surface render lifecycle`).
  //
  // Set at `warn` initially — the rules are precise but historically
  // noisy in codebases that haven't been pass-optimised. Surfaces in PR
  // review without failing CI. Pairs with the react-compiler rule
  // above: react-compiler flags compiler bailouts, react-perf flags
  // the props that *would* prevent memoisation even with the compiler
  // active.
  //
  // `jsx-no-jsx-as-prop` (passing a `<Component />` as a prop) is also
  // available but commonly used in real patterns (slot props, list
  // renderers); skipped to keep noise low.
  {
    files: ['**/*.tsx'],
    plugins: { 'react-perf': require('eslint-plugin-react-perf') },
    rules: {
      'react-perf/jsx-no-new-object-as-prop': 'warn',
      'react-perf/jsx-no-new-array-as-prop': 'warn',
      'react-perf/jsx-no-new-function-as-prop': 'warn',
    },
  },
  // React Compiler ESLint rule. Flags components and effects that the
  // compiler can't auto-memoize: render-body mutations, prop mutations,
  // refs misuse, conditional hooks, derived collections that aren't
  // stable across renders, etc. Direct payoff for the perf-slice cluster
  // (`stabilize derived collections in mintSelect`, `narrow zustand
  // selectors and store subscriptions`, `stabilise relay-flush re-fire
  // in contact-discovery hooks`, `drop redundant React.memo wrappers`,
  // `stop stale derived state from polluting virtualised lists`, etc.).
  //
  // Set at `warn` initially — the rule is precise but the warning floor
  // is unknown and we want the perf signal in PR review before failing
  // CI on it. Promote to `error` once the warning floor is at zero (a
  // future audit-fix slice). Warnings don't appear in
  // `eslint-suppressions.json`; they show up in the lint output and
  // surface in editor integrations.
  ...(reactCompilerPlugin
    ? [
        {
          files: ['**/*.ts', '**/*.tsx'],
          plugins: { 'react-compiler': reactCompilerPlugin },
          rules: {
            'react-compiler/react-compiler': 'warn',
          },
        },
      ]
    : []),
  {
    plugins: {
      'unused-imports': require('eslint-plugin-unused-imports'),
    },
    settings: {
      'import/resolver': {
        typescript: {
          project: './tsconfig.json',
        },
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      },
    },
    rules: {
      'no-empty': 0,
      // Raw `console.*` calls bypass the scoped-logger registry, escape
      // log redaction (secret/PII scrubbing), don't get tagged with the
      // calling module/profile, and ship as production hot-path overhead.
      // Slices that kept hitting this: `inject logger at colada
      // seam, drop raw console`, `scope domain logs through the registered
      // child loggers`, `drop render-body log calls from screen
      // components`, `drop module-load side effects`. Use the scoped
      // logger from `@/shared/lib/logger` (or its child via
      // `logger.child({ scope: '...' })`) instead. No allow-list — `warn`
      // and `error` route through the logger too (it has level-aware
      // transports). Exempted in the logger's own transport-fallback site
      // and at the pre-logger bootstrap layer (app.config.js, polyfills.js).
      'no-console': 'error',
      // Raw `fetch(...)` bypasses the `fetchJson` wrapper in
      // `shared/lib/apiClient.ts`, which handles: AbortSignal threading,
      // default timeouts, query/URL redaction in logs, zod-validated
      // response envelopes, and consistent error mapping. Slices that
      // kept hitting this: `route raw fetches through fetchJson + abort +
      // zod`, `route fetchMintInfo through fetchJson`. Streaming
      // responses (Server-Sent Events / `stream: true`) genuinely need
      // raw fetch — exempt those at the call site with an inline disable
      // and a one-line note explaining the stream consumer.
      'no-restricted-globals': [
        'error',
        {
          name: 'fetch',
          message:
            "Use `fetchJson` from '@/shared/lib/apiClient' (handles AbortSignal, timeout, URL redaction, zod-validated envelopes). Streaming responses are the one legitimate exception — keep raw `fetch` but disable this rule inline with a one-line note.",
        },
      ],
      // Defensive — same wrapper requirement when fetch is accessed via
      // window/global/globalThis (e.g. for type-narrowing or to avoid
      // identifier shadowing). No current call sites, but blocks the
      // bypass.
      'no-restricted-properties': [
        'error',
        {
          object: 'window',
          property: 'fetch',
          message:
            "Use `fetchJson` from '@/shared/lib/apiClient' instead of reaching for `window.fetch`.",
        },
        {
          object: 'globalThis',
          property: 'fetch',
          message:
            "Use `fetchJson` from '@/shared/lib/apiClient' instead of reaching for `globalThis.fetch`.",
        },
        {
          object: 'global',
          property: 'fetch',
          message:
            "Use `fetchJson` from '@/shared/lib/apiClient' instead of reaching for `global.fetch`.",
        },
      ],
      // Remove unused imports
      'unused-imports/no-unused-imports': 'error',
      // Remove unused variables but allow prefix `_` to ignore
      'unused-imports/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
        },
      ],
      // Disable import/no-unresolved since TypeScript handles this
      'import/no-unresolved': 'off',
      // Force every tap surface through the shared `Pressable` at
      // `@/shared/ui/primitives/Pressable`, which routes `onPress`
      // through `useSingleFlight`. Importing the raw RN names —
      // including the legacy `TouchableOpacity`, which the codebase no
      // longer wraps — would silently bypass that guard.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'react-native',
              importNames: [
                'Pressable',
                'TouchableOpacity',
                'TouchableHighlight',
                'TouchableWithoutFeedback',
              ],
              message:
                "Import { Pressable } from '@/shared/ui/primitives/Pressable' instead. The shared primitive auto-guards onPress against rapid double-tap re-entry; importing the raw RN tap primitives bypasses that guard. `TouchableOpacity`'s opacity behaviour is preserved via Pressable's `activeOpacity` prop; `TouchableHighlight` / `TouchableWithoutFeedback` map to Pressable with `unstable_pressDelay` / a no-op highlight.",
            },
            // Legacy clipboard libraries. The canonical home for
            // clipboard reads/writes is `expo-clipboard`, which handles
            // both platforms uniformly and integrates with the secure-
            // copy permission flow. Slice: `redact bearer instruments +
            // geolocation from storage dump and swap legacy clipboard`.
            // Currently no call sites — pure regression guard against a
            // future install of the deprecated package.
            {
              name: '@react-native-community/clipboard',
              message:
                "Use `expo-clipboard` instead. The community package is deprecated and doesn't integrate with the project's secure-copy permission flow.",
            },
            {
              name: '@react-native-clipboard/clipboard',
              message:
                "Use `expo-clipboard` instead. The community package is deprecated and doesn't integrate with the project's secure-copy permission flow.",
            },
            // Legacy `Animated` runs on the JS thread (driver: false) or
            // the UI thread via a serialised native driver (driver: true)
            // — either way it can't worklet-link to gestures or shared
            // values, can't interpolate colours, and is significantly
            // slower than Reanimated v4. Slice:
            // `refactor(animation): migrate three feature screens from
            // legacy RN Animated to Reanimated v4`. Use the
            // `react-native-reanimated` API (`useSharedValue`,
            // `useAnimatedStyle`, `withTiming`, `withSpring`, etc).
            //
            // `Easing` from `react-native` is also blocked because it
            // pairs with Animated; Reanimated ships its own `Easing` at
            // `react-native-reanimated`.
            {
              name: 'react-native',
              importNames: ['Animated', 'Easing'],
              message:
                "Use `react-native-reanimated` (Reanimated v4): `useSharedValue`, `useAnimatedStyle`, `withTiming`, `withSpring`, `Easing`. Legacy `Animated` from 'react-native' runs JS-thread (or via a serialised native driver) — it can't worklet-link to gestures, can't interpolate colours, and is materially slower than Reanimated.",
            },
          ],
        },
      ],
      // `Dimensions.get('window' | 'screen')` snapshots the viewport once and
      // never updates on rotation, foldable resize, or split-screen — UI that
      // depends on it goes stale. Use `useWindowDimensions()` from react-native
      // inside components, which subscribes via change events. Pure helpers
      // should accept a `windowWidth: number` parameter from the caller's hook.
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.object.name='Dimensions'][callee.property.name='get']",
          message:
            "Use `useWindowDimensions()` from 'react-native' inside components, or accept a `windowWidth` parameter in helpers. `Dimensions.get(...)` snapshots the viewport once and won't react to rotation, foldables, or split-screen.",
        },
        // Hardcoded hex colors drift away from the theme system and survive
        // theme flips (light/dark/custom palettes). Slices that kept hitting
        // this: `kill module-scope and hardcoded colors that survive theme
        // flips`, `consolidate raw '#F7931A' into BITCOIN_ACCENT token`,
        // `drop hardcoded #3B82F6 in theme picker`, `replace hardcoded
        // brand hexes with theme tokens`. Match `#RGB`, `#RGBA`, `#RRGGBB`,
        // `#RRGGBBAA`. Exempted in the canonical color homes via the
        // override block below.
        {
          selector: 'Literal[value=/^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/]',
          message:
            "Hardcoded hex colors bypass the theme system. For theme-aware values use `useThemeColor` from '@/shared/hooks/useThemeColor'; for cross-theme brand constants (Bitcoin orange, BLE blue, connected green) import from '@/shared/lib/brandColors' (BITCOIN_ACCENT / BLUETOOTH_ACCENT / CONNECTED_ACCENT). If you need a new cross-theme constant, add a named export to `shared/lib/brandColors.ts` rather than inlining the hex.",
        },
        // `Linking.openURL(raw)` from `react-native` accepts any string —
        // `javascript:`, `file:`, `intent:`, custom schemes — and opens
        // whatever the OS resolves it to. When `raw` comes from
        // untrusted input (BTCMap merchant fields, mint-operator contact
        // metadata, Nostr relay note content, etc.) this is a privilege-
        // escalation surface. Slice: `fix(security): scheme-validate
        // untrusted Linking.openURL inputs`. Use `openExternalUrl(raw)`
        // from `@/shared/lib/url`, which enforces an http/https/mailto/tel
        // allowlist and returns a `ResultAsync` so failures (denied
        // scheme, malformed URL, OS rejection) surface instead of being
        // silently swallowed.
        {
          selector: "CallExpression[callee.object.name='Linking'][callee.property.name='openURL']",
          message:
            "Use `openExternalUrl(raw)` from '@/shared/lib/url'. It enforces an http/https/mailto/tel scheme allowlist and returns a `ResultAsync` so rejection paths surface. Raw `Linking.openURL` opens any scheme the OS recognises — `javascript:`, `file:`, `intent:` — which is a privilege-escalation surface for untrusted input.",
        },
        // `borderWidth: 0.5` (and the directional variants) rounds DOWN
        // to 0 on DPR=1 devices — the border vanishes. Documented in
        // `../.agents/skills/sovran-ui-patterns/references/responsive-scaling.md`.
        // Use `StyleSheet.hairlineWidth`
        // (== `1 / PixelRatio.get()`, guaranteed to render as exactly
        // one physical pixel on every density). 1pt is also fine if the
        // design wants something visibly thicker than a hairline.
        {
          selector:
            "Property[key.name=/^border(Top|Bottom|Left|Right|Start|End)?Width$/][value.type='Literal'][value.value=0.5]",
          message:
            '`borderWidth: 0.5` rounds to 0 on DPR=1 devices and the border disappears. Use `StyleSheet.hairlineWidth` (1 physical pixel on every density) or a literal `1`. See ../.agents/skills/sovran-ui-patterns/references/responsive-scaling.md.',
        },
        // `Date#toLocaleDateString` / `Date#toLocaleTimeString` bypass the
        // canonical date pipeline in `shared/lib/date.ts` (rule:
        // `../.agents/skills/sovran-data-runtime/references/dates.md`). The shared
        // `formatDate(input, style)` and
        // `formatRelative(input, style)` resolve locale automatically
        // (in-app language override → device locale → `'en'`) and lock the
        // style names so screens stay consistent. Bare `.toLocale*String`
        // bakes in the system locale per call, drifts on style, and
        // ignores the user's in-app language override. Number formatting
        // via `.toLocaleString()` is unaffected — only Date-specific
        // method names are matched.
        {
          selector: 'MemberExpression[property.name=/^toLocale(Date|Time)String$/]',
          message:
            "Use `formatDate(input, style)` from '@/shared/lib/date' (or `formatRelative` for relative timestamps). The shared helpers resolve locale automatically and lock the style vocabulary. See ../.agents/skills/sovran-data-runtime/references/dates.md for the catalog of styles.",
        },
      ],
    },
    ignores: ['dist/*'],
  },
  // The shared Pressable IS the wrapper — it must import the raw RN
  // name. Allow only that one file to break the rule above.
  {
    files: ['shared/ui/primitives/Pressable.tsx'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
  // Two known callers legitimately need a frozen snapshot rather than a
  // rotation-reactive value. If either surface moves to live layout
  // measurement, drop the matching exemption.
  //   - app/_layout.tsx: splash overlay measurements are taken once at app
  //     launch (before any rotation could matter) and used to morph into a
  //     QR-button anchor. Subscribing to dimension changes here would
  //     invalidate the morph-source rectangle mid-animation.
  //   - features/splitBill/components/ParticipantCardDeck.tsx: STEP /
  //     CARD_W / SIDE_PAD feed `useAnimatedStyle` worklets and the carousel
  //     snap math; converting these to reactive values needs the worklet
  //     deps to thread through the SharedValue path, out of scope here.
  {
    files: ['app/_layout.tsx', 'features/splitBill/components/ParticipantCardDeck.tsx'],
    rules: {
      'no-restricted-syntax': 'off',
    },
  },
  // The fetch-wrapper file IS the legitimate caller of raw `fetch`.
  // shared/lib/apiClient.ts hosts the canonical `fetchJson` used by
  // the rest of the app.
  {
    files: ['shared/lib/apiClient.ts'],
    rules: {
      'no-restricted-globals': 'off',
    },
  },
  // `no-console` exemptions — three legitimate sites:
  //   - shared/lib/loggerCore.ts: transport-fallback escape hatch. When
  //     the logger's own transport throws, it falls through to
  //     `console.error` rather than swallow the failure (F-017).
  //   - app.config.js: build-time Expo config script, runs in Node before
  //     the app starts.
  //   - polyfills.js: runtime bootstrap that loads BEFORE the logger
  //     module exists; can't route through a logger that hasn't been
  //     initialised yet.
  {
    files: ['shared/lib/loggerCore.ts', 'app.config.js', 'polyfills.js'],
    rules: {
      'no-console': 'off',
    },
  },
  // `openExternalUrl` lives in shared/lib/url.ts — the wrapper IS the
  // legitimate caller of raw `Linking.openURL`. It does the scheme-
  // allowlist check first, then forwards. Only that one file is allowed
  // to break the rule above.
  {
    files: ['shared/lib/url.ts'],
    rules: {
      'no-restricted-syntax': 'off',
    },
  },
  // Canonical hex-color homes — these files ARE the theme/brand-token
  // source of truth, so hex literals here are the answer, not the
  // problem. Disabling `no-restricted-syntax` wholesale (vs. selector-
  // by-selector) is acceptable because none of these files touch
  // `Dimensions.get(...)` either.
  //   - themes.ts: the theme palette table.
  //   - shared/lib/themeEngine.ts: palette generation / OKLCH math.
  //   - shared/lib/brandColors.ts: cross-theme brand constants
  //     (BITCOIN_ACCENT etc).
  //   - shared/lib/colorExtraction.ts: image-to-palette color math.
  //   - config/backgroundImageThemes.ts: art-directed gradient stops.
  {
    files: [
      'themes.ts',
      'shared/lib/themeEngine.ts',
      'shared/lib/brandColors.ts',
      'shared/lib/colorExtraction.ts',
      'config/backgroundImageThemes.ts',
    ],
    rules: {
      'no-restricted-syntax': 'off',
    },
  },
]);
