const path = require('path');
const { getDefaultConfig } = require('expo/metro-config');
const { withUniwindConfig } = require('uniwind/metro');

const config = getDefaultConfig(__dirname);

// `@sovranbitcoin/schemas` lives as a sibling repo and is wired in via
// `file:../sovran-schemas`. Metro needs the linked target in `watchFolders`
// so transform/resolve can walk its source files; otherwise the `node_modules`
// symlink resolves but the target falls outside Metro's project roots.
// `extraNodeModules` pins the schemas package's peer-deps (zod, neverthrow)
// to the app's own copies so we don't ship two realms of ZodObject.
const sovranSchemasPath = path.resolve(__dirname, '..', 'sovran-schemas');
const appNodeModules = path.resolve(__dirname, 'node_modules');
config.watchFolders = [...(config.watchFolders ?? []), sovranSchemasPath];
config.resolver = {
  ...config.resolver,
  unstable_enableSymlinks: true,
  nodeModulesPaths: [...(config.resolver?.nodeModulesPaths ?? []), appNodeModules],
  extraNodeModules: {
    ...(config.resolver?.extraNodeModules ?? {}),
    zod: path.resolve(appNodeModules, 'zod'),
    neverthrow: path.resolve(appNodeModules, 'neverthrow'),
  },
};

// Enable source maps for better debugging
config.transformer = {
  ...config.transformer,
  minifierConfig: {
    keep_classnames: true,
    keep_fnames: true,
    mangle: {
      keep_classnames: true,
      keep_fnames: true,
    },
  },
};

// First apply Uniwind
const uniwindConfig = withUniwindConfig(config, { cssEntryFile: './global.css' });

// Resolve @monicon/runtime to the pre-generated icons file.
// The .monicon/icons.js file is generated by running the dev server locally
// (which triggers @monicon/core's loadIcons) and committed to the repo.
// This replaces @monicon/metro's withMonicon() which is incompatible with
// the installed version mix and Expo 55's resolver chain.
const moniconIconsPath = path.resolve(__dirname, '.monicon', 'icons.js');
const liquidGlassEntryPath = path.resolve(
  __dirname,
  'node_modules',
  'expo-liquid-glass-native',
  'build',
  'index.js'
);
const herouiNativeEntryPath = path.resolve(
  __dirname,
  'node_modules',
  'heroui-native',
  'lib',
  'module',
  'index.js'
);
const herouiNativeProviderPath = path.resolve(
  __dirname,
  'node_modules',
  'heroui-native',
  'lib',
  'module',
  'providers',
  'hero-ui-native',
  'index.js'
);

// Save Uniwind's resolver before adding ours — Uniwind intercepts CSS
// imports and swaps them for platform-specific JS. Overwriting it causes a
// black screen because styles never load.
const uniwindResolver = uniwindConfig.resolver?.resolveRequest;

uniwindConfig.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName === '@monicon/runtime') {
    return {
      type: 'sourceFile',
      filePath: moniconIconsPath,
    };
  }
  if (moduleName === 'expo-liquid-glass-native') {
    return {
      type: 'sourceFile',
      filePath: liquidGlassEntryPath,
    };
  }
  if (moduleName === 'heroui-native') {
    return {
      type: 'sourceFile',
      filePath: herouiNativeEntryPath,
    };
  }
  if (moduleName === 'heroui-native/provider') {
    return {
      type: 'sourceFile',
      filePath: herouiNativeProviderPath,
    };
  }
  // Chain to Uniwind's resolver to preserve CSS interop styling
  if (uniwindResolver) {
    return uniwindResolver(context, moduleName, platform);
  }
  return context.resolveRequest(context, moduleName, platform);
};

module.exports = uniwindConfig;
