const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');
const { withMonicon } = require('@monicon/metro');

const config = getDefaultConfig(__dirname);

// Enable source maps for better debugging
config.transformer = {
  ...config.transformer,
  minifierConfig: {
    keep_classnames: true,
    keep_fnames: true,
    mangle: {
      keep_classnames: true,
      keep_fnames: true,
    },
  },
};

// First apply NativeWind
const nativeWindConfig = withNativeWind(config, { input: './global.css' });

// Then apply Monicon
module.exports = withMonicon(nativeWindConfig, {
  collections: ['circle-flags'],
  icons: [
    // Your existing icons array...
    'mdi:refresh',
    'fluent:apps-16-filled',
    'ri:openai-fill', // Using robot as OpenAI icon
    'ri:anthropic-fill',
    'ri:google-fill',
    'ri:meta-fill',
    'simple-icons:mistralai',
    'ri:perplexity-line',
    'bi:nvidia',
    'hugeicons:qwen',
    'ri:deepseek-fill',
    'ant-design:alibaba-outlined',
    'ri:twitter-x-fill',
    'material-symbols:account-balance-wallet',
    'solar:tag-price-bold',
    'ri:amazon-fill',
    'cib:ibm',
    'simple-icons:microsoft',
    'simple-icons:baidu',
    'simple-icons:tencentqq',
    'simple-icons:tiktok',
    'mdi:brain',
    'mdi:help-circle',
    'mdi:check-circle',
    'mdi-light:check',
    'lucide:arrow-down-left',
    'fluent:filter-16-filled',
    'lucide:activity',
    'fa6-solid:chevron-left',
    'fa6-solid:chevron-right',
    'fluent:chevron-down-12-filled',
    'lucide:arrow-right',
    'lucide:arrow-up-right',
    'fluent:add-24-filled',
    'fluent:arrow-upload-16-filled',
    'fluent:arrow-download-16-filled',
    'fluent:arrow-swap-16-filled',
    'iconamoon:send-fill',
    'ri:share-fill',
    'lets-icons:copy',
    'lucide:pencil-line',
    'lucide:delete',
    'simple-line-icons:check',
    'material-symbols:check-rounded',
    'lucide:nfc',
    'lucide:clipboard-paste',
    'lucide:link',
    'fluent:checkmark-16-filled',
    'fluent:checkmark-circle-16-filled',
    'fluent:list-16-filled',
    'fluent:clock-16-filled',
    'fluent:dismiss-circle-16-filled',
    'ion:checkmark-done',
    'material-symbols:close-rounded',
    'simple-line-icons:close',
    'nonicons:error-16',
    'mdi:cancel',
    'ph:user-bold',
    'fa6-solid:user',
    'la:user-plus',
    'la:user-minus',
    'la:user-slash',
    'mdi:contact',
    'ant-design:loading-outlined',
    'humbleicons:refresh',
    'ic:round-refresh',
    'majesticons:eye',
    'majesticons:eye-off',
    'material-symbols:currency-bitcoin',
    'material-symbols-light:currency-bitcoin',
    'fluent:wallet-20-filled',
    'majesticons:coins',
    'solar:card-bold',
    'material-symbols:arrow-back-rounded',
    'material-symbols:close-rounded',
    'material-symbols:verified-rounded',
    'material-symbols:verified',
    'ph:contactless-payment-fill',
    'majesticons:percent',
    'majesticons:text',
    'mdi:decimal',
    'fluent:emoji-24-filled',
    'mdi:lightbulb-on-outline',
    'mdi:lightbulb-on',
    'proicons:photo',
    'majesticons:search-line',
    'solar:key-bold',
    'garden:arrow-retweet-fill-16',
    'garden:speech-bubble-typing-fill-12',
    'garden:heart-fill-16',
    'hugeicons:new-twitter',
    'mdi:at',
    'mingcute:lightning-fill',
    'material-symbols:info-rounded',
    'material-symbols:report-rounded',
    'material-symbols:settings-rounded',
    'mdi:robot',
    'mdi:help-circle',
    'feather:wifi',
    'clarity:internet-of-things-solid',
    'bx:dots-vertical-rounded',
    'tabler:dots',
    'fluent:clock-12-filled',
    'stash:qr-code',
    'ic:round-star',
    'humbleicons:url',
    'lucide:activity',
    'lucide:square-pen',
    'mdi:menu',
    'mdi:anonymous-off',
    'mdi:anonymous',
    'ph:coins',

    // Explore page icons
    'mdi:chevron-right',
    'mdi:map-marker',
    'mdi:sim',
    'mdi:calendar',
    'mdi:account-group',
    'mdi:arrow-right',
    'mdi:gamepad-variant',
    'mdi:food',
    'mdi:airplane',
    'mdi:shopping',
    'mdi:movie-open',

    // Map page icons
    'mdi:bitcoin',
    'mdi:crosshairs-gps',
    'mdi:phone',
    'mdi:web',
    'mdi:email',
    'mdi:instagram',
    'mdi:close-circle',
    'mdi:coffee',
    'mdi:silverware-fork-knife',
    'mdi:cart',
    'mdi:store',
    'mdi:cash-multiple',
    'mdi:bed',
    'mdi:pill',
    'mdi:laptop',
    'mdi:camera',
    'mdi:hospital-box',
    'mdi:bread-slice',
    'mdi:spa',
    'mdi:office-building',
    'mdi:grass',
    'mdi:dumbbell',
    'mdi:chair-rolling',
    'mdi:hammer-wrench',
    'mdi:music',
    'mdi:tree',
    'mdi:car',
    'mdi:currency-usd',
    'mdi:content-cut',
    'mdi:palette',
    'mdi:car-wrench',
    'mdi:diamond',
    'mdi:alert-circle',
    'mdi:chevron-down',
    'mdi:minus',
    'mdi:plus',

    // Keyring page icons
    'mdi:key-plus',
    'mdi:key-arrow-right',
    'mdi:trash-can-outline',
    'mdi:chevron-up',
    'mdi:key-variant',

    // Lightning Address card icons
    'mdi:arrow-down',
    'mdi:share-variant',
    'mdi:qrcode',
    'mdi:account-check',

    // Claim username modal icons
    'mdi:check',

    // User profile icons
    'mdi:check-decagram',
    'mdi:message-text',
    'mdi:lightning-bolt',
    'mdi:open-in-new',
    'mdi:bank',

    // Pending Ecash icons
    'mdi:clock-outline',
    'mdi:clock-alert-outline',
    'mdi:broom',
    'mdi:check-circle-outline',
    'fluent:wallet-24-filled',

    // Distribution/Balance split icons
    'fluent:split-vertical-24-filled',
    'mdi:arrow-collapse-up',
    'mdi:arrow-collapse-down',

    // Rebalance plan icons
    'mdi:skip-next',
    'mdi:skip-next-circle',
    'mdi:swap-horizontal',
  ],
});
