// Plain build-time copy. No app, wallet, schema, environment or React imports.
export const siteCopy = {
  title: 'Sovran - Sound money meets freedom of expression',
  description: 'A Bitcoin app for payments, conversations, and a more open social world. Understand the risks, choose your mint, and start small.',
  hero: { title: 'Sound money meets freedom of expression.', text: 'Payments, conversations, and open networks in one app.', action: 'Download' },
  manifesto: { text: 'Two persons may exchange messages, conduct business, and negotiate electronic contracts without ever knowing the True Name, or legal identity, of the other.', cite: 'Timothy C. May, The Crypto Anarchist Manifesto (1988)', href: 'https://www.activism.net/cypherpunk/crypto-anarchy.html' },
  statement: { problem: 'Platforms trap money, identity, messages, and reputation behind walled gardens.', solution: 'Sovran brings payments and conversations together on open protocols. You choose who to connect with and which services to trust.' },
  benefits: [
    { id: 'wallet', eyebrow: 'Pay', title: 'Pay a friend.\nPick your mint.', text: 'Pay a Lightning address, scan a code, or send Cashu ecash. Your phone holds the digital cash; the issuing mint holds the bitcoin behind it and is responsible for redemption.', points: ['Send and receive Cashu ecash', 'Pay supported Lightning invoices and addresses', 'Choose and manage your mints'], note: 'You are not holding bitcoin directly on-chain. Fees and availability depend on the mint and payment route.' },
    { id: 'social', eyebrow: 'Social', title: 'Nostr, without\nthe noise.', text: 'Read, post, and connect with people on Nostr. Explore ranked feeds, grouped notifications, and conversations beyond a single closed platform.', points: ['Find people and posts', 'Follow conversations across the network', 'Message friends with supported encrypted DMs'], note: 'Public posts can be copied and retained by others. Relays can restrict access; encrypted messages do not hide every kind of metadata.' },
    { id: 'ai', eyebrow: 'Ask', title: 'Chat with AI,\npay as you go.', text: 'Pick a model and top up your Routstr balance with ecash from your wallet. Pay for usage rather than a recurring subscription.', points: ['Choose a supported model', 'Top up with Cashu ecash', 'Read answers as they stream in'], note: 'Prompts go to external providers under their own terms. Models can make mistakes; prices and availability vary.' },
    { id: 'offline', eyebrow: 'Nearby', title: 'Pass digital cash.\nEven offline.', text: 'Supported NFC and Bluetooth paths let you hand ecash to someone nearby without an internet connection at the moment of transfer.', points: ['Share tokens with people nearby', 'Use supported NFC and Bluetooth handoffs', 'Reconnect to check and redeem with the mint'], note: 'Handoff is not settlement. Redemption and spendability checks need the relevant mint. Support varies by device and installed version.' },
  ],
  stack: { title: 'The freedom stack,\nin one app.', text: 'Built on open protocols and projects, with source you can inspect. Different components have their own licenses, and hosted services remain part of the experience.', items: [
    { name: 'Bitcoin', role: 'Backing asset', logo: 'bitcoin' },
    { name: 'Cashu', role: 'Digital cash', logo: 'cashu' },
    { name: 'Nostr', role: 'Social network', logo: 'nostr' },
    { name: 'BitChat', role: 'Nearby communication', logo: '' },
    { name: 'BTC Map', role: 'Places to spend', logo: 'btcmap' },
    { name: 'Vertex', role: 'People discovery', logo: 'vertex' },
    { name: 'Coco', role: 'Wallet engine', logo: 'coco' },
    { name: 'npub.cash', role: 'Lightning addresses', logo: 'npubcash' },
    { name: 'Routstr', role: 'Pay-per-use AI', logo: '' },
    { name: 'Nagg', role: 'Feed indexing', logo: '' },
  ] },
  faq: [
    { question: 'What is Sovran?', answer: 'Sovran brings a Cashu ecash wallet, Lightning payments, Nostr feeds and messages, and pay-per-use AI into one app. Features vary by platform and installed version.' },
    { question: 'Do I hold my own money?', answer: 'Your phone holds your keys and digital cash. The issuing mint holds the backing bitcoin and must redeem your ecash, including when the mint is Sovran-branded. Community reviews, operator reputations, and payment-test results from auditors can help you compare mints. They do not prove reserves or guarantee future reliability. A mint can fail or restrict redemption. Start with small amounts you can afford to lose.' },
    { question: 'How do I back it up?', answer: 'Keep your recovery words safe and save the URLs of your mints. Sovran makes a best-effort search for mints and uses available records to recover ecash. It may not find everything: words alone do not guarantee recovery of every token, message, or pending payment. If you imported a Nostr identity, back up its private key separately; your recovery words cannot recreate it. Sovran cannot reset lost words.' },
    { question: 'Is my public identity connected to my money?', answer: 'For profiles you create in Sovran, your recovery words derive separate Nostr identity keys and Cashu wallet keys. Your Nostr key alone does not recreate your Cashu wallet. Keep it private, though: someone who gets it may read retained messages and spend unredeemed ecash tokens inside them. Payment addresses, public posts, timing, and network information can still link activity across separate keys.' },
    { question: 'Can I pay people without the internet?', answer: 'Supported NFC and Bluetooth paths can hand off ecash tokens offline. The recipient needs the relevant mint to check spendability and redeem them. An offline handoff is not proof of settlement, and support varies by device and version.' },
    { question: 'Is Sovran open source?', answer: 'The main Sovran app source is published under the Mozilla Public License 2.0 (MPL-2.0). You can read the code and its license on GitHub. Dependencies, artwork, and other components have their own licenses. This does not mean every hosted service is open source or every store build is reproducible.', links: [{ label: 'View the source', href: 'https://github.com/SovranBitcoin/Sovran' }, { label: 'Read the MPL-2.0 license', href: 'https://github.com/SovranBitcoin/Sovran/blob/main/LICENSE' }] },
    { question: 'Which phones can run it?', answer: 'See the iOS and Android download options below. Each store has its own release schedule, so versions and features may differ. The download section checks current availability before showing a link.', links: [{ label: 'See download options', href: '#download' }] },
  ],
  risk: 'Cashu ecash is experimental. Mints can fail, and funds can be lost. Use small amounts you can afford to lose. Back up your recovery information; recovery is not guaranteed.',
  downloads: {
    title: 'Be Sovran.',
    text: 'Each channel has its own release schedule. Links appear only after live release metadata has been checked.',
    loading: 'Checking live release availability...',
    failure: 'Release availability could not be verified. No download links are enabled. Try again shortly.',
    ready: 'Live release metadata checked. Versions below are specific to each channel.',
    unavailable: 'No confirmed release',
    retry: 'Check again',
  },
  releases: {
    title: 'Releases',
    text: 'What changed in Sovran, newest first.',
    note: 'Dates are when the notes were published on GitHub. Store versions and features may differ; check the download options for current availability.',
    href: 'https://github.com/SovranBitcoin/Sovran/releases',
    // Verified against the GitHub Releases API on 2026-09-14. Do not fill gaps
    // with package versions or treat current source as historical release notes.
    entries: [
      {
        version: '0.1.3',
        date: '2026-09-12',
        title: 'Android release on GitHub',
        text: 'An Android installation file was published on GitHub, with checksums and signing-certificate information. The published notes do not include a feature-by-feature changelog.',
        items: [],
        href: 'https://github.com/SovranBitcoin/Sovran/releases/tag/v0.1.3',
      },
      {
        version: '0.1.0',
        date: '2026-06-18',
        title: 'The first release',
        text: 'The first release brought a Cashu wallet and Nostr conversations together on iOS. These highlights summarize the original release notes.',
        items: [
          'Send and receive Cashu digital cash, or pay supported Lightning invoices and addresses through a mint.',
          'Read Nostr feeds and replies, find people, and send encrypted direct messages with payment actions in chat.',
          'Choose mints with help from community reviews and recorded payment checks, not proof of their reserves.',
          'Chat with supported AI models through Routstr, using a separate balance topped up with ecash.',
          'Find Bitcoin merchants on a map and personalize your wallet with colors and wallpapers.',
        ],
        href: 'https://github.com/SovranBitcoin/Sovran/releases/tag/v0.1.0',
      },
    ],
  },
  roadmap: {
    title: 'Roadmap',
    text: 'Where Sovran is heading: more dependable payments, clearer recovery, and better conversations.',
    note: 'These are the original roadmap statuses, not a list of released features or promised dates. Complete means marked complete in that work log, not confirmed availability in your installed or store version. In progress means unfinished work; planned means a goal. Priorities may change as we test and learn.',
    glossary: 'Cashu ecash is digital cash issued and redeemed by a mint, which holds the backing funds. Nostr is the network behind profiles, posts, and messages. Lightning and on-chain Bitcoin are different ways to move payments. Support depends on the mint, device, and version.',
    source: { label: 'Original roadmap source', href: 'https://github.com/SovranBitcoin/sovran.money/blob/ec88419/src/content/roadmap.ts' },
    statusLabels: { complete: 'Complete', 'in-progress': 'In progress', planned: 'Planned' },
    // One item per original bullet in sovran.money/src/content/roadmap.ts.
    // Group IDs retain source slugs; item IDs freeze their original 1-based
    // position, not their future display order. Coverage/provenance lives in
    // site/tests/roadmap-coverage.test.ts. Do not renumber or merge these IDs.
    groups: [
      { id: 'payments', title: 'Payments and sends', status: 'in-progress', text: 'Make sending and receiving dependable across currencies, recipients, and ways to pay.', items: [
        { id: 'payments-01', status: 'complete', text: 'Scan, paste, or tap a Bitcoin address, Lightning payment, Cashu token, or sovran:/cashu: app link to open the matching payment screen. Recognizing an input does not mean every payment type is ready to use.' },
        { id: 'payments-02', status: 'complete', text: 'Hold and read balances in sats (small units of bitcoin), dollars, pounds, and euros, with the currency clearly labelled in selectors and history.' },
        { id: 'payments-03', status: 'complete', text: "Send ecash over Nostr locked to the recipient's public key (npub). This P2PK lock requires the matching key to spend it, rather than letting anyone with a copied token spend it." },
        { id: 'payments-04', status: 'planned', text: 'Read every spending condition on a locked token and show when its locktime allows the sender to reclaim it. A generic lock badge should not hide the actual unlock or rollback conditions.' },
        { id: 'payments-05', status: 'complete', text: 'When a mint is unreachable, offer combinations of ecash proofs (the spendable records on your phone), with round-up and round-down choices. Stop an offline send cleanly if it cannot proceed. Handoff still needs a later mint check and redemption; it is not settlement.' },
        { id: 'payments-06', status: 'complete', text: 'Show the recipient name, avatar, and live Nostr profile before each payment, so you can check who it is for before money moves.' },
        { id: 'payments-07', status: 'in-progress', text: 'Keep payment memos attached through history and receipts. Lightning receives already carry a note; extend memo entry to ecash, on-chain, payment-request, nearby, and chat sends.' },
        { id: 'payments-08', status: 'planned', text: 'Put receive settings in one panel: toggle recipient-key locking (P2PK), enable reusable Lightning offers (BOLT-12), and edit your npub.cash username, rather than searching onboarding and separate settings.' },
        { id: 'payments-09', status: 'planned', text: 'Align the mint picker with the other actions on amount screens; it currently sits a few pixels too high.' },
        { id: 'payments-10', status: 'planned', text: 'Offer another mint for the same Lightning invoice if the selected mint cannot cover the amount or the payment fails. Let a mint that can pay finish the payment instead of ending at an error.' },
        { id: 'payments-11', status: 'planned', text: 'Try the other payment options in a scanned BIP-321 code before giving up. If its ecash, Lightning, or on-chain option fails, move to the next supported option, including after a failed NFC tap.' },
        { id: 'payments-12', status: 'planned', text: 'Let you change mints on the Pay confirmation screen. If the mint picker is dismissed, recover and ask again instead of silently ignoring the payment tap.' },
        { id: 'payments-13', status: 'planned', text: 'Add address hallmarks: visual stamps that help you compare the payment address in a scanned code with the address shown on your phone.' },
        { id: 'payments-14', status: 'planned', text: 'Read the minimum and maximum accepted by a Lightning address, such as odell@primal.net, and keep amount entry within those limits so payments do not fail for being too small or too large.' },
      ] },
      { id: 'payment-requests', title: 'Payment requests, both directions', status: 'in-progress', text: 'Support both paying a Cashu request and creating one to ask someone to pay you.', items: [
        { id: 'payment-requests-01', status: 'complete', text: 'Pay a Cashu payment request (NUT-18) from scan, paste, chat, or an app link, with a review step before sending. Route ecash from trusted mints to the recipient in a gift-wrapped encrypted Nostr direct message (NIP-17).' },
        { id: 'payment-requests-02', status: 'planned', text: 'Create your own payment requests: generate, cancel, recover, and deliver them over Nostr, so you can ask for money as well as pay a request.' },
      ] },
      { id: 'mints', title: 'Choosing and using mints', status: 'in-progress', text: 'Compare mint operators and reputation before trusting them, and make group payouts less repetitive. Reviews and audit data do not prove reserves or guarantee reliability.', items: [
        { id: 'mints-01', status: 'complete', text: 'Inspect a mint page with its operator, Nostr reviews, star rating, live audit data, and swap success rate. When redeeming ecash from a mint you do not hold, open that page in verify mode to accept or reject it in one step.' },
        { id: 'mints-02', status: 'planned', text: 'Rate a mint and write a short review inside Sovran. Publish it to Nostr so it contributes to the ratings and reviews other people can read.' },
        { id: 'mints-03', status: 'planned', text: 'Show live progress for each mint as it connects, resolves, and verifies, with success, retry, and failure states. Adding several mints should not leave you watching an unexplained spinner.' },
        { id: 'mints-04', status: 'planned', text: 'When you reject an unfamiliar mint while redeeming ecash, offer to redeem its proofs directly into a mint you trust (a melt) instead of abandoning the funds. Retry across destination mints, with already-failed choices disabled.' },
        { id: 'mints-05', status: 'planned', text: 'Batch Nut Drop group payouts and repeated minting into one action while keeping track of where every token went.' },
      ] },
      { id: 'wallet-recovery', title: 'Wallet and recovery', status: 'in-progress', text: 'Make backup, restore, and moving phones more dependable. Recovery still depends on mint support and available records; keep mint URLs and separate backups for imported private keys.', items: [
        { id: 'wallet-recovery-01', status: 'complete', text: 'Use one recovery phrase for the profiles and wallets created from it, with each profile deriving separate keys on its own path. This does not recreate imported private keys or guarantee recovery of every token or record.' },
        { id: 'wallet-recovery-02', status: 'complete', text: 'Run the wallet on the Coco engine for faster restores, live balances over websocket connections, and the groundwork for on-chain payments.' },
        { id: 'wallet-recovery-03', status: 'in-progress', text: 'Reshape setup, restore, and moving to a new phone to feel seedless, so recovering a wallet need not require handling a recovery phrase by hand.' },
        { id: 'wallet-recovery-04', status: 'planned', text: 'Restore profiles imported with an existing Nostr private key (nsec) after a reinstall, instead of requiring you to import each key again.' },
        { id: 'wallet-recovery-05', status: 'planned', text: 'When a restored wallet adds a mint, have Coco re-check it for funds that the first restore pass may have missed.' },
        { id: 'wallet-recovery-06', status: 'planned', text: 'Fix the timing race that can randomly crash the app when switching profiles more than once in a session, so changing accounts does not require a restart.' },
      ] },
      { id: 'wallet-engine', title: 'Wallet engine and reliability', status: 'in-progress', text: 'Keep balances and history trustworthy across currencies, interrupted payments, and restarts.', items: [
        { id: 'wallet-engine-01', status: 'complete', text: 'Treat sats, USD, EUR, and GBP as full units across balances, fees, and history. Rebuild each currency from the recovery phrase during restore, subject to mint support and recoverable records.' },
        { id: 'wallet-engine-02', status: 'complete', text: 'Track each invoice or offer as its own payment record (a quote). A pending Lightning top-up can settle when the mint issues ecash proofs and survive an app restart instead of disappearing.' },
        { id: 'wallet-engine-03', status: 'complete', text: "Read live history directly from Coco's wallet-core state. Each row links to the actual operation and can reopen its details, including the original token." },
        { id: 'wallet-engine-04', status: 'in-progress', text: 'Keep mint and balance state current with websocket watchers while the app is open. Pause those connections cleanly in the background to avoid unnecessary battery use.' },
        { id: 'wallet-engine-05', status: 'in-progress', text: 'Improve proof-state recovery: checking ecash, sweeping recoverable funds, and rolling back operations. Reduce stuck funds and invalid tokens while keeping balance calculations exact for each currency.' },
        { id: 'wallet-engine-06', status: 'planned', text: 'Distinguish an unreachable mint from an offline phone. If your phone is online but the mint is down, name the mint as the cause and fall back to usable local ecash proofs. Extend that fallback to any send error with usable local proofs, not just selected errors.' },
        { id: 'wallet-engine-07', status: 'planned', text: 'For dollars, pounds, and euros, choose the ecash combination with the lowest fees within the rounding window. If an affordable amount rounds to the same fiat value, send that amount without an extra prompt.' },
      ] },
      { id: 'onchain-lightning', title: 'On-chain Bitcoin and Lightning', status: 'in-progress', text: 'Finish on-chain payments through the wallet engine, with fee control, and add reusable ways to receive payments.', items: [
        { id: 'onchain-lightning-01', status: 'in-progress', text: 'Finish on-chain receive and send with BIP-321 address handling, clear amounts, selectable fees, and plain-language warnings. Routes, screens, and parsing exist, but receive cannot yet issue ecash from a deposit and send is not supported yet; both depend on Coco engine work.' },
        { id: 'onchain-lightning-02', status: 'planned', text: 'Handle on-chain-to-on-chain transfers on the same mint as a special case, aiming for immediate receive and send confirmation without breaking the timeline or history on this faster path.' },
        { id: 'onchain-lightning-03', status: 'in-progress', text: 'Replace one-use deposit addresses with reusable on-chain minting in Coco: fund the same address repeatedly, track its balance, claim deposits automatically, and allow partial withdrawals.' },
        { id: 'onchain-lightning-04', status: 'in-progress', text: "Connect Coco's on-chain withdrawal (melt) operation to send and history screens, with selectable fee rates, live settlement progress, and clear failure states when a chain payment stalls." },
        { id: 'onchain-lightning-05', status: 'planned', text: 'Add reusable Lightning offers (BOLT-12) for sending and receiving. One static code could accept repeated payments once the engine and release pipeline can support another payment type.' },
        { id: 'onchain-lightning-06', status: 'planned', text: 'Add Payjoin to on-chain sends once everyday payments are reliable enough to introduce it clearly. These collaborative transactions aim to save fees and make common chain-analysis methods less effective.' },
      ] },
      { id: 'social-feed', title: 'Reading and replying on Nostr', status: 'in-progress', text: 'Improve the feed and its supporting services, then make it easier to join conversations.', items: [
        { id: 'social-feed-01', status: 'in-progress', text: 'The home feed ranks notes by relevance rather than only recency, opens full reply chains, and shows reposts, zaps (tips), and post metrics alongside unified search and grouped notifications. Improve ranking, threading, and notification quality.' },
        { id: 'social-feed-02', status: 'planned', text: 'Add a reply composer in the thread view, keeping each reply nested under its parent instead of detaching it into the wider feed.' },
        { id: 'social-feed-03', status: 'planned', text: 'Let a connected X account mirror an update from Sovran, starting with an opt-in share path and expanding to managed posting later.' },
        { id: 'social-feed-04', status: 'planned', text: 'Teach Nagg, the feed backend, to extract image and video dimensions, aspect ratios, and safe layout metadata. Clients can reserve space before media loads and filter or downrank extreme aspect ratios.' },
        { id: 'social-feed-05', status: 'planned', text: "Have Nagg fetch and cache a link's Open Graph preview image and include it in the feed response, so each client does not need to fetch that metadata separately." },
      ] },
      { id: 'notifications', title: 'More useful notifications', status: 'in-progress', text: 'Help the inbox recognize people you engage with and bring app and mint news into the same place.', items: [
        { id: 'notifications-01', status: 'in-progress', text: 'Keep the manual Relaxed, Moderate, Strict, and Follows policies and Direct/Thread reply scope. Add adaptive ranking: opening or replying to someone raises their future prominence, while people you never answer become less prominent without needing to block them.' },
        { id: 'notifications-02', status: 'in-progress', text: 'Grow the Notifications App tab from its static welcome card into a real feed of release notes and live mint status, so product news and mint health share an inbox.' },
      ] },
      { id: 'messaging', title: 'Messaging and private groups', status: 'in-progress', text: 'Bring payments into conversations and extend encrypted messaging beyond one-to-one chats.', items: [
        { id: 'messaging-01', status: 'complete', text: 'Pay from the chat composer to a contact who publishes a Lightning address, without leaving the thread. Ecash appears as an inline card that the recipient can tap to redeem.' },
        { id: 'messaging-02', status: 'in-progress', text: 'Extend encrypted messaging to private multi-member groups. An opt-in MLS-encrypted transport over Marmot exists for two-party conversations; multi-member group chats are the remaining work.' },
      ] },
      { id: 'identity', title: 'An identity people can pay by name', status: 'in-progress', text: 'Connect Nostr profiles, Lightning addresses, and the communities people belong to.', items: [
        { id: 'identity-01', status: 'complete', text: 'Give each profile an npub.cash Lightning address tied to its Nostr key, with one-tap copy on the receive screen and free names to claim, so receiving can start with sharing a username.' },
        { id: 'identity-02', status: 'planned', text: 'Add the npub.cash address to the Lightning address field (LUD) on the Nostr profile, so zaps can resolve from the profile itself, not only the receive screen.' },
        { id: 'identity-03', status: 'planned', text: "Use npub.cash to identify who sent an incoming Lightning address payment. Show the sender's Nostr name and avatar in history when available, instead of a generic mint receive." },
        { id: 'identity-04', status: 'planned', text: 'Tag a profile with a group, event, or community, such as a meetup or cohort. People sharing the tag would share a feed and appear as suggested follows.' },
      ] },
      { id: 'history-insights', title: 'History that explains itself', status: 'in-progress', text: 'Explain individual payments and make spending across months easier to follow.', items: [
        { id: 'history-insights-01', status: 'complete', text: 'Show a live payment timeline with the source (QR, NFC, clipboard, or deep link), how money moved, and how it settled. Group by date with month tabs that stay pinned while paging back. The source marks this item complete but still calls for richer recipient and originating-request context on each row.' },
        { id: 'history-insights-02', status: 'in-progress', text: 'Extend the wallet chart of current-month spending and receipts, including its projected trend line, to past months with running totals and optional breakdowns by mint or currency.' },
      ] },
      { id: 'ai', title: 'AI paid with ecash, under your control', status: 'in-progress', text: 'Connect AI spending to the wallet and offer writing help only when requested, with you confirming every send.', items: [
        { id: 'ai-01', status: 'in-progress', text: 'Let AI use your wallet balance rather than a separate Routstr balance. The AI tab streams OpenAI, Claude, and Grok responses paid with ecash, but its standalone Routstr balance needs a token top-up; combining the balances is the remaining work.' },
        { id: 'ai-02', status: 'planned', text: 'Offer opt-in AI-drafted replies to help you write, with you confirming every send. A model should not send a reply or move money on its own.' },
      ] },
      { id: 'open-stack', title: 'Code others can build on', status: 'in-progress', text: 'Keep source public and make the Nostr tools, payment engine, and translation workflow easier to understand and reuse.', items: [
        { id: 'open-stack-01', status: 'complete', text: 'Keep the app and its supporting libraries public on GitHub for reading, auditing, and reuse under their respective licenses. Public source is not proof that every hosted service or store build is reproducible.' },
        { id: 'open-stack-02', status: 'in-progress', text: 'Package the search, notification, and feed recipes behind Sovran into nagg-ts, a Nostr client that other apps can use without adopting a particular user interface.' },
        { id: 'open-stack-03', status: 'in-progress', text: 'Document how Colada parses, routes, and sequences payments over Coco, covering ecash and Lightning first and on-chain next, so other wallets can reuse the payment flow.' },
        { id: 'open-stack-04', status: 'planned', text: 'Translate into Spanish first, then establish a repeatable translation workflow and regular public progress notes so more people can read and follow the project.' },
      ] },
      { id: 'releases-quality', title: 'Releases and quality', status: 'in-progress', text: 'Make releases repeatable, broaden device testing, and reduce download size.', items: [
        { id: 'releases-quality-01', status: 'in-progress', text: 'Combine build, submit, and AltStore sideload scripts into one release command, keeping App Store, sideloadable iOS, and Android APK packages in sync. This goal does not confirm store availability.' },
        { id: 'releases-quality-02', status: 'in-progress', text: 'Expand the Maestro send, receive, and onboarding test suites across more iPhones, Android builds, operating-system versions, and NFC tap-to-pay paths, rather than relying on manual checks on a few devices.' },
        { id: 'releases-quality-03', status: 'planned', text: 'Reduce the bundle from the original roadmap baseline of 94 MB on TestFlight, making installs, updates, and cold starts lighter.' },
      ] },
    ],
    recurring: {
      title: 'Recurring work',
      text: 'Maintenance continues across releases rather than becoming a completed one-time goal.',
      items: [
        { id: 'interface-stability-loading-polish', title: 'Smooth loading, no jumps', cadence: 'Every release', text: 'Keep screens steady as data loads: reduce content jumps, improve empty and error states, and use placeholders so content does not pop around while loading.' },
      ],
    },
  },
} as const;
