import type { PaymentCopyCatalog } from "./types";

export const paymentCopyDefaults = {
  "nfc.unitSwitchFailed": "Could not select the terminal’s currency. Try again.",
  "nfc.unitNotFunded": "This terminal wants {unit}. You have no {unit} ecash at an accepted mint.",
  "timeline.mint.unpaid.label": "Waiting for payment",
  "timeline.mint.unpaid.info": "Pay the invoice to receive funds",
  "timeline.mint.unpaid.onchainInfo": "Pay the address to receive funds",
  "timeline.mint.paid.label": "Payment received",
  "timeline.mint.paid.info": "Adding to wallet...",
  "timeline.mint.issued.label": "Complete",
  "timeline.mint.issued.info": "+{amount} sats added to wallet",
  "timeline.mint.expired.label": "Invoice expired",
  "timeline.mint.expired.info": "No payment was seen before it ran out",
  "timeline.mint.failed.label": "Failed",
  "timeline.mint.failed.info": "Receive could not be completed",

  "timeline.melt.unpaid.label": "Ready to send",
  "timeline.melt.unpaid.info": "Tap Send to complete payment",
  "timeline.melt.pending.label": "Paying",
  "timeline.melt.pending.info": "The mint is sending the payment",
  "timeline.melt.paid.label": "Paid",
  "timeline.melt.paid.info": "Payment complete",
  "timeline.melt.expired.label": "Quote expired",
  "timeline.melt.expired.info": "It ran out before the payment was sent",
  "timeline.melt.rolledBack.label": "Cancelled",
  "timeline.melt.rolledBack.info": "Funds returned to your balance",
  "timeline.melt.onchain.sending.label": "Sending to mint",
  "timeline.melt.onchain.sending.info": "Submitting payment…",
  "timeline.melt.onchain.sent.label": "Sent",
  "timeline.melt.onchain.broadcasting.label": "Broadcasting",
  "timeline.melt.onchain.broadcasting.info": "Sending the transaction to the network",
  "timeline.melt.onchain.mempool.label": "In mempool",
  "timeline.melt.onchain.blocks": "{current}/{required} blocks",
  "timeline.melt.onchain.confirmed.label": "Confirmed",
  "timeline.melt.onchain.offchain.label": "Settled off-chain",
  "timeline.melt.onchain.offchain.info": "The mint reported no on-chain transaction",

  "timeline.send.prepared.label": "Created",
  "timeline.send.prepared.info": "Ready to share",
  "timeline.send.pending.label": "Waiting for recipient",
  "timeline.send.pending.info": "Not claimed yet",
  "timeline.send.finalized.label": "Claimed",
  "timeline.send.finalized.info": "The token has been redeemed",
  "timeline.send.locked.label": "Locked",
  "timeline.send.locked.info": "Only the recipient can redeem it",
  "timeline.send.unlock.label": "Reclaimable",
  "timeline.send.unlock.reachedLabel": "Unlocked",
  "timeline.send.rolledBack.reclaimedLabel": "Reclaimed",
  "timeline.send.unlock.infoUpcoming": "Unlocks",
  "timeline.send.unlock.infoRefund": "You can take this back",
  "timeline.send.unlock.infoPublic": "Anyone with the token can redeem it",
  "timeline.send.rolledBack.label": "Cancelled",
  "timeline.send.rolledBack.info": "Funds returned to your balance",

  "timeline.paymentRequest.prepared.label": "Created",
  "timeline.paymentRequest.prepared.info": "Creating token...",
  "timeline.paymentRequest.nostrSent.label": "Delivered",
  "timeline.paymentRequest.nostrSent.infoSending": "Sending...",
  "timeline.paymentRequest.nostrSent.infoSent": "Sent to the recipient",
  "timeline.paymentRequest.finalized.label": "Claimed",
  "timeline.paymentRequest.finalized.info": "The token has been redeemed",
  "timeline.paymentRequest.rolledBack.label": "Cancelled",
  "timeline.paymentRequest.rolledBack.info":
    "Payment cancelled — funds returned to your balance",

  "timeline.receive.pending.label": "Ready to redeem",
  "timeline.receive.pending.info": "Tap Redeem to add to wallet",
  "timeline.receive.accepted.label": "Token accepted",
  "timeline.receive.waiting.label": "Waiting to redeem",
  "timeline.receive.waiting.info":
    "We'll add this ecash to your wallet when you're back online.",
  "timeline.receive.redeemed.label": "Added to wallet",
  "timeline.receive.redeemed.info": "+{amount} sats added to wallet",
  "timeline.receive.alreadySpent.label": "Already spent",
  "timeline.receive.alreadySpent.info": "The mint reports this token as spent",
  "timeline.receive.rejected.label": "Not added",
  "timeline.receive.rejected.info":
    "The mint did not accept this token. Nothing was added to your balance.",
  "timeline.receiveRequest.requested.label": "Requested",
  "timeline.receiveRequest.requested.info": "Waiting for payment over Nostr…",
  "timeline.receiveRequest.paid.label": "Payment received",
  "timeline.receiveRequest.paid.info": "Redeeming…",

  "timeline.status.failed": "Failed",
  "timeline.status.complete": "Complete",
  "timeline.status.inProgress": "In Progress",
  "timeline.status.waiting": "Waiting",
  "timeline.status.awaitingPayment": "Awaiting Payment",
  "timeline.status.ready": "Ready",
  "timeline.status.cancelled": "Cancelled",
  "timeline.status.alreadySpent": "Already Spent",
  "timeline.status.notAdded": "Not Added",
  "timeline.status.pending": "Pending",
  "timeline.onchain.waitingFirstConfirmation": "Waiting for first confirmation",
  "timeline.onchain.paymentConfirmed": "Payment confirmed onchain",
  "timeline.onchain.confirmations": "{current}/{required} confirmations",
  // Onchain deposits confirm on-chain (our own explorer) BEFORE the mint credits
  // the quote. The middle step reflects that waiting-on-the-mint phase and must
  // not claim "Payment received" — that milestone belongs to the mint marking
  // the quote PAID.
  "timeline.onchain.confirmingLabel": "Confirming on-chain",
  "timeline.onchain.confirmedLabel": "Confirmed on-chain",
  "timeline.onchain.waitingForMint": "Waiting for mint to credit",
  "timeline.cancelling.label": "Cancelling",
  "timeline.cancelling.info": "Returning ecash to your balance",
  "timeline.mint.created.label": "Invoice created",
  "timeline.mint.issuing.label": "Adding to wallet",
  "timeline.mint.issuing.info": "Collecting your ecash from the mint",
  "timeline.mint.failed.afterPaymentInfo":
    "The payment arrived but the mint did not issue ecash",
  "timeline.onchain.created.label": "Address created",
  "timeline.onchain.deposit.waitingLabel": "Waiting for deposit",
  "timeline.onchain.deposit.seenLabel": "Deposit detected",
  "timeline.onchain.droppedInfo":
    "The transaction is no longer in the mempool",
  "timeline.onchain.waitingForMintInfo":
    "Deep enough by our count. The mint credits it once its own node agrees.",
  "timeline.melt.created.label": "Payment prepared",
  "timeline.melt.submitted.label": "Ecash sent to mint",
  "timeline.melt.failed.label": "Payment failed",
  "timeline.melt.onchain.broadcast.label": "Broadcast",
  "timeline.melt.onchain.settling.label": "Paid by the mint",
  "timeline.melt.onchain.settling.info": "Looking for the transaction",
  "timeline.mint.unrestored.info":
    "The mint issued this ecash but it could not be restored",
  "timeline.melt.onchain.confirming.label": "Confirming",
  "timeline.send.creating.label": "Creating token",
  "timeline.send.creating.info": "Setting aside ecash",
  "timeline.send.unlock.infoRefundSignatures":
    "Refund signatures are required",
  "timeline.paymentRequest.delivering.label": "Delivering",
  "timeline.paymentRequest.delivering.info": "Sending to the recipient",
  "timeline.onchain.notCredited.label":
    "Not credited by the mint",
  "timeline.onchain.notCredited.info":
    "The deposit is confirmed, but the mint has not added it. Mints skip deposits below their minimum and ones that arrive after the request expires. Contact the mint.",
  "timeline.melt.pending.slowInfo":
    "Taking longer than usual. Your ecash stays held until the mint reports it paid or failed.",
  "timeline.cancelling.slowInfo":
    "This has not finished. Your ecash is still held and may need recovering.",
  "timeline.paymentRequest.delivered.nostrInfo":
    "Sent over Nostr",
  "timeline.paymentRequest.delivered.httpInfo":
    "Sent to the recipient's server",
  "timeline.onchain.waitingForMintPlainInfo":
    "The mint has not credited the deposit yet",
  "timeline.unknown.label":
    "Status unavailable",
  "timeline.unknown.info":
    "This version of the app cannot read this transaction's state",
  "timeline.melt.onchain.awaitingMint.label":
    "Waiting for the mint",
  "timeline.melt.onchain.awaitingMint.info":
    "Deep enough by our count. The mint confirms it once its own node agrees.",
  "timeline.paymentRequest.ready.label":
    "Ready to pay",
  "timeline.paymentRequest.ready.info":
    "Nothing has been sent yet",
  "timeline.flow.receive": "Receive",
  "timeline.flow.send": "Send",
  "timeline.flow.payment": "Payment",
  "timeline.flow.transaction": "Transaction",

  "send.warning.mintOffline.title": "Mint was offline",
  "send.warning.mintOffline.description":
    "This token was created offline. The recipient may have trouble redeeming it until the mint is back online.",
  "send.warning.deviceOffline.title": "You were offline",
  "send.warning.deviceOffline.description":
    "This token was created from local proofs while your device was offline. The recipient can redeem it after they can reach the mint.",
  "send.warning.mintUnreachable.title": "Mint appears offline",
  "send.warning.mintUnreachable.description":
    "This token was created from local proofs. The mint did not respond to a quick reachability check, so redemption may wait until it is reachable.",

  "history.refresh.sentWith": "Sent with",
  "history.refresh.sendingWith": "Sending with",
  "history.refresh.receivedWith": "Received with",
  "history.refresh.receivingWith": "Receiving with",
  "history.refresh.processingWith": "Processing with",
  "history.refresh.mintAlt": "Mint",

  "toast.receive.message": "Payment received",
  "toast.receive.processing": "Adding to wallet...",
  "toast.receive.confirmed": "Received",
  "toast.receive.failed": "Payment failed",
  "toast.send.message": "Payment sent",
  "toast.send.processing": "Sending...",
  "toast.send.confirmed": "Sent",
  "toast.send.failed": "Payment failed",
  "toast.paymentRequest.message": "Payment request sent",
  "toast.paymentRequest.processing": "Waiting for recipient",
  "toast.paymentRequest.delivered": "Sent via Nostr",
  "toast.paymentRequest.confirmed": "Claimed by recipient",
  "toast.paymentRequest.failed": "Payment failed",
  "toast.melt.message": "Payment sent",
  "toast.melt.processing": "Sending...",
  "toast.melt.confirmed": "Sent",
  "toast.melt.failed": "Payment failed",
  "toast.receiveEcash.message": "Payment received",
  "toast.receiveEcash.processing": "Redeeming...",
  "toast.receiveEcash.confirmed": "Received",
  "toast.receiveEcash.failed": "Payment failed",

  // Detected Send-flow destination row (describeDestination). For person-kinds
  // the label is the bare verb and the app appends the resolved recipient name.
  "send.destination.redeemAmount": "Redeem {amount} sats",
  "send.destination.redeem": "Redeem ecash",
  "send.destination.payAmount": "Pay {amount} sats",
  "send.destination.pay": "Pay",
  "send.destination.lockEcash": "Lock ecash to",
  "send.destination.payRequest": "Pay request",
  "send.destination.payInvoice": "Pay invoice",
  "send.destination.sendAmount": "Send {amount} sats",
  "send.destination.sendOnchain": "Send onchain",
  "send.destination.openMint": "View mint",
  "send.destination.unsupported": "Unrecognized destination",

  // Transaction header titles. One phrase per rail per phase, so a screen that
  // already happened never reads as an instruction: a settled melt says "Sent
  // Lightning", not "Send Lightning". `{name}` is the counterparty, and the
  // person phrasing replaces the rail phrasing whenever the transaction names
  // someone — including a zap, which is a payment to the post's author.
  "header.lightningSend.ready": "Send Lightning",
  "header.lightningSend.inFlight": "Sending Lightning",
  "header.lightningSend.settled": "Sent Lightning",
  "header.lightningSend.cancelled": "Cancelled payment",
  "header.lightningSend.failed": "Lightning send failed",
  "header.lightningSend.expired": "Quote expired",
  "header.onchainSend.ready": "Send onchain",
  "header.onchainSend.inFlight": "Sending onchain",
  "header.onchainSend.settled": "Sent onchain",
  "header.onchainSend.cancelled": "Cancelled payment",
  "header.onchainSend.failed": "Onchain send failed",
  "header.onchainSend.expired": "Quote expired",
  "header.ecashSend.ready": "Send ecash",
  "header.ecashSend.inFlight": "Sending ecash",
  "header.ecashSend.settled": "Sent ecash",
  "header.ecashSend.cancelled": "Cancelled ecash",
  "header.ecashSend.failed": "Send failed",
  "header.ecashSend.expired": "Expired",
  "header.lightningReceive.ready": "Receive Lightning",
  "header.lightningReceive.inFlight": "Receiving Lightning",
  "header.lightningReceive.settled": "Received Lightning",
  "header.lightningReceive.cancelled": "Cancelled receive",
  "header.lightningReceive.failed": "Receive failed",
  "header.lightningReceive.expired": "Invoice expired",
  "header.onchainReceive.ready": "Receive onchain",
  "header.onchainReceive.inFlight": "Receiving onchain",
  "header.onchainReceive.settled": "Received onchain",
  "header.onchainReceive.cancelled": "Cancelled receive",
  "header.onchainReceive.failed": "Receive failed",
  "header.onchainReceive.expired": "Expired",
  "header.ecashReceive.ready": "Receive ecash",
  "header.ecashReceive.inFlight": "Receiving ecash",
  "header.ecashReceive.settled": "Received ecash",
  "header.ecashReceive.cancelled": "Cancelled ecash",
  "header.ecashReceive.failed": "Receive failed",
  "header.ecashReceive.expired": "Expired",
  "header.swap.ready": "Swap",
  "header.swap.inFlight": "Swapping",
  "header.swap.settled": "Swapped",
  "header.swap.cancelled": "Cancelled swap",
  "header.swap.failed": "Swap failed",
  "header.swap.expired": "Expired",
  "header.payPerson.ready": "Pay {name}",
  "header.payPerson.inFlight": "Paying {name}",
  "header.payPerson.settled": "Paid {name}",
  "header.payPerson.cancelled": "Payment cancelled",
  "header.payPerson.failed": "Payment failed",
  "header.payPerson.expired": "Payment expired",
  "header.receivePerson.ready": "Receive from {name}",
  "header.receivePerson.inFlight": "Receiving from {name}",
  "header.receivePerson.settled": "Received from {name}",
  "header.receivePerson.cancelled": "Receive cancelled",
  "header.receivePerson.failed": "Receive failed",
  "header.receivePerson.expired": "Expired",
} as const satisfies PaymentCopyCatalog;
