import type { PaymentCopyCatalog } from "./types";

export const paymentCopyDefaults = {
  "timeline.mint.unpaid.label": "Waiting for payment",
  "timeline.mint.unpaid.info": "Pay the invoice to receive funds",
  "timeline.mint.unpaid.onchainInfo": "Pay the address to receive funds",
  "timeline.mint.paid.label": "Payment received",
  "timeline.mint.paid.info": "Adding to wallet...",
  "timeline.mint.issued.label": "Complete",
  "timeline.mint.issued.info": "+{amount} sats added to wallet",
  "timeline.mint.expired.label": "Expired",
  "timeline.mint.expired.info": "Invoice expired without payment",
  "timeline.mint.failed.label": "Failed",
  "timeline.mint.failed.info": "Receive could not be completed",

  "timeline.melt.unpaid.label": "Ready to send",
  "timeline.melt.unpaid.info": "Tap Send to complete payment",
  "timeline.melt.pending.label": "Sending",
  "timeline.melt.pending.info": "Payment in progress...",
  "timeline.melt.paid.label": "Sent",
  "timeline.melt.paid.info": "Payment complete",
  "timeline.melt.expired.label": "Expired",
  "timeline.melt.expired.info": "Quote expired",

  "timeline.send.prepared.label": "Created",
  "timeline.send.prepared.info": "Ready to share",
  "timeline.send.pending.label": "Pending",
  "timeline.send.pending.info": "Waiting for recipient",
  "timeline.send.finalized.label": "Claimed",
  "timeline.send.finalized.info": "Claimed by recipient",
  "timeline.send.rolledBack.label": "Cancelled",
  "timeline.send.rolledBack.info": "Funds returned to your balance",

  "timeline.paymentRequest.prepared.label": "Created",
  "timeline.paymentRequest.prepared.info": "Creating token...",
  "timeline.paymentRequest.nostrSent.label": "Delivered",
  "timeline.paymentRequest.nostrSent.infoSending": "Sending...",
  "timeline.paymentRequest.nostrSent.infoSent": "Sent via Nostr",
  "timeline.paymentRequest.finalized.label": "Claimed",
  "timeline.paymentRequest.finalized.info": "Claimed by recipient",
  "timeline.paymentRequest.rolledBack.label": "Cancelled",
  "timeline.paymentRequest.rolledBack.info":
    "Delivery failed — funds returned to your balance",

  "timeline.receive.pending.label": "Pending",
  "timeline.receive.pending.info": "Tap Redeem to add to wallet",
  "timeline.receive.accepted.label": "Token accepted",
  "timeline.receive.waiting.label": "Waiting to redeem",
  "timeline.receive.waiting.info":
    "We'll add this ecash to your wallet when you're back online.",
  "timeline.receive.redeemed.label": "Added to wallet",
  "timeline.receive.redeemed.info": "+{amount} sats added to wallet",
  "timeline.receive.alreadySpent.label": "Already spent",
  "timeline.receive.alreadySpent.info": "Token was already redeemed elsewhere",
  "timeline.receiveRequest.requested.label": "Requested",
  "timeline.receiveRequest.requested.info": "Waiting for payment over Nostr…",
  "timeline.receiveRequest.paid.label": "Payment received",
  "timeline.receiveRequest.paid.info": "Redeeming…",

  "timeline.status.failed": "Failed",
  "timeline.status.complete": "Complete",
  "timeline.status.inProgress": "In Progress",
  "timeline.status.waiting": "Waiting",
  "timeline.status.awaitingPayment": "Awaiting Payment",
  "timeline.status.ready": "Ready",
  "timeline.status.cancelled": "Cancelled",
  "timeline.status.alreadySpent": "Already Spent",
  "timeline.status.pending": "Pending",
  "timeline.onchain.waitingFirstConfirmation": "Waiting for first confirmation",
  "timeline.onchain.paymentConfirmed": "Payment confirmed onchain",
  "timeline.onchain.confirmations": "{current}/{required} confirmations",
  // Onchain deposits confirm on-chain (our own explorer) BEFORE the mint credits
  // the quote. The middle step reflects that waiting-on-the-mint phase and must
  // not claim "Payment received" — that milestone belongs to the mint marking
  // the quote PAID.
  "timeline.onchain.confirmingLabel": "Confirming on-chain",
  "timeline.onchain.confirmedLabel": "Confirmed on-chain",
  "timeline.onchain.waitingForMint": "Waiting for mint to credit",
  "timeline.flow.receive": "Receive",
  "timeline.flow.send": "Send",
  "timeline.flow.payment": "Payment",
  "timeline.flow.transaction": "Transaction",

  "send.warning.mintOffline.title": "Mint was offline",
  "send.warning.mintOffline.description":
    "This token was created offline. The recipient may have trouble redeeming it until the mint is back online.",
  "send.warning.deviceOffline.title": "You were offline",
  "send.warning.deviceOffline.description":
    "This token was created from local proofs while your device was offline. The recipient can redeem it after they can reach the mint.",
  "send.warning.mintUnreachable.title": "Mint appears offline",
  "send.warning.mintUnreachable.description":
    "This token was created from local proofs. The mint did not respond to a quick reachability check, so redemption may wait until it is reachable.",

  "history.refresh.sentWith": "Sent with",
  "history.refresh.sendingWith": "Sending with",
  "history.refresh.receivedWith": "Received with",
  "history.refresh.receivingWith": "Receiving with",
  "history.refresh.processingWith": "Processing with",
  "history.refresh.mintAlt": "Mint",

  "toast.receive.message": "Payment received",
  "toast.receive.processing": "Adding to wallet...",
  "toast.receive.confirmed": "Received",
  "toast.receive.failed": "Payment failed",
  "toast.send.message": "Payment sent",
  "toast.send.processing": "Sending...",
  "toast.send.confirmed": "Sent",
  "toast.send.failed": "Payment failed",
  "toast.paymentRequest.message": "Payment request sent",
  "toast.paymentRequest.processing": "Waiting for recipient",
  "toast.paymentRequest.delivered": "Delivered to recipient",
  "toast.paymentRequest.confirmed": "Claimed by recipient",
  "toast.paymentRequest.failed": "Payment failed",
  "toast.melt.message": "Payment sent",
  "toast.melt.processing": "Sending...",
  "toast.melt.confirmed": "Sent",
  "toast.melt.failed": "Payment failed",
  "toast.receiveEcash.message": "Payment received",
  "toast.receiveEcash.processing": "Redeeming...",
  "toast.receiveEcash.confirmed": "Received",
  "toast.receiveEcash.failed": "Payment failed",

  // Detected Send-flow destination row (describeDestination). For person-kinds
  // the label is the bare verb and the app appends the resolved recipient name.
  "send.destination.redeemAmount": "Redeem {amount} sats",
  "send.destination.redeem": "Redeem ecash",
  "send.destination.payAmount": "Pay {amount} sats",
  "send.destination.pay": "Pay",
  "send.destination.payRequest": "Pay request",
  "send.destination.payInvoice": "Pay invoice",
  "send.destination.sendAmount": "Send {amount} sats",
  "send.destination.sendOnchain": "Send onchain",
  "send.destination.openMint": "View mint",
  "send.destination.unsupported": "Unrecognized destination",
} as const satisfies PaymentCopyCatalog;
