import { Platform } from 'react-native';
import { requireNativeModule, type EventSubscription } from 'expo-modules-core';
import type {
  BLEDeliveryStatusEvent,
  BLEDmContact,
  BLEMessageEvent,
  BLEPeer,
  BLEPeerEvent,
  BLEPrivateMessageEvent,
  BitchatBLEIdentityMaterial,
  NostrMessageEvent,
  NostrPrivateMessageEvent,
} from './types';

interface BitChatNativeModule {
  // BLE
  startBLE(
    nickname: string,
    profileScope: string,
    noisePrivateKeyHex: string,
    signingPrivateKeyHex: string
  ): Promise<void>;
  sendBLEMessage(content: string): Promise<void>;
  startBLEPrivateChat(peerID: string): Promise<void>;
  resetBLEPrivateChat(peerID: string): Promise<void>;
  sendBLEPrivateMessage(
    peerID: string,
    content: string,
    nickname: string,
    messageID: string
  ): Promise<string>;
  getBLEPeers(): BLEPeer[];
  getBLEDmHistory(profileScope: string): BLEDmContact[];
  getBLEState(): string;
  // Nostr (native — wraps upstream bitchat's NostrRelayManager + GeoRelayDirectory)
  startNostr(profileScope: string): Promise<void>;
  joinGeohash(hash: string): Promise<void>;
  leaveGeohash(): Promise<void>;
  sendGeohashMessage(content: string, nickname: string): Promise<void>;
  sendGeohashPrivateMessage(recipientPubkey: string, content: string): Promise<void>;
  // Events — `event` is unknown at the bridge boundary; typed wrappers below
  // cast to the per-event payload that the native side actually dispatches.
  addListener(eventName: string, listener: (event: unknown) => void): EventSubscription;
  removeListeners(count: number): void;
}

// expo-module.config.json declares `{ "platforms": ["apple"] }` — calling
// `requireNativeModule('BitChat')` on Android throws synchronously at module
// load. Mirror the canonical pattern used by liquid-glass-text: resolve to
// `null` off-iOS, and have each export degrade gracefully.
const NativeModule: BitChatNativeModule | null =
  Platform.OS === 'ios' ? requireNativeModule<BitChatNativeModule>('BitChat') : null;

class BitChatUnavailableError extends Error {
  constructor() {
    super('BitChat native module is unavailable on this platform');
    this.name = 'BitChatUnavailableError';
  }
}

const NOOP_SUBSCRIPTION: EventSubscription = { remove: () => {} };

function unavailable(): Promise<never> {
  return Promise.reject(new BitChatUnavailableError());
}

// --- BLE Mesh ---

const KEY_HEX_RE = /^[0-9a-f]{64}$/;

function validateBLEIdentityMaterial(
  identityMaterial: BitchatBLEIdentityMaterial | null | undefined
): void {
  if (!identityMaterial) {
    throw new Error('BitChat identity material unavailable');
  }
  if (identityMaterial.version !== 'sovran-bitchat-ble-v1') {
    throw new Error('BitChat identity material has an unsupported version');
  }
  if (!KEY_HEX_RE.test(identityMaterial.nostrPubkey)) {
    throw new Error('BitChat Nostr identity material is invalid');
  }
  if (!KEY_HEX_RE.test(identityMaterial.noisePrivateKeyHex)) {
    throw new Error('BitChat noise identity material is invalid');
  }
  if (!KEY_HEX_RE.test(identityMaterial.signingPrivateKeyHex)) {
    throw new Error('BitChat signing identity material is invalid');
  }
}

export function startBLE(
  nickname: string,
  profileScope: string,
  identityMaterial: BitchatBLEIdentityMaterial
): Promise<void> {
  try {
    validateBLEIdentityMaterial(identityMaterial);
  } catch (err) {
    return Promise.reject(err);
  }
  return NativeModule
    ? NativeModule.startBLE(
        nickname,
        profileScope,
        identityMaterial.noisePrivateKeyHex,
        identityMaterial.signingPrivateKeyHex
      )
    : unavailable();
}

export function sendBLEMessage(content: string): Promise<void> {
  return NativeModule ? NativeModule.sendBLEMessage(content) : unavailable();
}

/**
 * Prepare a BLE private chat. Triggers the Noise XX handshake if no session
 * exists yet. Safe to call repeatedly — no-op once a session is established.
 */
export function startBLEPrivateChat(peerID: string): Promise<void> {
  return NativeModule ? NativeModule.startBLEPrivateChat(peerID) : unavailable();
}

/**
 * Clear the Noise session for `peerID`. The next outbound DM will trigger a
 * fresh XX handshake. Use this when the JS-side watchdog detects a stuck
 * `sending` message — the session is likely invalidated. Does not drain
 * upstream's pending-message queue; the JS store should mark stuck sends
 * `failed` so they don't double-send when the new handshake completes.
 */
export function resetBLEPrivateChat(peerID: string): Promise<void> {
  return NativeModule ? NativeModule.resetBLEPrivateChat(peerID) : unavailable();
}

/**
 * Send a Noise-encrypted 1:1 message over BLE mesh. If no session exists,
 * upstream bitchat queues the message and triggers a handshake automatically.
 * `nickname` is OUR nickname — upstream stamps it into the message for the
 * recipient's display. `messageID` is generated by the caller so the
 * optimistic chat bubble and later `onBLEDeliveryStatus` events
 * (sending / sent / delivered / failed) can be correlated on a single key.
 * Returns the same messageID for ergonomic chaining.
 */
export function sendBLEPrivateMessage(
  peerID: string,
  content: string,
  nickname: string,
  messageID: string
): Promise<string> {
  return NativeModule
    ? NativeModule.sendBLEPrivateMessage(peerID, content, nickname, messageID)
    : unavailable();
}

export function addBLEPrivateMessageListener(
  listener: (event: BLEPrivateMessageEvent) => void
): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onBLEPrivateMessage', listener as (e: unknown) => void);
}

/**
 * Subscribe to delivery-status transitions for outbound BLE DMs. Each event
 * carries the same `messageID` originally passed to `sendBLEPrivateMessage`.
 * Subscribe once at app-level so events aren't lost while the DM screen
 * isn't mounted.
 */
export function addBLEDeliveryStatusListener(
  listener: (event: BLEDeliveryStatusEvent) => void
): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onBLEDeliveryStatus', listener as (e: unknown) => void);
}

export function getBLEPeers(): BLEPeer[] {
  return NativeModule ? NativeModule.getBLEPeers() : [];
}

/**
 * Returns the persisted 1:1 DM-peer history (peerID + best-known nickname +
 * last activity timestamp). Survives app restarts — fed by both inbound and
 * outbound BLE DMs in the native bridge. Empty array on Android (no native
 * bridge) and on first-launch iOS before any DM has flowed.
 */
export function getBLEDmHistory(profileScope: string): BLEDmContact[] {
  return NativeModule && profileScope ? NativeModule.getBLEDmHistory(profileScope) : [];
}

export function getBLEState(): string {
  return NativeModule ? NativeModule.getBLEState() : 'unavailable';
}

export function addBLEMessageListener(
  listener: (event: BLEMessageEvent) => void
): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onBLEMessage', listener as (e: unknown) => void);
}

export function addBLEPeerListener(listener: (event: BLEPeerEvent) => void): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onBLEPeerUpdate', listener as (e: unknown) => void);
}

export function addBLEStateListener(
  listener: (event: { state: string }) => void
): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onBLEStateChanged', listener as (e: unknown) => void);
}

// --- Nostr ---

export function startNostr(profileScope: string): Promise<void> {
  return NativeModule ? NativeModule.startNostr(profileScope) : unavailable();
}

export function joinGeohash(hash: string): Promise<void> {
  return NativeModule ? NativeModule.joinGeohash(hash) : unavailable();
}

export function leaveGeohash(): Promise<void> {
  return NativeModule ? NativeModule.leaveGeohash() : unavailable();
}

export function sendGeohashMessage(content: string, nickname: string): Promise<void> {
  return NativeModule ? NativeModule.sendGeohashMessage(content, nickname) : unavailable();
}

/**
 * Send a NIP-17 gift-wrapped DM to another participant in the currently-
 * joined geohash. The recipient is addressed by the Nostr hex pubkey
 * observed on their public geohash messages (`senderPubkey` from
 * `onNostrMessage` events).
 */
export function sendGeohashPrivateMessage(recipientPubkey: string, content: string): Promise<void> {
  return NativeModule
    ? NativeModule.sendGeohashPrivateMessage(recipientPubkey, content)
    : unavailable();
}

export function addNostrMessageListener(
  listener: (event: NostrMessageEvent) => void
): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onNostrMessage', listener as (e: unknown) => void);
}

export function addNostrPrivateMessageListener(
  listener: (event: NostrPrivateMessageEvent) => void
): EventSubscription {
  if (!NativeModule) return NOOP_SUBSCRIPTION;
  return NativeModule.addListener('onNostrPrivateMessage', listener as (e: unknown) => void);
}
