/**
 * @jest-environment node
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { check, resolveConfig } from 'prettier';

/**
 * The ratcheted JSON artifacts are generated by their gate's `--update` mode
 * and committed, so `bun run pretty:check` also checks them. Writing them with
 * a bare `JSON.stringify(value, null, 2)` puts the two tools in direct
 * conflict — `JSON.stringify` always expands an array, Prettier collapses one
 * that fits inside `printWidth`. `react-compiler-bailouts.json` has arrays of
 * short strings, so every `check:react-compiler:update` left the formatter red,
 * and running `prettier --write` on it was undone by the next update: a closed
 * loop, and formatting churn dropped into whichever PR next banked the ratchet.
 *
 * `pretty:check` is not one of the workflows the README badges enforce, so this
 * suite is what actually holds the invariant — `bun run test` is in CI.
 */
const APP_DIR = path.resolve(__dirname, '..');
const SCRIPTS_DIR = path.join(APP_DIR, 'scripts');

/**
 * Every generated-and-committed artifact, with the gate that writes it and the
 * identifier that gate holds its path in.
 */
const ARTIFACTS: { file: string; writer: string; pathConst: string }[] = [
  {
    file: 'react-compiler-bailouts.json',
    writer: 'check-react-compiler.mjs',
    pathConst: 'BASELINE_PATH',
  },
  { file: 'styling-budget.json', writer: 'check-styling.mjs', pathConst: 'BUDGET_FILE' },
];

describe('ratcheted artifacts', () => {
  it.each(ARTIFACTS)('$file is formatted as pretty:check expects', async ({ file }) => {
    const filepath = path.join(APP_DIR, file);
    // `editorconfig: true` mirrors the CLI `pretty:check` runs, and the
    // helper that writes these files.
    const options = await resolveConfig(filepath, { editorconfig: true });
    await expect(
      check(readFileSync(filepath, 'utf8'), { ...options, filepath, parser: 'json' })
    ).resolves.toBe(true);
  });

  it.each(ARTIFACTS)('$writer writes through the shared formatter', ({ writer, pathConst }) => {
    // Not merely "is formatted today": the next `--update` has to produce
    // the same thing. A gate that serializes and writes the artifact itself
    // is how the conflict came back the last time someone fixed the file by
    // hand. Scoped to THIS artifact's path — an unrelated write elsewhere in
    // the script is none of this test's business.
    const source = readFileSync(path.join(SCRIPTS_DIR, writer), 'utf8');
    expect(source).toContain("import { writeRatchetArtifact } from './lib/ratchet-artifact.mjs';");
    expect(source).toMatch(new RegExp(`await writeRatchetArtifact\\(\\s*${pathConst}`));
    expect(source).not.toMatch(new RegExp(`writeFileSync\\(\\s*${pathConst}`));
  });

  it('formats through the config Prettier resolves, not a copy of its rules', () => {
    // Hand-matching `printWidth` here would drift the moment prettier.config.js
    // changes. The helper asks Prettier for the config of the exact path it is
    // about to write.
    const helper = readFileSync(path.join(SCRIPTS_DIR, 'lib/ratchet-artifact.mjs'), 'utf8');
    expect(helper).toContain("await import('prettier')");
    expect(helper).toContain(
      'const options = await resolveConfig(filePath, { editorconfig: true });'
    );
    expect(helper).toContain('filepath: filePath,');
  });
});
