export const SET_ROUTSTR_TOKEN = 'SET_ROUTSTR_TOKEN';
export const SET_ROUTSTR_BALANCE = 'SET_ROUTSTR_BALANCE';
export const ADD_ROUTSTR_SESSION = 'ADD_ROUTSTR_SESSION';
export const ADD_ROUTSTR_MESSAGE = 'ADD_ROUTSTR_MESSAGE';
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION';
export const SET_LAST_TOKEN = 'SET_LAST_TOKEN';
