/** Explicit route aliases for canonical pages. This is an inventory, not a
 * coverage claim. The audit gate rejects unregistered new routes. */
import type { CANONICAL_PAGES } from './pages';
export const PAGE_ROUTES: Partial<Record<(typeof CANONICAL_PAGES)[number], readonly string[]>> = {
  ai: ['(drawer)/(tabs)/ai/index.tsx'],
  contacts: ['(drawer)/(tabs)/contacts/index.tsx'],
  feed: ['(drawer)/(tabs)/feed/index.tsx'],
  wallet: ['(drawer)/(tabs)/index/index.tsx'],
  'notification-followers': ['(drawer)/(tabs)/notifications/followers.tsx'],
  notifications: ['(drawer)/(tabs)/notifications/index.tsx'],
  'notification-mint-changes': ['(drawer)/(tabs)/notifications/mint-changes.tsx'],
  'transaction-filters': ['(filter-flow)/filters.tsx'],
  'map-detail': ['(map-flow)/detail.tsx'],
  map: ['(map-flow)/index.tsx'],
  'mint-add': ['(mint-flow)/add.tsx'],
  'balance-split': ['(mint-flow)/distribution.tsx'],
  'mint-info': ['(mint-flow)/info.tsx'],
  'rebalance-plan': ['(mint-flow)/rebalancePlan.tsx'],
  'mint-reviews': ['(mint-flow)/reviews.tsx'],
  'dm-chat': [
    '(mint-flow)/userMessages.tsx',
    '(profile-flow)/userMessages.tsx',
    '(user-flow)/userMessages.tsx',
    'userMessages.tsx',
  ],
  'bitchat-dm': ['(profile-flow)/bitchatDM.tsx', '(user-flow)/bitchatDM.tsx'],
  'bitchat-network': ['(profile-flow)/bitchatNetwork.tsx', '(user-flow)/bitchatNetwork.tsx'],
  profile: ['(profile-flow)/profile.tsx', '(user-flow)/profile.tsx'],
  'profile-share': ['(profile-flow)/share.tsx', '(user-flow)/share.tsx', 'share.tsx'],
  thread: ['(profile-flow)/thread.tsx', '(transactions-flow)/thread.tsx', '(user-flow)/thread.tsx'],
  'whitenoise-dm': ['(profile-flow)/whitenoiseDM.tsx', '(user-flow)/whitenoiseDM.tsx'],
  'whitenoise-setup': ['(profile-flow)/whitenoiseSetup.tsx', '(user-flow)/whitenoiseSetup.tsx'],
  'receive-amount': ['(receive-flow)/amount.tsx'],
  camera: ['(receive-flow)/camera.tsx', '(send-flow)/camera.tsx', 'camera.tsx'],
  'lightning-receive': [
    '(receive-flow)/lightningReceive.tsx',
    '(transactions-flow)/lightningReceive.tsx',
    'lightningReceive.tsx',
  ],
  'mint-select': ['(receive-flow)/mintSelect.tsx', '(send-flow)/mintSelect.tsx'],
  'onchain-receive': [
    '(receive-flow)/onchainReceive.tsx',
    '(transactions-flow)/onchainReceive.tsx',
    'onchainReceive.tsx',
  ],
  'payment-request': [
    '(receive-flow)/paymentRequest.tsx',
    '(send-flow)/paymentRequest.tsx',
    'paymentRequest.tsx',
  ],
  'receive-qr': ['(receive-flow)/qrDisplay.tsx'],
  'receive-rails': ['(receive-flow)/railList.tsx'],
  receive: ['(receive-flow)/receive.tsx'],
  'receive-token': [
    '(receive-flow)/receiveToken.tsx',
    '(transactions-flow)/receiveToken.tsx',
    'receiveToken.tsx',
  ],
  'send-amount': ['(send-flow)/amount.tsx'],
  'lightning-send': [
    '(send-flow)/lightningSend.tsx',
    '(transactions-flow)/lightningSend.tsx',
    'lightningSend.tsx',
  ],
  'near-pay': ['(send-flow)/nearPay.tsx'],
  'near-pay-peers': ['(send-flow)/nearPayPeers.tsx'],
  'onchain-send': [
    '(send-flow)/onchainSend.tsx',
    '(transactions-flow)/onchainSend.tsx',
    'onchainSend.tsx',
  ],
  send: ['(send-flow)/send.tsx'],
  'send-token': ['(send-flow)/sendToken.tsx', '(transactions-flow)/sendToken.tsx', 'sendToken.tsx'],
  'settings-delete': ['(settings-flow)/delete.tsx'],
  'settings-design-system-empty-states': ['(settings-flow)/design-system-empty-states.tsx'],
  'settings-design-system-fade-stress': ['(settings-flow)/design-system-fade-stress.tsx'],
  'settings-design-system-foundations': ['(settings-flow)/design-system-foundations.tsx'],
  'settings-design-system-loading': ['(settings-flow)/design-system-loading.tsx'],
  'settings-design-system-posts': ['(settings-flow)/design-system-posts.tsx'],
  'settings-design-system-segmented': ['(settings-flow)/design-system-segmented.tsx'],
  'settings-design-system-skeleton-crossfade': [
    '(settings-flow)/design-system-skeleton-crossfade.tsx',
  ],
  'settings-design-system-timeline': ['(settings-flow)/design-system-timeline.tsx'],
  'settings-design-system-wallet-controls': ['(settings-flow)/design-system-wallet-controls.tsx'],
  'settings-design-system': ['(settings-flow)/design-system.tsx'],
  settings: ['(settings-flow)/index.tsx'],
  'settings-keyring': ['(settings-flow)/keyring.tsx'],
  'settings-media': ['(settings-flow)/media.tsx'],
  'settings-moderation': ['(settings-flow)/moderation.tsx'],
  'settings-network': ['(settings-flow)/network.tsx'],
  'settings-notification-policy': ['(settings-flow)/notification-policy.tsx'],
  'settings-privacy': ['(settings-flow)/privacy.tsx'],
  'settings-profile': ['(settings-flow)/profile.tsx'],
  'settings-recovery': ['(settings-flow)/recovery.tsx'],
  'settings-routing': ['(settings-flow)/routing.tsx'],
  'settings-storage': ['(settings-flow)/storage.tsx'],
  'settings-terms': ['(settings-flow)/terms.tsx'],
  'signer-activity-detail': ['(signer-flow)/activity-detail.tsx'],
  'signer-activity': ['(signer-flow)/activity.tsx'],
  'signer-app-permissions': ['(signer-flow)/app-permissions.tsx'],
  'signer-app-person': ['(signer-flow)/app-person.tsx'],
  'signer-app': ['(signer-flow)/app.tsx'],
  'signer-connect': ['(signer-flow)/connect.tsx'],
  'signer-hub': ['(signer-flow)/index.tsx'],
  'signer-requests': ['(signer-flow)/requests.tsx'],
  'signer-share': ['(signer-flow)/share.tsx'],
  stories: ['(stories-flow)/stories.tsx'],
  'theme-background': ['(theme-flow)/background.tsx'],
  gallery: ['(theme-flow)/gallery.tsx'],
  'theme-preview': ['(theme-flow)/preview.tsx'],
  swap: ['(transactions-flow)/swap.tsx'],
  transactions: ['(transactions-flow)/transactions.tsx'],
  'geohash-chat': ['(user-flow)/geohashChat.tsx'],
  'not-found': ['+not-found.tsx'],
  'claim-username': ['claimUsername.tsx'],
  composer: ['composer.tsx'],
};
