import { ImageSource } from 'expo-image';

/**
 * Background Image Themes Configuration
 *
 * AUTO-GENERATED by `npm run build:themes`
 * Do not edit manually - changes will be overwritten.
 *
 * This is the single source of truth for all background image theme configuration.
 * Other files import from here to get background image paths, display names, etc.
 */

/**
 * Background image require() mappings.
 * Maps theme name to the image asset.
 */
export const backgroundImageThemes: Record<string, ImageSource> = {
  cosmicpurple: require('assets/images/backgrounds/cosmic-purple.png'),
  deepocean: require('assets/images/backgrounds/deep-ocean.png'),
  mysticblue: require('assets/images/backgrounds/mystic-blue.png'),
  royalpurple: require('assets/images/backgrounds/royal-purple.png'),
};

/**
 * Array of all background image theme names.
 */
export const BACKGROUND_THEME_NAMES = ['cosmicpurple', 'deepocean', 'mysticblue', 'royalpurple'];

/**
 * Display names for background image themes (from filename).
 */
export const backgroundThemeDisplayNames: Record<string, string> = {
  cosmicpurple: 'Cosmic Purple',
  deepocean: 'Deep Ocean',
  mysticblue: 'Mystic Blue',
  royalpurple: 'Royal Purple',
};

/**
 * Check if a theme is a background image theme.
 */
export const isBackgroundImageTheme = (themeName: string): boolean => {
  return BACKGROUND_THEME_NAMES.includes(themeName);
};

/**
 * Get the background image for a theme, or null if not a background theme.
 */
export const getBackgroundImage = (themeName: string): ImageSource | null => {
  return backgroundImageThemes[themeName] ?? null;
};

/**
 * Get the display name for a background theme.
 */
export const getBackgroundThemeDisplayName = (themeName: string): string | undefined => {
  return backgroundThemeDisplayNames[themeName];
};
