/**
 * Screenshot sync, screenshots.ts generation, composite preview, and pruning.
 *
 * Difference from the old tool: order.json is written as *ordering only*. It is
 * NOT used as a download allowlist, so new App Store Connect screenshots are
 * never silently skipped. Pure helpers (selectPruneTargets, generateScreenshotsTs,
 * pickPrimaryDevice) are exported separately from the filesystem/sharp IO.
 */

import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';

import { DEVICE_PREFERENCE, SOVRAN_MONEY_BASE } from '../release.config.mjs';

const require = createRequire(import.meta.url);

const screenshotUrl = (device, filename) => `${SOVRAN_MONEY_BASE}/ios/${device}/${filename}`;

/** First preferred device that has screenshots. Pure. */
export function pickPrimaryDevice(deviceScreenshots) {
  const present = Object.keys(deviceScreenshots);
  return DEVICE_PREFERENCE.find((d) => present.includes(d)) ?? present[0] ?? null;
}

/**
 * Download a version's screenshots from App Store Connect into device dirs.
 * Writes order.json per device (ordering only). Returns { deviceScreenshots,
 * primaryDevice } where deviceScreenshots maps device -> [public url].
 */
export async function syncScreenshots({ ascClient, version, iosPublicDir, downloadFile }) {
  const listing = await ascClient.listScreenshots(version);
  if (!listing) return { deviceScreenshots: {}, primaryDevice: null, locale: null, missing: true };

  const deviceScreenshots = {};
  for (const [device, shots] of Object.entries(listing.devices)) {
    const deviceDir = path.join(iosPublicDir, device);
    fs.mkdirSync(deviceDir, { recursive: true });

    const ordered = [];
    for (const shot of shots) {
      const filename = `${shot.id}.png`;
      const outPath = path.join(deviceDir, filename);
      if (!fs.existsSync(outPath)) await downloadFile(shot.url, outPath);
      ordered.push(filename);
      (deviceScreenshots[device] ??= []).push(screenshotUrl(device, filename));
    }
    fs.writeFileSync(path.join(deviceDir, 'order.json'), JSON.stringify(ordered, null, 2) + '\n');
  }

  return {
    deviceScreenshots,
    primaryDevice: pickPrimaryDevice(deviceScreenshots),
    locale: listing.locale,
    missing: false,
  };
}

/** Generate the contents of src/screenshots.ts. Pure. */
export function generateScreenshotsTs(deviceScreenshots, primaryDevice) {
  const rel = (url) => url.replace(SOVRAN_MONEY_BASE, '');
  const primary = deviceScreenshots[primaryDevice] || [];
  const lines = [
    '/**',
    ' * Screenshot URLs for Sovran',
    ' *',
    ' * Auto-generated by scripts/release-ios.mjs. Do not edit manually.',
    ' */',
    '',
    'export const screenshots = {',
    `  // Primary screenshots for the website (uses ${primaryDevice})`,
    '  primary: [',
    ...primary.map((u) => `    "${rel(u)}",`),
    '  ],',
    '',
    '  // All device types available',
    '  devices: {',
  ];
  for (const [device, urls] of Object.entries(deviceScreenshots)) {
    lines.push(`    "${device}": [`, ...urls.map((u) => `      "${rel(u)}",`), '    ],');
  }
  lines.push(
    '  },',
    '};',
    '',
    'export const getScreenshot = (index: number): string =>',
    '  screenshots.primary[index] || screenshots.primary[0];',
    '',
    'export const heroScreenshot = screenshots.primary[0];',
    'export const walletScreenshot = screenshots.primary[0];',
    'export const socialScreenshot = screenshots.primary[2] || screenshots.primary[0];',
    '',
    'export default screenshots;',
    ''
  );
  return lines.join('\n');
}

export function writeScreenshotsTs(targetPath, deviceScreenshots, primaryDevice) {
  fs.writeFileSync(targetPath, generateScreenshotsTs(deviceScreenshots, primaryDevice));
}

/** Build a tiled, rounded composite preview PNG from a device's screenshots. */
export async function generateComposite({ deviceDir, outPath }) {
  const sharp = require('sharp');
  const orderPath = path.join(deviceDir, 'order.json');
  const files = fs.existsSync(orderPath)
    ? JSON.parse(fs.readFileSync(orderPath, 'utf8'))
    : fs
        .readdirSync(deviceDir)
        .filter((f) => f.endsWith('.png'))
        .sort();
  if (!files.length) return null;

  const THUMB_HEIGHT = 480;
  const COLS = 4;
  const MARGIN = 16;
  const PADDING = 24;
  const RADIUS = 16;
  const IMG_RADIUS = 32;

  const thumbs = [];
  for (const file of files) {
    const buf = await sharp(path.join(deviceDir, file))
      .resize({ height: THUMB_HEIGHT })
      .png()
      .toBuffer();
    const meta = await sharp(buf).metadata();
    thumbs.push({ buf, w: meta.width, h: meta.height });
  }

  const rows = [];
  for (let i = 0; i < thumbs.length; i += COLS) rows.push(thumbs.slice(i, i + COLS));
  const rowW = (row) => row.reduce((s, t) => s + t.w, 0) + MARGIN * (row.length - 1);
  const totalW = Math.max(...rows.map(rowW)) + PADDING * 2;
  const totalH = rows.length * THUMB_HEIGHT + (rows.length - 1) * MARGIN + PADDING * 2;

  const bgSvg = Buffer.from(
    `<svg width="${totalW}" height="${totalH}"><rect width="${totalW}" height="${totalH}" rx="${RADIUS}" ry="${RADIUS}" fill="rgb(30,30,30)"/></svg>`
  );
  const roundCorners = (buf, w, h) => {
    const mask = Buffer.from(
      `<svg width="${w}" height="${h}"><rect width="${w}" height="${h}" rx="${IMG_RADIUS}" ry="${IMG_RADIUS}" fill="white"/></svg>`
    );
    return sharp(buf)
      .composite([{ input: mask, blend: 'dest-in' }])
      .png()
      .toBuffer();
  };

  const composites = [{ input: bgSvg, top: 0, left: 0 }];
  let y = PADDING;
  for (const row of rows) {
    let x = PADDING;
    for (const thumb of row) {
      composites.push({ input: await roundCorners(thumb.buf, thumb.w, thumb.h), top: y, left: x });
      x += thumb.w + MARGIN;
    }
    y += THUMB_HEIGHT + MARGIN;
  }

  await sharp({
    create: {
      width: totalW,
      height: totalH,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .png()
    .toFile(outPath);
  return { width: totalW, height: totalH };
}

/**
 * Choose which on-disk assets are safe to delete. Pure — takes listings, returns
 * absolute paths to remove. Conservative: only removes release dirs whose ADP is
 * no longer referenced, screenshot files not in their device's order.json, and
 * preview PNGs whose version is no longer listed.
 *
 * @param {object} a
 * @param {string[]} a.referencedAdpIds   ADP ids still referenced by the JSON
 * @param {{name:string,path:string}[]} a.releaseDirs   all release dirs on disk
 * @param {{device:string,file:string,path:string}[]} a.screenshotFiles  all device pngs
 * @param {Record<string,string[]>} a.orderByDevice   device -> filenames to keep
 * @param {{version:string,path:string}[]} a.previewFiles  screenshots-preview-*.png
 * @param {string[]} a.listedVersions   version strings still in the JSON
 */
export function selectPruneTargets({
  referencedAdpIds,
  releaseDirs,
  screenshotFiles,
  orderByDevice,
  previewFiles,
  listedVersions,
}) {
  const keepAdp = new Set(referencedAdpIds);
  const keepFile = new Set();
  for (const [device, files] of Object.entries(orderByDevice)) {
    for (const f of files) keepFile.add(`${device}/${f}`);
  }
  const keepVersion = new Set(listedVersions);

  return {
    releaseDirs: releaseDirs.filter((d) => !keepAdp.has(d.name)).map((d) => d.path),
    screenshots: screenshotFiles
      .filter((s) => !keepFile.has(`${s.device}/${s.file}`))
      .map((s) => s.path),
    previews: previewFiles.filter((p) => !keepVersion.has(p.version)).map((p) => p.path),
  };
}
