export type EmojiEntry = {
  emoji: string;
  keywords: string[];
};

export type EmojiCategory = {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
};

export const CATEGORIES: EmojiCategory[] = [
  {
    id: 'bitcoin',
    label: 'Bitcoin',
    icon: '₿',
    emojis: [
      { emoji: '😂', keywords: ['laugh', 'funny', 'joy'] },
      { emoji: '🥜', keywords: ['nut', 'peanut', 'cashu'] },
      { emoji: '⚡', keywords: ['lightning', 'zap', 'bolt', 'ln'] },
      { emoji: '🧡', keywords: ['heart', 'orange', 'bitcoin', 'love'] },
      { emoji: '🏆', keywords: ['trophy', 'win', 'champion'] },
      { emoji: '🌋', keywords: ['volcano', 'eruption', 'lava'] },
      { emoji: '🚀', keywords: ['rocket', 'launch', 'moon'] },
      { emoji: '💰', keywords: ['money', 'bag', 'rich', 'sats'] },
      { emoji: '🔑', keywords: ['key', 'lock', 'private', 'secret'] },
      { emoji: '🦡', keywords: ['badger', 'honey'] },
      { emoji: '🦍', keywords: ['gorilla', 'ape', 'strong'] },
      { emoji: '🪙', keywords: ['coin', 'token', 'gold'] },
      { emoji: '🔒', keywords: ['lock', 'secure', 'private'] },
      { emoji: '🛡️', keywords: ['shield', 'protect', 'defense'] },
      { emoji: '⛏️', keywords: ['pick', 'mine', 'mining'] },
      { emoji: '💎', keywords: ['diamond', 'gem', 'hodl'] },
    ],
  },
  {
    id: 'smileys',
    label: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { emoji: '😀', keywords: ['grinning', 'smile', 'happy'] },
      { emoji: '😃', keywords: ['grinning', 'big', 'eyes'] },
      { emoji: '😄', keywords: ['grinning', 'smiling', 'eyes'] },
      { emoji: '😁', keywords: ['beaming', 'grin', 'teeth'] },
      { emoji: '😆', keywords: ['grinning', 'squinting', 'laugh'] },
      { emoji: '😅', keywords: ['grinning', 'sweat', 'nervous'] },
      { emoji: '🤣', keywords: ['rofl', 'rolling', 'laugh'] },
      { emoji: '😂', keywords: ['tears', 'joy', 'laugh'] },
      { emoji: '🙂', keywords: ['slight', 'smile'] },
      { emoji: '🙃', keywords: ['upside', 'down', 'smile'] },
      { emoji: '🫠', keywords: ['melting', 'hot'] },
      { emoji: '😉', keywords: ['winking', 'wink'] },
      { emoji: '😊', keywords: ['smiling', 'blush', 'warm'] },
      { emoji: '😇', keywords: ['halo', 'angel', 'innocent'] },
      { emoji: '🥰', keywords: ['smiling', 'hearts', 'adore'] },
      { emoji: '😍', keywords: ['heart', 'eyes', 'love'] },
      { emoji: '🤩', keywords: ['star', 'struck', 'excited'] },
      { emoji: '😘', keywords: ['kiss', 'blow'] },
      { emoji: '😗', keywords: ['kissing'] },
      { emoji: '☺️', keywords: ['smiling', 'relaxed'] },
      { emoji: '😚', keywords: ['kissing', 'closed', 'eyes'] },
      { emoji: '😙', keywords: ['kissing', 'smiling', 'eyes'] },
      { emoji: '🥲', keywords: ['smiling', 'tear'] },
      { emoji: '😋', keywords: ['savoring', 'yum', 'tongue'] },
      { emoji: '😛', keywords: ['tongue'] },
      { emoji: '😜', keywords: ['winking', 'tongue', 'silly'] },
      { emoji: '🤪', keywords: ['zany', 'crazy'] },
      { emoji: '😝', keywords: ['squinting', 'tongue'] },
      { emoji: '🤑', keywords: ['money', 'rich', 'dollar'] },
      { emoji: '🤗', keywords: ['hugging', 'hug'] },
      { emoji: '🤭', keywords: ['hand', 'mouth', 'oops'] },
      { emoji: '🫢', keywords: ['open', 'hand', 'mouth'] },
      { emoji: '🫣', keywords: ['peeking', 'shy'] },
      { emoji: '🤫', keywords: ['shush', 'quiet', 'shh'] },
      { emoji: '🤔', keywords: ['thinking', 'hmm', 'wonder'] },
      { emoji: '🫡', keywords: ['saluting', 'salute', 'respect'] },
      { emoji: '🤐', keywords: ['zipper', 'mouth', 'quiet'] },
      { emoji: '🤨', keywords: ['raised', 'eyebrow', 'skeptical'] },
      { emoji: '😐', keywords: ['neutral', 'face'] },
      { emoji: '😑', keywords: ['expressionless', 'blank'] },
      { emoji: '😶', keywords: ['no', 'mouth', 'speechless'] },
      { emoji: '🫥', keywords: ['dotted', 'line', 'hidden'] },
      { emoji: '😏', keywords: ['smirk', 'sly'] },
      { emoji: '😒', keywords: ['unamused', 'meh'] },
      { emoji: '🙄', keywords: ['eye', 'roll'] },
      { emoji: '😬', keywords: ['grimace', 'awkward'] },
      { emoji: '🤥', keywords: ['lying', 'pinocchio'] },
      { emoji: '🫨', keywords: ['shaking', 'shock'] },
      { emoji: '😌', keywords: ['relieved', 'peaceful'] },
      { emoji: '😔', keywords: ['pensive', 'sad'] },
      { emoji: '😪', keywords: ['sleepy', 'tired'] },
      { emoji: '🤤', keywords: ['drooling', 'drool'] },
      { emoji: '😴', keywords: ['sleeping', 'zzz'] },
      { emoji: '😷', keywords: ['mask', 'sick'] },
      { emoji: '🤒', keywords: ['thermometer', 'sick', 'fever'] },
      { emoji: '🤕', keywords: ['bandage', 'hurt', 'injury'] },
      { emoji: '🤢', keywords: ['nauseated', 'sick', 'green'] },
      { emoji: '🤮', keywords: ['vomit', 'sick'] },
      { emoji: '🤧', keywords: ['sneeze', 'tissue'] },
      { emoji: '🥵', keywords: ['hot', 'sweating'] },
      { emoji: '🥶', keywords: ['cold', 'freezing'] },
      { emoji: '🥴', keywords: ['woozy', 'dizzy', 'drunk'] },
      { emoji: '😵', keywords: ['knocked', 'out'] },
      { emoji: '😵‍💫', keywords: ['spiral', 'eyes'] },
      { emoji: '🤯', keywords: ['exploding', 'mind', 'blown'] },
      { emoji: '🤠', keywords: ['cowboy', 'hat'] },
      { emoji: '🥳', keywords: ['party', 'celebrate', 'birthday'] },
      { emoji: '🥸', keywords: ['disguised', 'mustache'] },
      { emoji: '😎', keywords: ['cool', 'sunglasses'] },
      { emoji: '🤓', keywords: ['nerd', 'glasses'] },
      { emoji: '🧐', keywords: ['monocle', 'inspect'] },
      { emoji: '😕', keywords: ['confused'] },
      { emoji: '🫤', keywords: ['diagonal', 'mouth'] },
      { emoji: '😟', keywords: ['worried'] },
      { emoji: '🙁', keywords: ['slight', 'frown'] },
      { emoji: '☹️', keywords: ['frown', 'frowning'] },
      { emoji: '😮', keywords: ['open', 'mouth', 'surprise'] },
      { emoji: '😯', keywords: ['hushed'] },
      { emoji: '😲', keywords: ['astonished'] },
      { emoji: '😳', keywords: ['flushed', 'blush'] },
      { emoji: '🥺', keywords: ['pleading', 'puppy', 'eyes'] },
      { emoji: '🥹', keywords: ['holding', 'tears'] },
      { emoji: '😦', keywords: ['frowning', 'open', 'mouth'] },
      { emoji: '😧', keywords: ['anguished'] },
      { emoji: '😨', keywords: ['fearful', 'scared'] },
      { emoji: '😰', keywords: ['anxious', 'sweat'] },
      { emoji: '😥', keywords: ['sad', 'relieved'] },
      { emoji: '😢', keywords: ['crying', 'tear'] },
      { emoji: '😭', keywords: ['loudly', 'crying', 'sob'] },
      { emoji: '😱', keywords: ['scream', 'shock', 'fear'] },
      { emoji: '😖', keywords: ['confounded'] },
      { emoji: '😣', keywords: ['persevering'] },
      { emoji: '😞', keywords: ['disappointed'] },
      { emoji: '😓', keywords: ['downcast', 'sweat'] },
      { emoji: '😩', keywords: ['weary'] },
      { emoji: '😫', keywords: ['tired'] },
      { emoji: '🥱', keywords: ['yawning', 'bored'] },
      { emoji: '😤', keywords: ['huff', 'steam', 'angry'] },
      { emoji: '😡', keywords: ['pouting', 'red', 'angry'] },
      { emoji: '😠', keywords: ['angry'] },
      { emoji: '🤬', keywords: ['cursing', 'symbols', 'swear'] },
      { emoji: '😈', keywords: ['smiling', 'devil'] },
      { emoji: '👿', keywords: ['angry', 'devil'] },
      { emoji: '💀', keywords: ['skull', 'death'] },
      { emoji: '☠️', keywords: ['skull', 'crossbones'] },
      { emoji: '💩', keywords: ['poo', 'poop'] },
      { emoji: '🤡', keywords: ['clown'] },
      { emoji: '👹', keywords: ['ogre'] },
      { emoji: '👺', keywords: ['goblin'] },
      { emoji: '👻', keywords: ['ghost'] },
      { emoji: '👽', keywords: ['alien'] },
      { emoji: '👾', keywords: ['monster', 'alien', 'pixel'] },
      { emoji: '🤖', keywords: ['robot'] },
      { emoji: '😺', keywords: ['grinning', 'cat'] },
      { emoji: '😸', keywords: ['cat', 'smile'] },
      { emoji: '😹', keywords: ['cat', 'tears', 'joy'] },
      { emoji: '😻', keywords: ['cat', 'heart', 'eyes'] },
      { emoji: '😼', keywords: ['cat', 'wry'] },
      { emoji: '😽', keywords: ['cat', 'kiss'] },
      { emoji: '🙀', keywords: ['weary', 'cat'] },
      { emoji: '😿', keywords: ['crying', 'cat'] },
      { emoji: '😾', keywords: ['pouting', 'cat'] },
      { emoji: '🙈', keywords: ['see', 'no', 'evil', 'monkey'] },
      { emoji: '🙉', keywords: ['hear', 'no', 'evil', 'monkey'] },
      { emoji: '🙊', keywords: ['speak', 'no', 'evil', 'monkey'] },
      { emoji: '❤️', keywords: ['red', 'heart', 'love'] },
      { emoji: '🧡', keywords: ['orange', 'heart'] },
      { emoji: '💛', keywords: ['yellow', 'heart'] },
      { emoji: '💚', keywords: ['green', 'heart'] },
      { emoji: '💙', keywords: ['blue', 'heart'] },
      { emoji: '💜', keywords: ['purple', 'heart'] },
      { emoji: '🤎', keywords: ['brown', 'heart'] },
      { emoji: '🖤', keywords: ['black', 'heart'] },
      { emoji: '🤍', keywords: ['white', 'heart'] },
      { emoji: '❤️‍🔥', keywords: ['heart', 'fire', 'burning'] },
      { emoji: '❤️‍🩹', keywords: ['mending', 'heart', 'healing'] },
      { emoji: '💖', keywords: ['sparkling', 'heart'] },
      { emoji: '💕', keywords: ['two', 'hearts'] },
      { emoji: '💞', keywords: ['revolving', 'hearts'] },
      { emoji: '💓', keywords: ['beating', 'heart'] },
      { emoji: '💗', keywords: ['growing', 'heart'] },
      { emoji: '💘', keywords: ['heart', 'arrow', 'cupid'] },
      { emoji: '💝', keywords: ['heart', 'ribbon', 'gift'] },
      { emoji: '💟', keywords: ['heart', 'decoration'] },
      { emoji: '♥️', keywords: ['heart', 'suit'] },
      { emoji: '❣️', keywords: ['heart', 'exclamation'] },
      { emoji: '💔', keywords: ['broken', 'heart'] },
      { emoji: '💋', keywords: ['kiss', 'mark'] },
      { emoji: '💌', keywords: ['love', 'letter'] },
      { emoji: '💤', keywords: ['zzz', 'sleep'] },
      { emoji: '💢', keywords: ['anger', 'symbol'] },
      { emoji: '💥', keywords: ['collision', 'boom'] },
      { emoji: '💫', keywords: ['dizzy', 'star'] },
      { emoji: '💦', keywords: ['sweat', 'drops'] },
      { emoji: '💨', keywords: ['dash', 'wind'] },
      { emoji: '🕳️', keywords: ['hole'] },
      { emoji: '💬', keywords: ['speech', 'balloon'] },
      { emoji: '👁️‍🗨️', keywords: ['eye', 'speech'] },
      { emoji: '🗨️', keywords: ['left', 'speech', 'bubble'] },
      { emoji: '🗯️', keywords: ['right', 'anger', 'bubble'] },
      { emoji: '💭', keywords: ['thought', 'bubble'] },
    ],
  },
  {
    id: 'people',
    label: 'People & Body',
    icon: '👋',
    emojis: [
      { emoji: '👋', keywords: ['wave', 'hi', 'hello'] },
      { emoji: '🤚', keywords: ['raised', 'back', 'hand'] },
      { emoji: '🖐️', keywords: ['hand', 'fingers', 'splayed'] },
      { emoji: '✋', keywords: ['raised', 'hand', 'stop'] },
      { emoji: '🖖', keywords: ['vulcan', 'salute'] },
      { emoji: '🫱', keywords: ['rightwards', 'hand'] },
      { emoji: '🫲', keywords: ['leftwards', 'hand'] },
      { emoji: '🫳', keywords: ['palm', 'down'] },
      { emoji: '🫴', keywords: ['palm', 'up'] },
      { emoji: '🫷', keywords: ['leftwards', 'pushing'] },
      { emoji: '🫸', keywords: ['rightwards', 'pushing'] },
      { emoji: '👌', keywords: ['ok', 'okay'] },
      { emoji: '🤌', keywords: ['pinched', 'fingers'] },
      { emoji: '🤏', keywords: ['pinching', 'small'] },
      { emoji: '✌️', keywords: ['victory', 'peace'] },
      { emoji: '🤞', keywords: ['crossed', 'fingers', 'luck'] },
      { emoji: '🫰', keywords: ['heart', 'fingers'] },
      { emoji: '🤟', keywords: ['love', 'you', 'gesture'] },
      { emoji: '🤘', keywords: ['rock', 'horns', 'sign'] },
      { emoji: '🤙', keywords: ['call', 'me', 'hang', 'loose'] },
      { emoji: '👈', keywords: ['point', 'left'] },
      { emoji: '👉', keywords: ['point', 'right'] },
      { emoji: '👆', keywords: ['point', 'up'] },
      { emoji: '🖕', keywords: ['flip', 'off', 'middle', 'finger', 'rude', 'fuck'] },
      { emoji: '👇', keywords: ['point', 'down'] },
      { emoji: '☝️', keywords: ['index', 'up'] },
      { emoji: '🫵', keywords: ['point', 'viewer', 'you'] },
      { emoji: '👍', keywords: ['thumbs', 'up', 'yes'] },
      { emoji: '👎', keywords: ['thumbs', 'down', 'no'] },
      { emoji: '✊', keywords: ['raised', 'fist'] },
      { emoji: '👊', keywords: ['oncoming', 'fist', 'bump'] },
      { emoji: '🤛', keywords: ['left', 'fist'] },
      { emoji: '🤜', keywords: ['right', 'fist'] },
      { emoji: '👏', keywords: ['clap', 'applause'] },
      { emoji: '🙌', keywords: ['raising', 'hands', 'praise'] },
      { emoji: '🫶', keywords: ['heart', 'hands'] },
      { emoji: '👐', keywords: ['open', 'hands'] },
      { emoji: '🤲', keywords: ['palms', 'up', 'together'] },
      { emoji: '🤝', keywords: ['handshake', 'deal'] },
      { emoji: '🙏', keywords: ['folded', 'hands', 'pray', 'thanks'] },
      { emoji: '✍️', keywords: ['writing', 'hand'] },
      { emoji: '💅', keywords: ['nail', 'polish'] },
      { emoji: '🤳', keywords: ['selfie'] },
      { emoji: '💪', keywords: ['flexed', 'biceps', 'strong'] },
      { emoji: '🦾', keywords: ['mechanical', 'arm'] },
      { emoji: '🦿', keywords: ['mechanical', 'leg'] },
      { emoji: '🦵', keywords: ['leg'] },
      { emoji: '🦶', keywords: ['foot'] },
      { emoji: '👂', keywords: ['ear'] },
      { emoji: '🦻', keywords: ['ear', 'hearing', 'aid'] },
      { emoji: '👃', keywords: ['nose'] },
      { emoji: '🧠', keywords: ['brain'] },
      { emoji: '🫀', keywords: ['anatomical', 'heart'] },
      { emoji: '🫁', keywords: ['lungs'] },
      { emoji: '🦷', keywords: ['tooth'] },
      { emoji: '🦴', keywords: ['bone'] },
      { emoji: '👀', keywords: ['eyes'] },
      { emoji: '👁️', keywords: ['eye'] },
      { emoji: '👅', keywords: ['tongue'] },
      { emoji: '👄', keywords: ['mouth', 'lips'] },
      { emoji: '🫦', keywords: ['biting', 'lip'] },
      { emoji: '👶', keywords: ['baby'] },
      { emoji: '🧒', keywords: ['child'] },
      { emoji: '👦', keywords: ['boy'] },
      { emoji: '👧', keywords: ['girl'] },
      { emoji: '🧑', keywords: ['person'] },
      { emoji: '👨', keywords: ['man'] },
      { emoji: '🧔', keywords: ['beard', 'person'] },
      { emoji: '👩', keywords: ['woman'] },
      { emoji: '🧓', keywords: ['older', 'person'] },
      { emoji: '👴', keywords: ['old', 'man', 'grandpa'] },
      { emoji: '👵', keywords: ['old', 'woman', 'grandma'] },
      { emoji: '👮', keywords: ['police', 'officer'] },
      { emoji: '🕵️', keywords: ['detective', 'spy'] },
      { emoji: '💂', keywords: ['guard'] },
      { emoji: '🥷', keywords: ['ninja'] },
      { emoji: '👷', keywords: ['construction', 'worker'] },
      { emoji: '🫅', keywords: ['crown', 'royalty'] },
      { emoji: '🤴', keywords: ['prince'] },
      { emoji: '👸', keywords: ['princess'] },
      { emoji: '👳', keywords: ['turban'] },
      { emoji: '🧕', keywords: ['headscarf'] },
      { emoji: '🤵', keywords: ['tuxedo'] },
      { emoji: '👰', keywords: ['bride', 'veil'] },
      { emoji: '🤰', keywords: ['pregnant', 'woman'] },
      { emoji: '🤱', keywords: ['breastfeeding'] },
      { emoji: '👼', keywords: ['baby', 'angel'] },
      { emoji: '🎅', keywords: ['santa', 'claus'] },
      { emoji: '🤶', keywords: ['mrs', 'claus'] },
      { emoji: '🧙', keywords: ['mage', 'wizard'] },
      { emoji: '🧚', keywords: ['fairy'] },
      { emoji: '🧛', keywords: ['vampire'] },
      { emoji: '🧜', keywords: ['merperson', 'mermaid'] },
      { emoji: '🧝', keywords: ['elf'] },
      { emoji: '🧞', keywords: ['genie'] },
      { emoji: '🧟', keywords: ['zombie'] },
      { emoji: '💆', keywords: ['face', 'massage'] },
      { emoji: '💇', keywords: ['haircut'] },
      { emoji: '🚶', keywords: ['walking'] },
      { emoji: '🧍', keywords: ['standing'] },
      { emoji: '🧎', keywords: ['kneeling'] },
      { emoji: '🏃', keywords: ['running'] },
      { emoji: '💃', keywords: ['dancer', 'woman'] },
      { emoji: '🕺', keywords: ['dancer', 'man'] },
      { emoji: '🕴️', keywords: ['suspended', 'suit'] },
      { emoji: '👯', keywords: ['bunny', 'ears', 'dancers'] },
      { emoji: '🧖', keywords: ['sauna', 'steamy'] },
      { emoji: '🧗', keywords: ['climbing'] },
      { emoji: '🤺', keywords: ['fencer'] },
      { emoji: '🏇', keywords: ['horse', 'racing'] },
      { emoji: '⛷️', keywords: ['skier'] },
      { emoji: '🏂', keywords: ['snowboarder'] },
      { emoji: '🏌️', keywords: ['golf', 'golfer'] },
      { emoji: '🏄', keywords: ['surfer', 'surfing'] },
      { emoji: '🚣', keywords: ['rowing', 'boat'] },
      { emoji: '🏊', keywords: ['swimming'] },
      { emoji: '⛹️', keywords: ['bouncing', 'ball'] },
      { emoji: '🏋️', keywords: ['weight', 'lifting'] },
      { emoji: '🚴', keywords: ['biking', 'cyclist'] },
      { emoji: '🚵', keywords: ['mountain', 'biking'] },
      { emoji: '🤸', keywords: ['cartwheel'] },
      { emoji: '🤼', keywords: ['wrestling'] },
      { emoji: '🤽', keywords: ['water', 'polo'] },
      { emoji: '🤾', keywords: ['handball'] },
      { emoji: '🤹', keywords: ['juggling'] },
      { emoji: '🧘', keywords: ['lotus', 'meditation', 'yoga'] },
      { emoji: '👪', keywords: ['family'] },
      { emoji: '🧑‍🤝‍🧑', keywords: ['people', 'holding', 'hands'] },
      { emoji: '👭', keywords: ['women', 'holding', 'hands'] },
      { emoji: '👫', keywords: ['woman', 'man', 'holding'] },
      { emoji: '👬', keywords: ['men', 'holding', 'hands'] },
      { emoji: '💏', keywords: ['kiss'] },
      { emoji: '💑', keywords: ['couple', 'heart'] },
    ],
  },
  {
    id: 'nature',
    label: 'Animals & Nature',
    icon: '🐾',
    emojis: [
      { emoji: '🐶', keywords: ['dog', 'puppy'] },
      { emoji: '🐱', keywords: ['cat', 'kitten'] },
      { emoji: '🐭', keywords: ['mouse'] },
      { emoji: '🐹', keywords: ['hamster'] },
      { emoji: '🐰', keywords: ['rabbit', 'bunny'] },
      { emoji: '🦊', keywords: ['fox'] },
      { emoji: '🐻', keywords: ['bear'] },
      { emoji: '🐼', keywords: ['panda'] },
      { emoji: '🐻‍❄️', keywords: ['polar', 'bear'] },
      { emoji: '🐨', keywords: ['koala'] },
      { emoji: '🐯', keywords: ['tiger', 'face'] },
      { emoji: '🦁', keywords: ['lion'] },
      { emoji: '🐮', keywords: ['cow', 'face'] },
      { emoji: '🐷', keywords: ['pig'] },
      { emoji: '🐽', keywords: ['pig', 'nose'] },
      { emoji: '🐸', keywords: ['frog', 'pepe'] },
      { emoji: '🐵', keywords: ['monkey', 'face'] },
      { emoji: '🐒', keywords: ['monkey'] },
      { emoji: '🐔', keywords: ['chicken'] },
      { emoji: '🐧', keywords: ['penguin'] },
      { emoji: '🐦', keywords: ['bird'] },
      { emoji: '🐤', keywords: ['baby', 'chick'] },
      { emoji: '🐣', keywords: ['hatching', 'chick'] },
      { emoji: '🐥', keywords: ['front', 'chick'] },
      { emoji: '🦆', keywords: ['duck'] },
      { emoji: '🦅', keywords: ['eagle'] },
      { emoji: '🦉', keywords: ['owl'] },
      { emoji: '🦇', keywords: ['bat'] },
      { emoji: '🐺', keywords: ['wolf'] },
      { emoji: '🐗', keywords: ['boar'] },
      { emoji: '🐴', keywords: ['horse', 'face'] },
      { emoji: '🦄', keywords: ['unicorn'] },
      { emoji: '🐝', keywords: ['bee', 'honey'] },
      { emoji: '🪱', keywords: ['worm'] },
      { emoji: '🐛', keywords: ['bug', 'caterpillar'] },
      { emoji: '🦋', keywords: ['butterfly'] },
      { emoji: '🐌', keywords: ['snail'] },
      { emoji: '🐞', keywords: ['ladybug'] },
      { emoji: '🐜', keywords: ['ant'] },
      { emoji: '🪰', keywords: ['fly'] },
      { emoji: '🪲', keywords: ['beetle'] },
      { emoji: '🪳', keywords: ['cockroach'] },
      { emoji: '🦟', keywords: ['mosquito'] },
      { emoji: '🦗', keywords: ['cricket'] },
      { emoji: '🕷️', keywords: ['spider'] },
      { emoji: '🕸️', keywords: ['spider', 'web'] },
      { emoji: '🦂', keywords: ['scorpion'] },
      { emoji: '🐢', keywords: ['turtle'] },
      { emoji: '🐍', keywords: ['snake'] },
      { emoji: '🦎', keywords: ['lizard'] },
      { emoji: '🦖', keywords: ['t-rex', 'dinosaur'] },
      { emoji: '🦕', keywords: ['sauropod', 'dinosaur'] },
      { emoji: '🐙', keywords: ['octopus'] },
      { emoji: '🦑', keywords: ['squid'] },
      { emoji: '🦐', keywords: ['shrimp'] },
      { emoji: '🦞', keywords: ['lobster'] },
      { emoji: '🦀', keywords: ['crab'] },
      { emoji: '🐡', keywords: ['blowfish'] },
      { emoji: '🐠', keywords: ['tropical', 'fish'] },
      { emoji: '🐟', keywords: ['fish'] },
      { emoji: '🐬', keywords: ['dolphin'] },
      { emoji: '🐳', keywords: ['spouting', 'whale'] },
      { emoji: '🐋', keywords: ['whale'] },
      { emoji: '🦈', keywords: ['shark'] },
      { emoji: '🦭', keywords: ['seal'] },
      { emoji: '🐊', keywords: ['crocodile', 'alligator'] },
      { emoji: '🐅', keywords: ['tiger'] },
      { emoji: '🐆', keywords: ['leopard'] },
      { emoji: '🦓', keywords: ['zebra'] },
      { emoji: '🦧', keywords: ['orangutan'] },
      { emoji: '🐘', keywords: ['elephant'] },
      { emoji: '🦣', keywords: ['mammoth'] },
      { emoji: '🦛', keywords: ['hippopotamus'] },
      { emoji: '🦏', keywords: ['rhinoceros'] },
      { emoji: '🐪', keywords: ['camel'] },
      { emoji: '🐫', keywords: ['two', 'hump', 'camel'] },
      { emoji: '🦒', keywords: ['giraffe'] },
      { emoji: '🦘', keywords: ['kangaroo'] },
      { emoji: '🦬', keywords: ['bison'] },
      { emoji: '🐃', keywords: ['water', 'buffalo'] },
      { emoji: '🐂', keywords: ['ox'] },
      { emoji: '🐄', keywords: ['cow'] },
      { emoji: '🐎', keywords: ['horse'] },
      { emoji: '🐖', keywords: ['pig'] },
      { emoji: '🐏', keywords: ['ram'] },
      { emoji: '🐑', keywords: ['ewe', 'sheep'] },
      { emoji: '🦙', keywords: ['llama'] },
      { emoji: '🐐', keywords: ['goat'] },
      { emoji: '🦌', keywords: ['deer'] },
      { emoji: '🐕', keywords: ['dog'] },
      { emoji: '🐩', keywords: ['poodle'] },
      { emoji: '🦮', keywords: ['guide', 'dog'] },
      { emoji: '🐈', keywords: ['cat'] },
      { emoji: '🐓', keywords: ['rooster'] },
      { emoji: '🦃', keywords: ['turkey'] },
      { emoji: '🦚', keywords: ['peacock'] },
      { emoji: '🦜', keywords: ['parrot'] },
      { emoji: '🦢', keywords: ['swan'] },
      { emoji: '🦩', keywords: ['flamingo'] },
      { emoji: '🕊️', keywords: ['dove'] },
      { emoji: '🐇', keywords: ['rabbit'] },
      { emoji: '🦝', keywords: ['raccoon'] },
      { emoji: '🦨', keywords: ['skunk'] },
      { emoji: '🦫', keywords: ['beaver'] },
      { emoji: '🦦', keywords: ['otter'] },
      { emoji: '🦥', keywords: ['sloth'] },
      { emoji: '🐁', keywords: ['mouse'] },
      { emoji: '🐀', keywords: ['rat'] },
      { emoji: '🐿️', keywords: ['chipmunk'] },
      { emoji: '🦔', keywords: ['hedgehog'] },
      { emoji: '🐉', keywords: ['dragon'] },
      { emoji: '🐲', keywords: ['dragon', 'face'] },
      { emoji: '🌵', keywords: ['cactus'] },
      { emoji: '🎄', keywords: ['christmas', 'tree'] },
      { emoji: '🌲', keywords: ['evergreen', 'tree'] },
      { emoji: '🌳', keywords: ['deciduous', 'tree'] },
      { emoji: '🌴', keywords: ['palm', 'tree'] },
      { emoji: '🪵', keywords: ['wood', 'log'] },
      { emoji: '🌱', keywords: ['seedling'] },
      { emoji: '🌿', keywords: ['herb'] },
      { emoji: '☘️', keywords: ['shamrock'] },
      { emoji: '🍀', keywords: ['four', 'leaf', 'clover', 'luck'] },
      { emoji: '🎍', keywords: ['pine', 'decoration'] },
      { emoji: '🪴', keywords: ['potted', 'plant'] },
      { emoji: '🎋', keywords: ['tanabata', 'tree'] },
      { emoji: '🍃', keywords: ['leaf', 'fluttering'] },
      { emoji: '🍂', keywords: ['fallen', 'leaf'] },
      { emoji: '🍁', keywords: ['maple', 'leaf'] },
      { emoji: '🍄', keywords: ['mushroom'] },
      { emoji: '🐚', keywords: ['shell'] },
      { emoji: '🪸', keywords: ['coral'] },
      { emoji: '🪨', keywords: ['rock'] },
      { emoji: '🌾', keywords: ['wheat'] },
      { emoji: '💐', keywords: ['bouquet'] },
      { emoji: '🌷', keywords: ['tulip'] },
      { emoji: '🌹', keywords: ['rose'] },
      { emoji: '🥀', keywords: ['wilted', 'flower'] },
      { emoji: '🌺', keywords: ['hibiscus'] },
      { emoji: '🌸', keywords: ['cherry', 'blossom'] },
      { emoji: '🌼', keywords: ['blossom', 'daisy'] },
      { emoji: '🌻', keywords: ['sunflower'] },
      { emoji: '🌞', keywords: ['sun', 'face'] },
      { emoji: '🌝', keywords: ['full', 'moon', 'face'] },
      { emoji: '🌛', keywords: ['first', 'quarter', 'face'] },
      { emoji: '🌜', keywords: ['last', 'quarter', 'face'] },
      { emoji: '🌚', keywords: ['new', 'moon', 'face'] },
      { emoji: '🌕', keywords: ['full', 'moon'] },
      { emoji: '🌖', keywords: ['waning', 'gibbous'] },
      { emoji: '🌗', keywords: ['last', 'quarter', 'moon'] },
      { emoji: '🌘', keywords: ['waning', 'crescent'] },
      { emoji: '🌑', keywords: ['new', 'moon'] },
      { emoji: '🌒', keywords: ['waxing', 'crescent'] },
      { emoji: '🌓', keywords: ['first', 'quarter'] },
      { emoji: '🌔', keywords: ['waxing', 'gibbous'] },
      { emoji: '🌙', keywords: ['crescent', 'moon'] },
      { emoji: '🌎', keywords: ['americas', 'earth'] },
      { emoji: '🌍', keywords: ['africa', 'earth'] },
      { emoji: '🌏', keywords: ['asia', 'earth'] },
      { emoji: '🪐', keywords: ['ringed', 'planet'] },
      { emoji: '⭐', keywords: ['star'] },
      { emoji: '🌟', keywords: ['glowing', 'star'] },
      { emoji: '✨', keywords: ['sparkles'] },
      { emoji: '☄️', keywords: ['comet'] },
      { emoji: '🔥', keywords: ['fire'] },
      { emoji: '🌪️', keywords: ['tornado'] },
      { emoji: '🌈', keywords: ['rainbow'] },
      { emoji: '☀️', keywords: ['sun'] },
      { emoji: '🌤️', keywords: ['sun', 'small', 'cloud'] },
      { emoji: '⛅', keywords: ['sun', 'cloud'] },
      { emoji: '🌥️', keywords: ['cloud', 'sun'] },
      { emoji: '☁️', keywords: ['cloud'] },
      { emoji: '🌦️', keywords: ['sun', 'rain'] },
      { emoji: '🌧️', keywords: ['cloud', 'rain'] },
      { emoji: '⛈️', keywords: ['thunder', 'storm'] },
      { emoji: '🌩️', keywords: ['cloud', 'lightning'] },
      { emoji: '🌨️', keywords: ['cloud', 'snow'] },
      { emoji: '❄️', keywords: ['snowflake'] },
      { emoji: '☃️', keywords: ['snowman'] },
      { emoji: '⛄', keywords: ['snowman', 'no', 'snow'] },
      { emoji: '🌬️', keywords: ['wind', 'face'] },
      { emoji: '💧', keywords: ['droplet'] },
      { emoji: '🫧', keywords: ['bubbles'] },
      { emoji: '☔', keywords: ['umbrella', 'rain'] },
      { emoji: '☂️', keywords: ['umbrella'] },
      { emoji: '🌊', keywords: ['water', 'wave'] },
      { emoji: '🌫️', keywords: ['fog'] },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍎',
    emojis: [
      { emoji: '🍏', keywords: ['green', 'apple'] },
      { emoji: '🍎', keywords: ['red', 'apple'] },
      { emoji: '🍐', keywords: ['pear'] },
      { emoji: '🍊', keywords: ['tangerine', 'orange'] },
      { emoji: '🍋', keywords: ['lemon'] },
      { emoji: '🍌', keywords: ['banana'] },
      { emoji: '🍉', keywords: ['watermelon'] },
      { emoji: '🍇', keywords: ['grapes'] },
      { emoji: '🍓', keywords: ['strawberry'] },
      { emoji: '🫐', keywords: ['blueberries'] },
      { emoji: '🍈', keywords: ['melon'] },
      { emoji: '🍒', keywords: ['cherries'] },
      { emoji: '🍑', keywords: ['peach'] },
      { emoji: '🥭', keywords: ['mango'] },
      { emoji: '🍍', keywords: ['pineapple'] },
      { emoji: '🥥', keywords: ['coconut'] },
      { emoji: '🥝', keywords: ['kiwi'] },
      { emoji: '🍅', keywords: ['tomato'] },
      { emoji: '🍆', keywords: ['eggplant', 'aubergine'] },
      { emoji: '🥑', keywords: ['avocado'] },
      { emoji: '🥦', keywords: ['broccoli'] },
      { emoji: '🥬', keywords: ['leafy', 'green'] },
      { emoji: '🥒', keywords: ['cucumber'] },
      { emoji: '🌶️', keywords: ['hot', 'pepper'] },
      { emoji: '🫑', keywords: ['bell', 'pepper'] },
      { emoji: '🌽', keywords: ['corn'] },
      { emoji: '🥕', keywords: ['carrot'] },
      { emoji: '🫒', keywords: ['olive'] },
      { emoji: '🧄', keywords: ['garlic'] },
      { emoji: '🧅', keywords: ['onion'] },
      { emoji: '🥔', keywords: ['potato'] },
      { emoji: '🍠', keywords: ['roasted', 'sweet', 'potato'] },
      { emoji: '🫘', keywords: ['beans'] },
      { emoji: '🌰', keywords: ['chestnut'] },
      { emoji: '🥐', keywords: ['croissant'] },
      { emoji: '🥯', keywords: ['bagel'] },
      { emoji: '🍞', keywords: ['bread'] },
      { emoji: '🥖', keywords: ['baguette'] },
      { emoji: '🧀', keywords: ['cheese'] },
      { emoji: '🥚', keywords: ['egg'] },
      { emoji: '🍳', keywords: ['cooking', 'fried'] },
      { emoji: '🧈', keywords: ['butter'] },
      { emoji: '🥞', keywords: ['pancakes'] },
      { emoji: '🧇', keywords: ['waffle'] },
      { emoji: '🥓', keywords: ['bacon'] },
      { emoji: '🥩', keywords: ['cut', 'meat', 'steak'] },
      { emoji: '🍗', keywords: ['poultry', 'leg'] },
      { emoji: '🍖', keywords: ['meat', 'bone'] },
      { emoji: '🌭', keywords: ['hot', 'dog'] },
      { emoji: '🍔', keywords: ['hamburger', 'burger'] },
      { emoji: '🍟', keywords: ['french', 'fries'] },
      { emoji: '🍕', keywords: ['pizza'] },
      { emoji: '🥪', keywords: ['sandwich'] },
      { emoji: '🥙', keywords: ['stuffed', 'flatbread'] },
      { emoji: '🧆', keywords: ['falafel'] },
      { emoji: '🌮', keywords: ['taco'] },
      { emoji: '🌯', keywords: ['burrito'] },
      { emoji: '🫔', keywords: ['tamale'] },
      { emoji: '🥗', keywords: ['green', 'salad'] },
      { emoji: '🥘', keywords: ['paella'] },
      { emoji: '🫕', keywords: ['fondue'] },
      { emoji: '🥫', keywords: ['canned', 'food'] },
      { emoji: '🍝', keywords: ['spaghetti'] },
      { emoji: '🍜', keywords: ['steaming', 'bowl', 'ramen'] },
      { emoji: '🍲', keywords: ['pot', 'food'] },
      { emoji: '🍛', keywords: ['curry', 'rice'] },
      { emoji: '🍣', keywords: ['sushi'] },
      { emoji: '🍱', keywords: ['bento'] },
      { emoji: '🥟', keywords: ['dumpling'] },
      { emoji: '🦪', keywords: ['oyster'] },
      { emoji: '🍤', keywords: ['fried', 'shrimp'] },
      { emoji: '🍙', keywords: ['rice', 'ball'] },
      { emoji: '🍚', keywords: ['cooked', 'rice'] },
      { emoji: '🍘', keywords: ['rice', 'cracker'] },
      { emoji: '🍥', keywords: ['fish', 'cake'] },
      { emoji: '🥮', keywords: ['moon', 'cake'] },
      { emoji: '🍢', keywords: ['oden'] },
      { emoji: '🍡', keywords: ['dango'] },
      { emoji: '🍧', keywords: ['shaved', 'ice'] },
      { emoji: '🍨', keywords: ['ice', 'cream'] },
      { emoji: '🍦', keywords: ['soft', 'ice', 'cream'] },
      { emoji: '🥧', keywords: ['pie'] },
      { emoji: '🧁', keywords: ['cupcake'] },
      { emoji: '🍰', keywords: ['shortcake'] },
      { emoji: '🎂', keywords: ['birthday', 'cake'] },
      { emoji: '🍮', keywords: ['custard'] },
      { emoji: '🍭', keywords: ['lollipop'] },
      { emoji: '🍬', keywords: ['candy'] },
      { emoji: '🍫', keywords: ['chocolate'] },
      { emoji: '🍿', keywords: ['popcorn'] },
      { emoji: '🍩', keywords: ['doughnut'] },
      { emoji: '🍪', keywords: ['cookie'] },
      { emoji: '🍯', keywords: ['honey'] },
      { emoji: '🥛', keywords: ['milk'] },
      { emoji: '🫗', keywords: ['pouring', 'liquid'] },
      { emoji: '☕', keywords: ['coffee'] },
      { emoji: '🍵', keywords: ['tea'] },
      { emoji: '🧉', keywords: ['mate'] },
      { emoji: '🍶', keywords: ['sake'] },
      { emoji: '🍾', keywords: ['champagne'] },
      { emoji: '🍷', keywords: ['wine', 'glass'] },
      { emoji: '🍸', keywords: ['cocktail'] },
      { emoji: '🍹', keywords: ['tropical', 'drink'] },
      { emoji: '🍺', keywords: ['beer'] },
      { emoji: '🍻', keywords: ['clinking', 'beers', 'cheers'] },
      { emoji: '🥂', keywords: ['clinking', 'glasses', 'toast'] },
      { emoji: '🥃', keywords: ['tumbler', 'whiskey'] },
      { emoji: '🫖', keywords: ['teapot'] },
      { emoji: '🥤', keywords: ['cup', 'straw'] },
      { emoji: '🧋', keywords: ['bubble', 'tea'] },
      { emoji: '🧃', keywords: ['juice', 'box'] },
      { emoji: '🧊', keywords: ['ice'] },
      { emoji: '🥢', keywords: ['chopsticks'] },
      { emoji: '🍴', keywords: ['fork', 'knife'] },
      { emoji: '🥄', keywords: ['spoon'] },
      { emoji: '🔪', keywords: ['kitchen', 'knife'] },
      { emoji: '🫙', keywords: ['jar'] },
      { emoji: '🏺', keywords: ['amphora'] },
      { emoji: '🍽️', keywords: ['plate', 'utensils'] },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '🚗',
    emojis: [
      { emoji: '🌐', keywords: ['globe', 'meridians'] },
      { emoji: '🗺️', keywords: ['world', 'map'] },
      { emoji: '🗾', keywords: ['japan'] },
      { emoji: '🧭', keywords: ['compass'] },
      { emoji: '🏔️', keywords: ['snow', 'mountain'] },
      { emoji: '⛰️', keywords: ['mountain'] },
      { emoji: '🗻', keywords: ['mount', 'fuji'] },
      { emoji: '🏕️', keywords: ['camping'] },
      { emoji: '🏖️', keywords: ['beach', 'umbrella'] },
      { emoji: '🏜️', keywords: ['desert'] },
      { emoji: '🏝️', keywords: ['desert', 'island'] },
      { emoji: '🏞️', keywords: ['national', 'park'] },
      { emoji: '🏟️', keywords: ['stadium'] },
      { emoji: '🏛️', keywords: ['classical', 'building'] },
      { emoji: '🏗️', keywords: ['construction'] },
      { emoji: '🧱', keywords: ['brick'] },
      { emoji: '🛖', keywords: ['hut'] },
      { emoji: '🏘️', keywords: ['houses'] },
      { emoji: '🏚️', keywords: ['derelict', 'house'] },
      { emoji: '🏠', keywords: ['house'] },
      { emoji: '🏡', keywords: ['home', 'garden'] },
      { emoji: '🏢', keywords: ['office', 'building'] },
      { emoji: '🏣', keywords: ['japanese', 'post'] },
      { emoji: '🏤', keywords: ['post', 'office'] },
      { emoji: '🏥', keywords: ['hospital'] },
      { emoji: '🏦', keywords: ['bank'] },
      { emoji: '🏨', keywords: ['hotel'] },
      { emoji: '🏩', keywords: ['love', 'hotel'] },
      { emoji: '🏪', keywords: ['convenience', 'store'] },
      { emoji: '🏫', keywords: ['school'] },
      { emoji: '🏬', keywords: ['department', 'store'] },
      { emoji: '🏭', keywords: ['factory'] },
      { emoji: '🏯', keywords: ['japanese', 'castle'] },
      { emoji: '🏰', keywords: ['castle'] },
      { emoji: '💒', keywords: ['wedding'] },
      { emoji: '🗼', keywords: ['tokyo', 'tower'] },
      { emoji: '🗽', keywords: ['statue', 'liberty'] },
      { emoji: '⛪', keywords: ['church'] },
      { emoji: '🕌', keywords: ['mosque'] },
      { emoji: '🛕', keywords: ['hindu', 'temple'] },
      { emoji: '🕍', keywords: ['synagogue'] },
      { emoji: '⛩️', keywords: ['shinto', 'shrine'] },
      { emoji: '🕋', keywords: ['kaaba'] },
      { emoji: '⛲', keywords: ['fountain'] },
      { emoji: '⛺', keywords: ['tent'] },
      { emoji: '🌁', keywords: ['foggy'] },
      { emoji: '🌃', keywords: ['night', 'stars'] },
      { emoji: '🏙️', keywords: ['cityscape'] },
      { emoji: '🌄', keywords: ['sunrise', 'mountains'] },
      { emoji: '🌅', keywords: ['sunrise'] },
      { emoji: '🌆', keywords: ['cityscape', 'dusk'] },
      { emoji: '🌇', keywords: ['sunset'] },
      { emoji: '🌉', keywords: ['bridge', 'night'] },
      { emoji: '♨️', keywords: ['hot', 'springs'] },
      { emoji: '🎠', keywords: ['carousel', 'horse'] },
      { emoji: '🛝', keywords: ['playground', 'slide'] },
      { emoji: '🎡', keywords: ['ferris', 'wheel'] },
      { emoji: '🎢', keywords: ['roller', 'coaster'] },
      { emoji: '💈', keywords: ['barber', 'pole'] },
      { emoji: '🎪', keywords: ['circus', 'tent'] },
      { emoji: '🚂', keywords: ['locomotive'] },
      { emoji: '🚃', keywords: ['railway', 'car'] },
      { emoji: '🚄', keywords: ['high', 'speed', 'train'] },
      { emoji: '🚅', keywords: ['bullet', 'train'] },
      { emoji: '🚆', keywords: ['train'] },
      { emoji: '🚇', keywords: ['metro'] },
      { emoji: '🚈', keywords: ['light', 'rail'] },
      { emoji: '🚉', keywords: ['station'] },
      { emoji: '🚊', keywords: ['tram'] },
      { emoji: '🚝', keywords: ['monorail'] },
      { emoji: '🚞', keywords: ['mountain', 'railway'] },
      { emoji: '🚋', keywords: ['tram', 'car'] },
      { emoji: '🚌', keywords: ['bus'] },
      { emoji: '🚍', keywords: ['oncoming', 'bus'] },
      { emoji: '🚎', keywords: ['trolleybus'] },
      { emoji: '🚐', keywords: ['minibus'] },
      { emoji: '🚑', keywords: ['ambulance'] },
      { emoji: '🚒', keywords: ['fire', 'engine'] },
      { emoji: '🚓', keywords: ['police', 'car'] },
      { emoji: '🚔', keywords: ['oncoming', 'police'] },
      { emoji: '🚕', keywords: ['taxi'] },
      { emoji: '🚖', keywords: ['oncoming', 'taxi'] },
      { emoji: '🚗', keywords: ['car', 'automobile'] },
      { emoji: '🚘', keywords: ['oncoming', 'car'] },
      { emoji: '🚙', keywords: ['sport', 'utility'] },
      { emoji: '🛻', keywords: ['pickup', 'truck'] },
      { emoji: '🚚', keywords: ['delivery', 'truck'] },
      { emoji: '🚛', keywords: ['articulated', 'lorry'] },
      { emoji: '🚜', keywords: ['tractor'] },
      { emoji: '🏎️', keywords: ['racing', 'car'] },
      { emoji: '🏍️', keywords: ['motorcycle'] },
      { emoji: '🛵', keywords: ['motor', 'scooter'] },
      { emoji: '🦽', keywords: ['manual', 'wheelchair'] },
      { emoji: '🦼', keywords: ['motorized', 'wheelchair'] },
      { emoji: '🛺', keywords: ['auto', 'rickshaw'] },
      { emoji: '🚲', keywords: ['bicycle'] },
      { emoji: '🛴', keywords: ['kick', 'scooter'] },
      { emoji: '🛹', keywords: ['skateboard'] },
      { emoji: '🛼', keywords: ['roller', 'skate'] },
      { emoji: '🚏', keywords: ['bus', 'stop'] },
      { emoji: '🛣️', keywords: ['motorway'] },
      { emoji: '🛤️', keywords: ['railway', 'track'] },
      { emoji: '🛢️', keywords: ['oil', 'drum'] },
      { emoji: '⛽', keywords: ['fuel', 'pump'] },
      { emoji: '🛞', keywords: ['wheel'] },
      { emoji: '🚨', keywords: ['police', 'light'] },
      { emoji: '🚥', keywords: ['horizontal', 'traffic'] },
      { emoji: '🚦', keywords: ['vertical', 'traffic'] },
      { emoji: '🛑', keywords: ['stop', 'sign'] },
      { emoji: '🚧', keywords: ['construction', 'sign'] },
      { emoji: '⚓', keywords: ['anchor'] },
      { emoji: '🛟', keywords: ['ring', 'buoy'] },
      { emoji: '⛵', keywords: ['sailboat'] },
      { emoji: '🛶', keywords: ['canoe'] },
      { emoji: '🚤', keywords: ['speedboat'] },
      { emoji: '🛥️', keywords: ['motor', 'boat'] },
      { emoji: '🛳️', keywords: ['passenger', 'ship'] },
      { emoji: '⛴️', keywords: ['ferry'] },
      { emoji: '🚢', keywords: ['ship'] },
      { emoji: '✈️', keywords: ['airplane'] },
      { emoji: '🛩️', keywords: ['small', 'airplane'] },
      { emoji: '🛫', keywords: ['takeoff'] },
      { emoji: '🛬', keywords: ['landing'] },
      { emoji: '🪂', keywords: ['parachute'] },
      { emoji: '💺', keywords: ['seat'] },
      { emoji: '🚁', keywords: ['helicopter'] },
      { emoji: '🚟', keywords: ['suspension', 'railway'] },
      { emoji: '🚠', keywords: ['mountain', 'cableway'] },
      { emoji: '🚡', keywords: ['aerial', 'tramway'] },
      { emoji: '🛰️', keywords: ['satellite'] },
      { emoji: '🛸', keywords: ['flying', 'saucer', 'ufo'] },
      { emoji: '🛎️', keywords: ['bellhop', 'bell'] },
      { emoji: '🧳', keywords: ['luggage'] },
      { emoji: '⌛', keywords: ['hourglass', 'done'] },
      { emoji: '⏳', keywords: ['hourglass', 'flowing'] },
      { emoji: '⌚', keywords: ['watch'] },
      { emoji: '⏰', keywords: ['alarm', 'clock'] },
      { emoji: '⏱️', keywords: ['stopwatch'] },
      { emoji: '⏲️', keywords: ['timer', 'clock'] },
      { emoji: '🕰️', keywords: ['mantelpiece', 'clock'] },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      { emoji: '🎃', keywords: ['pumpkin', 'halloween'] },
      { emoji: '🎆', keywords: ['fireworks'] },
      { emoji: '🎇', keywords: ['sparkler'] },
      { emoji: '🧨', keywords: ['firecracker'] },
      { emoji: '🎈', keywords: ['balloon'] },
      { emoji: '🎉', keywords: ['party', 'popper'] },
      { emoji: '🎊', keywords: ['confetti', 'ball'] },
      { emoji: '🎎', keywords: ['japanese', 'dolls'] },
      { emoji: '🎏', keywords: ['carp', 'streamer'] },
      { emoji: '🎐', keywords: ['wind', 'chime'] },
      { emoji: '🎑', keywords: ['moon', 'ceremony'] },
      { emoji: '🧧', keywords: ['red', 'envelope'] },
      { emoji: '🎀', keywords: ['ribbon'] },
      { emoji: '🎁', keywords: ['wrapped', 'gift', 'present'] },
      { emoji: '🎗️', keywords: ['reminder', 'ribbon'] },
      { emoji: '🎟️', keywords: ['admission', 'tickets'] },
      { emoji: '🎫', keywords: ['ticket'] },
      { emoji: '🎖️', keywords: ['military', 'medal'] },
      { emoji: '🏅', keywords: ['sports', 'medal'] },
      { emoji: '🥇', keywords: ['first', 'place', 'gold'] },
      { emoji: '🥈', keywords: ['second', 'place', 'silver'] },
      { emoji: '🥉', keywords: ['third', 'place', 'bronze'] },
      { emoji: '⚽', keywords: ['soccer', 'football'] },
      { emoji: '⚾', keywords: ['baseball'] },
      { emoji: '🥎', keywords: ['softball'] },
      { emoji: '🏀', keywords: ['basketball'] },
      { emoji: '🏐', keywords: ['volleyball'] },
      { emoji: '🏈', keywords: ['american', 'football'] },
      { emoji: '🏉', keywords: ['rugby'] },
      { emoji: '🎾', keywords: ['tennis'] },
      { emoji: '🥏', keywords: ['flying', 'disc'] },
      { emoji: '🎳', keywords: ['bowling'] },
      { emoji: '🏏', keywords: ['cricket', 'bat'] },
      { emoji: '🏑', keywords: ['field', 'hockey'] },
      { emoji: '🏒', keywords: ['ice', 'hockey'] },
      { emoji: '🥍', keywords: ['lacrosse'] },
      { emoji: '🏓', keywords: ['ping', 'pong'] },
      { emoji: '🏸', keywords: ['badminton'] },
      { emoji: '🥊', keywords: ['boxing', 'glove'] },
      { emoji: '🥋', keywords: ['martial', 'arts'] },
      { emoji: '🥅', keywords: ['goal', 'net'] },
      { emoji: '⛳', keywords: ['golf', 'hole'] },
      { emoji: '⛸️', keywords: ['ice', 'skate'] },
      { emoji: '🎣', keywords: ['fishing', 'pole'] },
      { emoji: '🤿', keywords: ['diving', 'mask'] },
      { emoji: '🎽', keywords: ['running', 'shirt'] },
      { emoji: '🎿', keywords: ['skis'] },
      { emoji: '🛷', keywords: ['sled'] },
      { emoji: '🥌', keywords: ['curling', 'stone'] },
      { emoji: '🎯', keywords: ['bullseye', 'dart'] },
      { emoji: '🪀', keywords: ['yo-yo'] },
      { emoji: '🪁', keywords: ['kite'] },
      { emoji: '🎱', keywords: ['pool', '8', 'ball'] },
      { emoji: '🔮', keywords: ['crystal', 'ball'] },
      { emoji: '🪄', keywords: ['magic', 'wand'] },
      { emoji: '🧿', keywords: ['nazar', 'amulet'] },
      { emoji: '🪬', keywords: ['hamsa'] },
      { emoji: '🎮', keywords: ['video', 'game'] },
      { emoji: '🕹️', keywords: ['joystick'] },
      { emoji: '🎰', keywords: ['slot', 'machine'] },
      { emoji: '🎲', keywords: ['dice'] },
      { emoji: '🧩', keywords: ['puzzle'] },
      { emoji: '🧸', keywords: ['teddy', 'bear'] },
      { emoji: '🪅', keywords: ['piñata'] },
      { emoji: '🪩', keywords: ['mirror', 'ball', 'disco'] },
      { emoji: '🪆', keywords: ['nesting', 'doll'] },
      { emoji: '♠️', keywords: ['spade', 'suit'] },
      { emoji: '♦️', keywords: ['diamond', 'suit'] },
      { emoji: '♣️', keywords: ['club', 'suit'] },
      { emoji: '♟️', keywords: ['chess', 'pawn'] },
      { emoji: '🃏', keywords: ['joker'] },
      { emoji: '🀄', keywords: ['mahjong'] },
      { emoji: '🎴', keywords: ['flower', 'cards'] },
      { emoji: '🎭', keywords: ['performing', 'arts'] },
      { emoji: '🖼️', keywords: ['framed', 'picture'] },
      { emoji: '🎨', keywords: ['artist', 'palette'] },
      { emoji: '🧵', keywords: ['thread'] },
      { emoji: '🪡', keywords: ['sewing', 'needle'] },
      { emoji: '🧶', keywords: ['yarn'] },
      { emoji: '🪢', keywords: ['knot'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { emoji: '👓', keywords: ['glasses'] },
      { emoji: '🕶️', keywords: ['sunglasses'] },
      { emoji: '🥽', keywords: ['goggles'] },
      { emoji: '🥼', keywords: ['lab', 'coat'] },
      { emoji: '🦺', keywords: ['safety', 'vest'] },
      { emoji: '👔', keywords: ['necktie'] },
      { emoji: '👕', keywords: ['t-shirt'] },
      { emoji: '👖', keywords: ['jeans'] },
      { emoji: '🧣', keywords: ['scarf'] },
      { emoji: '🧤', keywords: ['gloves'] },
      { emoji: '🧥', keywords: ['coat'] },
      { emoji: '🧦', keywords: ['socks'] },
      { emoji: '👗', keywords: ['dress'] },
      { emoji: '👘', keywords: ['kimono'] },
      { emoji: '🥻', keywords: ['sari'] },
      { emoji: '🩱', keywords: ['one', 'piece', 'swimsuit'] },
      { emoji: '🩲', keywords: ['briefs'] },
      { emoji: '🩳', keywords: ['shorts'] },
      { emoji: '👙', keywords: ['bikini'] },
      { emoji: '👚', keywords: ['womans', 'clothes'] },
      { emoji: '👛', keywords: ['purse'] },
      { emoji: '👜', keywords: ['handbag'] },
      { emoji: '👝', keywords: ['clutch', 'bag'] },
      { emoji: '🛍️', keywords: ['shopping', 'bags'] },
      { emoji: '🎒', keywords: ['backpack'] },
      { emoji: '🩴', keywords: ['thong', 'sandal'] },
      { emoji: '👞', keywords: ['mans', 'shoe'] },
      { emoji: '👟', keywords: ['running', 'shoe'] },
      { emoji: '🥾', keywords: ['hiking', 'boot'] },
      { emoji: '🥿', keywords: ['flat', 'shoe'] },
      { emoji: '👠', keywords: ['high', 'heel'] },
      { emoji: '👡', keywords: ['womans', 'sandal'] },
      { emoji: '🩰', keywords: ['ballet', 'shoes'] },
      { emoji: '👢', keywords: ['womans', 'boot'] },
      { emoji: '👑', keywords: ['crown'] },
      { emoji: '👒', keywords: ['womans', 'hat'] },
      { emoji: '🎩', keywords: ['top', 'hat'] },
      { emoji: '🎓', keywords: ['graduation', 'cap'] },
      { emoji: '🧢', keywords: ['billed', 'cap'] },
      { emoji: '🪖', keywords: ['military', 'helmet'] },
      { emoji: '⛑️', keywords: ['rescue', 'helmet'] },
      { emoji: '📿', keywords: ['prayer', 'beads'] },
      { emoji: '💄', keywords: ['lipstick'] },
      { emoji: '💍', keywords: ['ring'] },
      { emoji: '🔇', keywords: ['muted', 'speaker'] },
      { emoji: '🔈', keywords: ['speaker', 'low'] },
      { emoji: '🔉', keywords: ['speaker', 'medium'] },
      { emoji: '🔊', keywords: ['speaker', 'high', 'loud'] },
      { emoji: '📢', keywords: ['loudspeaker'] },
      { emoji: '📣', keywords: ['megaphone'] },
      { emoji: '📯', keywords: ['postal', 'horn'] },
      { emoji: '🔔', keywords: ['bell'] },
      { emoji: '🔕', keywords: ['bell', 'slash'] },
      { emoji: '🎼', keywords: ['musical', 'score'] },
      { emoji: '🎵', keywords: ['musical', 'note'] },
      { emoji: '🎶', keywords: ['musical', 'notes'] },
      { emoji: '🎙️', keywords: ['studio', 'microphone'] },
      { emoji: '🎚️', keywords: ['level', 'slider'] },
      { emoji: '🎛️', keywords: ['control', 'knobs'] },
      { emoji: '🎤', keywords: ['microphone'] },
      { emoji: '🎧', keywords: ['headphone'] },
      { emoji: '📻', keywords: ['radio'] },
      { emoji: '🎷', keywords: ['saxophone'] },
      { emoji: '🪗', keywords: ['accordion'] },
      { emoji: '🎸', keywords: ['guitar'] },
      { emoji: '🎹', keywords: ['piano'] },
      { emoji: '🎺', keywords: ['trumpet'] },
      { emoji: '🎻', keywords: ['violin'] },
      { emoji: '🪕', keywords: ['banjo'] },
      { emoji: '🥁', keywords: ['drum'] },
      { emoji: '📱', keywords: ['mobile', 'phone'] },
      { emoji: '📲', keywords: ['phone', 'arrow'] },
      { emoji: '☎️', keywords: ['telephone'] },
      { emoji: '📞', keywords: ['phone', 'receiver'] },
      { emoji: '📟', keywords: ['pager'] },
      { emoji: '📠', keywords: ['fax'] },
      { emoji: '🔋', keywords: ['battery'] },
      { emoji: '🪫', keywords: ['low', 'battery'] },
      { emoji: '🔌', keywords: ['plug'] },
      { emoji: '💻', keywords: ['laptop'] },
      { emoji: '🖥️', keywords: ['desktop', 'computer'] },
      { emoji: '🖨️', keywords: ['printer'] },
      { emoji: '⌨️', keywords: ['keyboard'] },
      { emoji: '🖱️', keywords: ['computer', 'mouse'] },
      { emoji: '🖲️', keywords: ['trackball'] },
      { emoji: '💽', keywords: ['minidisc'] },
      { emoji: '💾', keywords: ['floppy', 'disk', 'save'] },
      { emoji: '💿', keywords: ['optical', 'disk'] },
      { emoji: '📀', keywords: ['dvd'] },
      { emoji: '🧮', keywords: ['abacus'] },
      { emoji: '🎥', keywords: ['movie', 'camera'] },
      { emoji: '🎞️', keywords: ['film', 'frames'] },
      { emoji: '📽️', keywords: ['film', 'projector'] },
      { emoji: '🎬', keywords: ['clapper', 'board'] },
      { emoji: '📺', keywords: ['television'] },
      { emoji: '📷', keywords: ['camera'] },
      { emoji: '📸', keywords: ['camera', 'flash'] },
      { emoji: '📹', keywords: ['video', 'camera'] },
      { emoji: '📼', keywords: ['videocassette'] },
      { emoji: '🔍', keywords: ['magnifying', 'left'] },
      { emoji: '🔎', keywords: ['magnifying', 'right'] },
      { emoji: '🕯️', keywords: ['candle'] },
      { emoji: '💡', keywords: ['light', 'bulb', 'idea'] },
      { emoji: '🔦', keywords: ['flashlight'] },
      { emoji: '🏮', keywords: ['red', 'lantern'] },
      { emoji: '🪔', keywords: ['diya', 'lamp'] },
      { emoji: '📔', keywords: ['notebook', 'cover'] },
      { emoji: '📕', keywords: ['closed', 'book'] },
      { emoji: '📖', keywords: ['open', 'book'] },
      { emoji: '📗', keywords: ['green', 'book'] },
      { emoji: '📘', keywords: ['blue', 'book'] },
      { emoji: '📙', keywords: ['orange', 'book'] },
      { emoji: '📚', keywords: ['books'] },
      { emoji: '📓', keywords: ['notebook'] },
      { emoji: '📒', keywords: ['ledger'] },
      { emoji: '📃', keywords: ['page', 'curl'] },
      { emoji: '📜', keywords: ['scroll'] },
      { emoji: '📄', keywords: ['page'] },
      { emoji: '📰', keywords: ['newspaper'] },
      { emoji: '🗞️', keywords: ['rolled', 'newspaper'] },
      { emoji: '📑', keywords: ['bookmark', 'tabs'] },
      { emoji: '🔖', keywords: ['bookmark'] },
      { emoji: '🏷️', keywords: ['label', 'tag'] },
      { emoji: '💴', keywords: ['yen', 'banknote'] },
      { emoji: '💵', keywords: ['dollar', 'banknote'] },
      { emoji: '💶', keywords: ['euro', 'banknote'] },
      { emoji: '💷', keywords: ['pound', 'banknote'] },
      { emoji: '💸', keywords: ['money', 'wings'] },
      { emoji: '💳', keywords: ['credit', 'card'] },
      { emoji: '🧾', keywords: ['receipt'] },
      { emoji: '💹', keywords: ['chart', 'increasing', 'yen'] },
      { emoji: '💱', keywords: ['currency', 'exchange'] },
      { emoji: '💲', keywords: ['heavy', 'dollar'] },
      { emoji: '✉️', keywords: ['envelope'] },
      { emoji: '📧', keywords: ['email'] },
      { emoji: '📨', keywords: ['incoming', 'envelope'] },
      { emoji: '📩', keywords: ['envelope', 'arrow'] },
      { emoji: '📤', keywords: ['outbox', 'tray'] },
      { emoji: '📥', keywords: ['inbox', 'tray'] },
      { emoji: '📦', keywords: ['package'] },
      { emoji: '📫', keywords: ['mailbox', 'flag'] },
      { emoji: '📪', keywords: ['mailbox', 'lowered'] },
      { emoji: '📬', keywords: ['open', 'mailbox', 'flag'] },
      { emoji: '📭', keywords: ['open', 'mailbox', 'lowered'] },
      { emoji: '📮', keywords: ['postbox'] },
      { emoji: '🗳️', keywords: ['ballot', 'box'] },
      { emoji: '✏️', keywords: ['pencil'] },
      { emoji: '✒️', keywords: ['black', 'nib'] },
      { emoji: '🖋️', keywords: ['fountain', 'pen'] },
      { emoji: '🖊️', keywords: ['pen'] },
      { emoji: '🖌️', keywords: ['paintbrush'] },
      { emoji: '🖍️', keywords: ['crayon'] },
      { emoji: '📝', keywords: ['memo', 'note'] },
      { emoji: '💼', keywords: ['briefcase'] },
      { emoji: '📁', keywords: ['file', 'folder'] },
      { emoji: '📂', keywords: ['open', 'file', 'folder'] },
      { emoji: '🗂️', keywords: ['card', 'index', 'dividers'] },
      { emoji: '📅', keywords: ['calendar'] },
      { emoji: '📆', keywords: ['tear', 'off', 'calendar'] },
      { emoji: '🗒️', keywords: ['spiral', 'notepad'] },
      { emoji: '🗓️', keywords: ['spiral', 'calendar'] },
      { emoji: '📇', keywords: ['card', 'index'] },
      { emoji: '📈', keywords: ['chart', 'up'] },
      { emoji: '📉', keywords: ['chart', 'down'] },
      { emoji: '📊', keywords: ['bar', 'chart'] },
      { emoji: '📋', keywords: ['clipboard'] },
      { emoji: '📌', keywords: ['pushpin'] },
      { emoji: '📍', keywords: ['round', 'pushpin'] },
      { emoji: '📎', keywords: ['paperclip'] },
      { emoji: '🖇️', keywords: ['linked', 'paperclips'] },
      { emoji: '📏', keywords: ['straight', 'ruler'] },
      { emoji: '📐', keywords: ['triangular', 'ruler'] },
      { emoji: '✂️', keywords: ['scissors'] },
      { emoji: '🗃️', keywords: ['card', 'file', 'box'] },
      { emoji: '🗄️', keywords: ['file', 'cabinet'] },
      { emoji: '🗑️', keywords: ['wastebasket', 'trash'] },
      { emoji: '🔓', keywords: ['unlocked'] },
      { emoji: '🔏', keywords: ['locked', 'pen'] },
      { emoji: '🔐', keywords: ['locked', 'key'] },
      { emoji: '🗝️', keywords: ['old', 'key'] },
      { emoji: '🔨', keywords: ['hammer'] },
      { emoji: '🪓', keywords: ['axe'] },
      { emoji: '⚒️', keywords: ['hammer', 'pick'] },
      { emoji: '🛠️', keywords: ['hammer', 'wrench'] },
      { emoji: '🗡️', keywords: ['dagger'] },
      { emoji: '⚔️', keywords: ['crossed', 'swords'] },
      { emoji: '💣', keywords: ['bomb'] },
      { emoji: '🪃', keywords: ['boomerang'] },
      { emoji: '🏹', keywords: ['bow', 'arrow'] },
      { emoji: '🪚', keywords: ['carpentry', 'saw'] },
      { emoji: '🔧', keywords: ['wrench'] },
      { emoji: '🪛', keywords: ['screwdriver'] },
      { emoji: '🔩', keywords: ['nut', 'bolt'] },
      { emoji: '⚙️', keywords: ['gear'] },
      { emoji: '🗜️', keywords: ['clamp'] },
      { emoji: '⚖️', keywords: ['balance', 'scale'] },
      { emoji: '🦯', keywords: ['white', 'cane'] },
      { emoji: '🔗', keywords: ['link'] },
      { emoji: '⛓️', keywords: ['chains'] },
      { emoji: '🪝', keywords: ['hook'] },
      { emoji: '🧰', keywords: ['toolbox'] },
      { emoji: '🧲', keywords: ['magnet'] },
      { emoji: '🪜', keywords: ['ladder'] },
      { emoji: '⚗️', keywords: ['alembic'] },
      { emoji: '🧪', keywords: ['test', 'tube'] },
      { emoji: '🧫', keywords: ['petri', 'dish'] },
      { emoji: '🧬', keywords: ['dna'] },
      { emoji: '🔬', keywords: ['microscope'] },
      { emoji: '🔭', keywords: ['telescope'] },
      { emoji: '📡', keywords: ['satellite', 'antenna'] },
      { emoji: '💉', keywords: ['syringe'] },
      { emoji: '🩸', keywords: ['blood', 'drop'] },
      { emoji: '💊', keywords: ['pill'] },
      { emoji: '🩹', keywords: ['adhesive', 'bandage'] },
      { emoji: '🩼', keywords: ['crutch'] },
      { emoji: '🩺', keywords: ['stethoscope'] },
      { emoji: '🩻', keywords: ['x-ray'] },
      { emoji: '🚪', keywords: ['door'] },
      { emoji: '🛗', keywords: ['elevator'] },
      { emoji: '🪞', keywords: ['mirror'] },
      { emoji: '🪟', keywords: ['window'] },
      { emoji: '🛏️', keywords: ['bed'] },
      { emoji: '🛋️', keywords: ['couch', 'lamp'] },
      { emoji: '🪑', keywords: ['chair'] },
      { emoji: '🚽', keywords: ['toilet'] },
      { emoji: '🪠', keywords: ['plunger'] },
      { emoji: '🚿', keywords: ['shower'] },
      { emoji: '🛁', keywords: ['bathtub'] },
      { emoji: '🪤', keywords: ['mouse', 'trap'] },
      { emoji: '🪒', keywords: ['razor'] },
      { emoji: '🧴', keywords: ['lotion'] },
      { emoji: '🧷', keywords: ['safety', 'pin'] },
      { emoji: '🧹', keywords: ['broom'] },
      { emoji: '🧺', keywords: ['basket'] },
      { emoji: '🧻', keywords: ['roll', 'paper'] },
      { emoji: '🪣', keywords: ['bucket'] },
      { emoji: '🧼', keywords: ['soap'] },
      { emoji: '🪥', keywords: ['toothbrush'] },
      { emoji: '🧽', keywords: ['sponge'] },
      { emoji: '🧯', keywords: ['fire', 'extinguisher'] },
      { emoji: '🛒', keywords: ['shopping', 'cart'] },
      { emoji: '🚬', keywords: ['cigarette'] },
      { emoji: '⚰️', keywords: ['coffin'] },
      { emoji: '🪦', keywords: ['headstone'] },
      { emoji: '⚱️', keywords: ['funeral', 'urn'] },
      { emoji: '🗿', keywords: ['moai'] },
      { emoji: '🪧', keywords: ['placard'] },
      { emoji: '🪪', keywords: ['identification', 'card'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      { emoji: '⚠️', keywords: ['warning'] },
      { emoji: '🚸', keywords: ['children', 'crossing'] },
      { emoji: '⛔', keywords: ['no', 'entry'] },
      { emoji: '🚫', keywords: ['prohibited'] },
      { emoji: '🚳', keywords: ['no', 'bicycles'] },
      { emoji: '🚭', keywords: ['no', 'smoking'] },
      { emoji: '🚯', keywords: ['no', 'littering'] },
      { emoji: '🚱', keywords: ['non', 'potable'] },
      { emoji: '🚷', keywords: ['no', 'pedestrians'] },
      { emoji: '📵', keywords: ['no', 'mobile', 'phones'] },
      { emoji: '🔞', keywords: ['no', 'under', '18'] },
      { emoji: '☢️', keywords: ['radioactive'] },
      { emoji: '☣️', keywords: ['biohazard'] },
      { emoji: '⬆️', keywords: ['up', 'arrow'] },
      { emoji: '↗️', keywords: ['up', 'right', 'arrow'] },
      { emoji: '➡️', keywords: ['right', 'arrow'] },
      { emoji: '↘️', keywords: ['down', 'right', 'arrow'] },
      { emoji: '⬇️', keywords: ['down', 'arrow'] },
      { emoji: '↙️', keywords: ['down', 'left', 'arrow'] },
      { emoji: '⬅️', keywords: ['left', 'arrow'] },
      { emoji: '↖️', keywords: ['up', 'left', 'arrow'] },
      { emoji: '↕️', keywords: ['up', 'down', 'arrow'] },
      { emoji: '↔️', keywords: ['left', 'right', 'arrow'] },
      { emoji: '↩️', keywords: ['right', 'hook', 'arrow'] },
      { emoji: '↪️', keywords: ['left', 'hook', 'arrow'] },
      { emoji: '⤴️', keywords: ['arrow', 'curving', 'up'] },
      { emoji: '⤵️', keywords: ['arrow', 'curving', 'down'] },
      { emoji: '🔃', keywords: ['clockwise', 'arrows'] },
      { emoji: '🔄', keywords: ['counterclockwise', 'arrows'] },
      { emoji: '🔙', keywords: ['back', 'arrow'] },
      { emoji: '🔚', keywords: ['end', 'arrow'] },
      { emoji: '🔛', keywords: ['on', 'arrow'] },
      { emoji: '🔜', keywords: ['soon', 'arrow'] },
      { emoji: '🔝', keywords: ['top', 'arrow'] },
      { emoji: '🛐', keywords: ['place', 'worship'] },
      { emoji: '⚛️', keywords: ['atom'] },
      { emoji: '🕉️', keywords: ['om'] },
      { emoji: '✡️', keywords: ['star', 'david'] },
      { emoji: '☸️', keywords: ['wheel', 'dharma'] },
      { emoji: '☯️', keywords: ['yin', 'yang'] },
      { emoji: '✝️', keywords: ['latin', 'cross'] },
      { emoji: '☦️', keywords: ['orthodox', 'cross'] },
      { emoji: '☪️', keywords: ['star', 'crescent'] },
      { emoji: '☮️', keywords: ['peace'] },
      { emoji: '🕎', keywords: ['menorah'] },
      { emoji: '🔯', keywords: ['dotted', 'star'] },
      { emoji: '♈', keywords: ['aries'] },
      { emoji: '♉', keywords: ['taurus'] },
      { emoji: '♊', keywords: ['gemini'] },
      { emoji: '♋', keywords: ['cancer'] },
      { emoji: '♌', keywords: ['leo'] },
      { emoji: '♍', keywords: ['virgo'] },
      { emoji: '♎', keywords: ['libra'] },
      { emoji: '♏', keywords: ['scorpio'] },
      { emoji: '♐', keywords: ['sagittarius'] },
      { emoji: '♑', keywords: ['capricorn'] },
      { emoji: '♒', keywords: ['aquarius'] },
      { emoji: '♓', keywords: ['pisces'] },
      { emoji: '⛎', keywords: ['ophiuchus'] },
      { emoji: '🔀', keywords: ['shuffle'] },
      { emoji: '🔁', keywords: ['repeat'] },
      { emoji: '🔂', keywords: ['repeat', 'single'] },
      { emoji: '▶️', keywords: ['play', 'button'] },
      { emoji: '⏩', keywords: ['fast', 'forward'] },
      { emoji: '⏭️', keywords: ['next', 'track'] },
      { emoji: '⏯️', keywords: ['play', 'pause'] },
      { emoji: '◀️', keywords: ['reverse', 'button'] },
      { emoji: '⏪', keywords: ['fast', 'reverse'] },
      { emoji: '⏮️', keywords: ['previous', 'track'] },
      { emoji: '🔼', keywords: ['up', 'button'] },
      { emoji: '⏫', keywords: ['fast', 'up'] },
      { emoji: '🔽', keywords: ['down', 'button'] },
      { emoji: '⏬', keywords: ['fast', 'down'] },
      { emoji: '⏸️', keywords: ['pause', 'button'] },
      { emoji: '⏹️', keywords: ['stop', 'button'] },
      { emoji: '⏺️', keywords: ['record', 'button'] },
      { emoji: '⏏️', keywords: ['eject', 'button'] },
      { emoji: '🎦', keywords: ['cinema'] },
      { emoji: '🔅', keywords: ['dim', 'button'] },
      { emoji: '🔆', keywords: ['bright', 'button'] },
      { emoji: '📶', keywords: ['antenna', 'bars'] },
      { emoji: '🛜', keywords: ['wireless'] },
      { emoji: '📳', keywords: ['vibration'] },
      { emoji: '📴', keywords: ['phone', 'off'] },
      { emoji: '♀️', keywords: ['female', 'sign'] },
      { emoji: '♂️', keywords: ['male', 'sign'] },
      { emoji: '⚧️', keywords: ['transgender', 'symbol'] },
      { emoji: '✖️', keywords: ['multiply'] },
      { emoji: '➕', keywords: ['plus'] },
      { emoji: '➖', keywords: ['minus'] },
      { emoji: '➗', keywords: ['divide'] },
      { emoji: '🟰', keywords: ['equals'] },
      { emoji: '♾️', keywords: ['infinity'] },
      { emoji: '‼️', keywords: ['double', 'exclamation'] },
      { emoji: '⁉️', keywords: ['exclamation', 'question'] },
      { emoji: '❓', keywords: ['red', 'question'] },
      { emoji: '❔', keywords: ['white', 'question'] },
      { emoji: '❕', keywords: ['white', 'exclamation'] },
      { emoji: '❗', keywords: ['red', 'exclamation'] },
      { emoji: '〰️', keywords: ['wavy', 'dash'] },
      { emoji: '⚕️', keywords: ['medical', 'symbol'] },
      { emoji: '♻️', keywords: ['recycling'] },
      { emoji: '⚜️', keywords: ['fleur', 'lis'] },
      { emoji: '🔱', keywords: ['trident'] },
      { emoji: '📛', keywords: ['name', 'badge'] },
      { emoji: '🔰', keywords: ['japanese', 'beginner'] },
      { emoji: '⭕', keywords: ['hollow', 'red', 'circle'] },
      { emoji: '✅', keywords: ['check', 'mark'] },
      { emoji: '☑️', keywords: ['ballot', 'check'] },
      { emoji: '✔️', keywords: ['heavy', 'check'] },
      { emoji: '❌', keywords: ['cross', 'mark'] },
      { emoji: '❎', keywords: ['cross', 'button'] },
      { emoji: '➰', keywords: ['curly', 'loop'] },
      { emoji: '➿', keywords: ['double', 'curly', 'loop'] },
      { emoji: '〽️', keywords: ['part', 'alternation'] },
      { emoji: '✳️', keywords: ['eight', 'spoked'] },
      { emoji: '✴️', keywords: ['eight', 'pointed'] },
      { emoji: '❇️', keywords: ['sparkle'] },
      { emoji: '©️', keywords: ['copyright'] },
      { emoji: '®️', keywords: ['registered'] },
      { emoji: '™️', keywords: ['trademark'] },
      { emoji: '#️⃣', keywords: ['keycap', 'hash'] },
      { emoji: '*️⃣', keywords: ['keycap', 'asterisk'] },
      { emoji: '0️⃣', keywords: ['keycap', 'zero'] },
      { emoji: '1️⃣', keywords: ['keycap', 'one'] },
      { emoji: '2️⃣', keywords: ['keycap', 'two'] },
      { emoji: '3️⃣', keywords: ['keycap', 'three'] },
      { emoji: '4️⃣', keywords: ['keycap', 'four'] },
      { emoji: '5️⃣', keywords: ['keycap', 'five'] },
      { emoji: '6️⃣', keywords: ['keycap', 'six'] },
      { emoji: '7️⃣', keywords: ['keycap', 'seven'] },
      { emoji: '8️⃣', keywords: ['keycap', 'eight'] },
      { emoji: '9️⃣', keywords: ['keycap', 'nine'] },
      { emoji: '🔟', keywords: ['keycap', 'ten'] },
      { emoji: '🔠', keywords: ['input', 'uppercase'] },
      { emoji: '🔡', keywords: ['input', 'lowercase'] },
      { emoji: '🔢', keywords: ['input', 'numbers'] },
      { emoji: '🔣', keywords: ['input', 'symbols'] },
      { emoji: '🔤', keywords: ['input', 'latin'] },
      { emoji: '🆎', keywords: ['ab', 'blood'] },
      { emoji: '🆑', keywords: ['cl', 'button'] },
      { emoji: '🆒', keywords: ['cool'] },
      { emoji: '🆓', keywords: ['free'] },
      { emoji: 'ℹ️', keywords: ['information'] },
      { emoji: '🆔', keywords: ['id'] },
      { emoji: 'Ⓜ️', keywords: ['circled', 'm'] },
      { emoji: '🆕', keywords: ['new'] },
      { emoji: '🆖', keywords: ['ng'] },
      { emoji: '🆗', keywords: ['ok'] },
      { emoji: '🆘', keywords: ['sos'] },
      { emoji: '🆙', keywords: ['up'] },
      { emoji: '🆚', keywords: ['vs'] },
      { emoji: '🔴', keywords: ['red', 'circle'] },
      { emoji: '🟠', keywords: ['orange', 'circle'] },
      { emoji: '🟡', keywords: ['yellow', 'circle'] },
      { emoji: '🟢', keywords: ['green', 'circle'] },
      { emoji: '🔵', keywords: ['blue', 'circle'] },
      { emoji: '🟣', keywords: ['purple', 'circle'] },
      { emoji: '🟤', keywords: ['brown', 'circle'] },
      { emoji: '⚫', keywords: ['black', 'circle'] },
      { emoji: '⚪', keywords: ['white', 'circle'] },
      { emoji: '🟥', keywords: ['red', 'square'] },
      { emoji: '🟧', keywords: ['orange', 'square'] },
      { emoji: '🟨', keywords: ['yellow', 'square'] },
      { emoji: '🟩', keywords: ['green', 'square'] },
      { emoji: '🟦', keywords: ['blue', 'square'] },
      { emoji: '🟪', keywords: ['purple', 'square'] },
      { emoji: '🟫', keywords: ['brown', 'square'] },
      { emoji: '⬛', keywords: ['black', 'square'] },
      { emoji: '⬜', keywords: ['white', 'square'] },
      { emoji: '◼️', keywords: ['black', 'medium', 'square'] },
      { emoji: '◻️', keywords: ['white', 'medium', 'square'] },
      { emoji: '◾', keywords: ['black', 'small', 'square'] },
      { emoji: '◽', keywords: ['white', 'small', 'square'] },
      { emoji: '🔶', keywords: ['large', 'orange', 'diamond'] },
      { emoji: '🔷', keywords: ['large', 'blue', 'diamond'] },
      { emoji: '🔸', keywords: ['small', 'orange', 'diamond'] },
      { emoji: '🔹', keywords: ['small', 'blue', 'diamond'] },
      { emoji: '🔺', keywords: ['red', 'triangle', 'up'] },
      { emoji: '🔻', keywords: ['red', 'triangle', 'down'] },
      { emoji: '💠', keywords: ['diamond', 'dot'] },
      { emoji: '🔘', keywords: ['radio', 'button'] },
      { emoji: '🔳', keywords: ['white', 'button'] },
      { emoji: '🔲', keywords: ['black', 'button'] },
      { emoji: '💯', keywords: ['hundred', 'perfect'] },
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏁',
    emojis: [
      { emoji: '🏁', keywords: ['chequered', 'flag', 'race'] },
      { emoji: '🚩', keywords: ['triangular', 'flag'] },
      { emoji: '🎌', keywords: ['crossed', 'flags'] },
      { emoji: '🏴', keywords: ['black', 'flag'] },
      { emoji: '🏳️', keywords: ['white', 'flag'] },
      { emoji: '🏳️‍🌈', keywords: ['rainbow', 'flag', 'pride'] },
      { emoji: '🏳️‍⚧️', keywords: ['transgender', 'flag'] },
      { emoji: '🏴‍☠️', keywords: ['pirate', 'flag', 'skull'] },
      { emoji: '🇺🇸', keywords: ['united', 'states', 'usa', 'america'] },
      { emoji: '🇬🇧', keywords: ['united', 'kingdom', 'uk', 'britain'] },
      { emoji: '🇨🇦', keywords: ['canada'] },
      { emoji: '🇲🇽', keywords: ['mexico'] },
      { emoji: '🇧🇷', keywords: ['brazil'] },
      { emoji: '🇦🇷', keywords: ['argentina'] },
      { emoji: '🇸🇻', keywords: ['el', 'salvador'] },
      { emoji: '🇫🇷', keywords: ['france'] },
      { emoji: '🇩🇪', keywords: ['germany'] },
      { emoji: '🇪🇸', keywords: ['spain'] },
      { emoji: '🇮🇹', keywords: ['italy'] },
      { emoji: '🇵🇹', keywords: ['portugal'] },
      { emoji: '🇳🇱', keywords: ['netherlands', 'holland'] },
      { emoji: '🇧🇪', keywords: ['belgium'] },
      { emoji: '🇨🇭', keywords: ['switzerland'] },
      { emoji: '🇦🇹', keywords: ['austria'] },
      { emoji: '🇸🇪', keywords: ['sweden'] },
      { emoji: '🇳🇴', keywords: ['norway'] },
      { emoji: '🇩🇰', keywords: ['denmark'] },
      { emoji: '🇫🇮', keywords: ['finland'] },
      { emoji: '🇮🇸', keywords: ['iceland'] },
      { emoji: '🇮🇪', keywords: ['ireland'] },
      { emoji: '🇵🇱', keywords: ['poland'] },
      { emoji: '🇨🇿', keywords: ['czech', 'republic', 'czechia'] },
      { emoji: '🇭🇺', keywords: ['hungary'] },
      { emoji: '🇬🇷', keywords: ['greece'] },
      { emoji: '🇹🇷', keywords: ['turkey'] },
      { emoji: '🇷🇺', keywords: ['russia'] },
      { emoji: '🇺🇦', keywords: ['ukraine'] },
      { emoji: '🇷🇴', keywords: ['romania'] },
      { emoji: '🇧🇬', keywords: ['bulgaria'] },
      { emoji: '🇭🇷', keywords: ['croatia'] },
      { emoji: '🇷🇸', keywords: ['serbia'] },
      { emoji: '🇨🇳', keywords: ['china'] },
      { emoji: '🇯🇵', keywords: ['japan'] },
      { emoji: '🇰🇷', keywords: ['south', 'korea'] },
      { emoji: '🇰🇵', keywords: ['north', 'korea'] },
      { emoji: '🇮🇳', keywords: ['india'] },
      { emoji: '🇵🇰', keywords: ['pakistan'] },
      { emoji: '🇧🇩', keywords: ['bangladesh'] },
      { emoji: '🇹🇭', keywords: ['thailand'] },
      { emoji: '🇻🇳', keywords: ['vietnam'] },
      { emoji: '🇵🇭', keywords: ['philippines'] },
      { emoji: '🇮🇩', keywords: ['indonesia'] },
      { emoji: '🇲🇾', keywords: ['malaysia'] },
      { emoji: '🇸🇬', keywords: ['singapore'] },
      { emoji: '🇹🇼', keywords: ['taiwan'] },
      { emoji: '🇭🇰', keywords: ['hong', 'kong'] },
      { emoji: '🇦🇺', keywords: ['australia'] },
      { emoji: '🇳🇿', keywords: ['new', 'zealand'] },
      { emoji: '🇿🇦', keywords: ['south', 'africa'] },
      { emoji: '🇳🇬', keywords: ['nigeria'] },
      { emoji: '🇰🇪', keywords: ['kenya'] },
      { emoji: '🇪🇬', keywords: ['egypt'] },
      { emoji: '🇲🇦', keywords: ['morocco'] },
      { emoji: '🇮🇱', keywords: ['israel'] },
      { emoji: '🇸🇦', keywords: ['saudi', 'arabia'] },
      { emoji: '🇦🇪', keywords: ['united', 'arab', 'emirates', 'uae'] },
      { emoji: '🇮🇷', keywords: ['iran'] },
      { emoji: '🇮🇶', keywords: ['iraq'] },
      { emoji: '🇨🇱', keywords: ['chile'] },
      { emoji: '🇨🇴', keywords: ['colombia'] },
      { emoji: '🇵🇪', keywords: ['peru'] },
      { emoji: '🇻🇪', keywords: ['venezuela'] },
      { emoji: '🇺🇾', keywords: ['uruguay'] },
      { emoji: '🇪🇺', keywords: ['european', 'union', 'eu'] },
      { emoji: '🇺🇳', keywords: ['united', 'nations', 'un'] },
    ],
  },
];

export const ALL_EMOJIS: EmojiEntry[] = CATEGORIES.flatMap((c) => c.emojis);

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  // Deduplicate by emoji character (same emoji may appear in multiple categories)
  const seen = new Set<string>();
  const results: EmojiEntry[] = [];
  for (const entry of ALL_EMOJIS) {
    if (seen.has(entry.emoji)) continue;
    if (entry.keywords.some((kw) => kw.startsWith(q)) || entry.emoji === q) {
      seen.add(entry.emoji);
      results.push(entry);
    }
  }
  return results;
}
