#!/usr/bin/env node
import assert from "node:assert/strict";
import { readFile, writeFile, rename } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const source = "app/assets/brand/source/symbol.svg";

export async function siteBrandFiles() {
  const master = await readFile(new URL(source, root), "utf8");
  const paths = [...master.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)];
  assert.equal(
    paths.length,
    1,
    "The canonical symbol must have one compound path",
  );
  const path = `<path fill="#ffffff" d="${paths[0][1]}"/>`;
  const mark = `<!-- Generated by scripts/site-brand.mjs from ${source}. -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 621 621">${path}</svg>\n`;

  // The QR grid remains the reviewed static encoding. Only this existing logo
  // slot is generator-owned; do not re-encode the destination or move its mask.
  const qrFile = "site/public/downloads/download-qr.svg";
  const qr = await readFile(new URL(qrFile, root), "utf8");
  const slot =
    /<g transform="translate\(23 20\) scale\(0\.135\)">[\s\S]*?<\/g>/g;
  assert.equal(
    [...qr.matchAll(slot)].length,
    1,
    "Expected one download QR logo slot",
  );
  return {
    "site/public/sovran-mark.svg": mark,
    [qrFile]: qr.replace(
      slot,
      `<g transform="translate(23 20) scale(0.135)">${path}</g>`,
    ),
  };
}

export async function generateSiteBrand({ check = false } = {}) {
  const files = await siteBrandFiles();
  for (const [name, contents] of Object.entries(files)) {
    const file = new URL(name, root);
    if (check) {
      assert.equal(
        await readFile(file, "utf8"),
        contents,
        `Stale site logo: ${name}; run node scripts/site-brand.mjs`,
      );
    } else {
      const temporary = new URL(`${name}.tmp`, root);
      await writeFile(temporary, contents);
      await rename(temporary, file);
    }
  }
  return files;
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  assert(
    process.argv.length === 2 ||
      (process.argv.length === 3 && process.argv[2] === "--check"),
    "Usage: node scripts/site-brand.mjs [--check]",
  );
  await generateSiteBrand({ check: process.argv[2] === "--check" });
  console.log(
    `${process.argv[2] === "--check" ? "Verified" : "Generated"} site mark and download QR logo from ${source}.`,
  );
}
