const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');

// Generated metadata lets pre-hydration migrations enumerate lazy stores without
// importing them (which would initialize native dependencies and start hydration).
function collectStoreDefinitions(appRoot = root) {
  const definitions = [];
  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!['__tests__', 'node_modules'].includes(entry.name)) walk(file);
        continue;
      }
      if (
        !/\.tsx?$/.test(file) ||
        file.endsWith('createQueryCacheStore.ts') ||
        file.endsWith('defineStore.ts')
      )
        continue;
      const source = ts.createSourceFile(
        file,
        fs.readFileSync(file, 'utf8'),
        ts.ScriptTarget.Latest,
        true
      );
      source.forEachChild((node) => {
        if (
          ts.isImportDeclaration(node) &&
          ['zustand', 'zustand/vanilla'].includes(node.moduleSpecifier.text)
        ) {
          const bindings = node.importClause?.namedBindings;
          if (bindings && ts.isNamespaceImport(bindings))
            throw new Error(`Unregistered store import: ${file}`);
          for (const binding of bindings?.elements ?? []) {
            if (['create', 'createStore'].includes((binding.propertyName ?? binding.name).text)) {
              throw new Error(`Unregistered store import: ${file}`);
            }
          }
        }
      });
      const factories = new Set(['createQueryCacheStore']);
      source.forEachChild((node) => {
        if (ts.isImportDeclaration(node) && node.moduleSpecifier.text.endsWith('defineStore')) {
          for (const binding of node.importClause?.namedBindings?.elements ?? [])
            factories.add(binding.name.text);
        }
      });
      const persistedKeys = [];
      function visit(node) {
        if (
          ts.isCallExpression(node) &&
          ts.isIdentifier(node.expression) &&
          node.expression.text === 'persistConfig' &&
          node.arguments[0] &&
          ts.isObjectLiteralExpression(node.arguments[0])
        ) {
          for (const property of node.arguments[0].properties) {
            if (
              ts.isPropertyAssignment(property) &&
              property.name.getText(source) === 'name' &&
              ts.isStringLiteral(property.initializer)
            )
              persistedKeys.push(property.initializer.text);
          }
        }
        if (
          ts.isCallExpression(node) &&
          ts.isIdentifier(node.expression) &&
          factories.has(node.expression.text)
        ) {
          const options = node.arguments[0];
          if (!options || !ts.isObjectLiteralExpression(options))
            throw new Error(`Missing store definition: ${file}`);
          const values = {};
          for (const property of options.properties) {
            if (ts.isPropertyAssignment(property))
              values[property.name.getText(source)] = ts.isStringLiteral(property.initializer)
                ? property.initializer.text
                : property.initializer.getText(source);
          }
          if (!values.name || !values.scope) throw new Error(`Missing name/scope: ${file}`);
          const queryCache = node.expression.text === 'createQueryCacheStore';
          definitions.push({
            file: path.relative(appRoot, file),
            name: values.name,
            scope: values.scope,
            persisted: queryCache
              ? values.persist !== 'false'
              : node.parent.getText(source).includes('persistConfig'),
            queryCache,
            profileStorage: queryCache ? values.hostScoped !== 'true' : values.scope === 'profile',
          });
        }
        ts.forEachChild(node, visit);
      }
      visit(source);
      for (const name of persistedKeys) {
        if (
          !definitions.some(
            (entry) =>
              entry.file === path.relative(appRoot, file) && entry.name === name && entry.persisted
          )
        ) {
          throw new Error(`Unregistered persisted key: ${file}: ${name}`);
        }
      }
    }
  }
  for (const dir of ['shared', 'features', 'app']) walk(path.join(appRoot, dir));
  return definitions.sort((a, b) => a.file.localeCompare(b.file) || a.name.localeCompare(b.name));
}
module.exports = { collectStoreDefinitions };
if (require.main === module) {
  fs.writeFileSync(
    path.join(root, 'shared/lib/persist/storeRegistryManifest.ts'),
    '// Generated by `bun run store-registry:update`. Do not edit by hand.\n' +
      'export const storeRegistryManifest = ' +
      JSON.stringify(collectStoreDefinitions(), null, 2) +
      ' as const;\n'
  );
}
