executionOrder:
  continueOnFailure: false
  flowsOrder:
    - Create Account
    - Receive Lightning With Note
    - Receive Lightning Without Note
    - Send Ecash Without Note

flows:
  - onboarding/*
  - receive/*
  - send/*
